### ISSUE TITLE
Make namespace initialisation work on Windows

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#1007]
I recommend adding unit tests to reproduce the problems that `riff namespace init` exhibits on Windows and then fixing the code so the unit tests pass and `riff namespace init` works successfully.

**Comment by trisberg** [comment]
Did you try with a `--manifest` flag using a file location? That's when I saw errors. I'm away from my Windows system ATM. I can try when I get back to it later.

**Comment by glyn** [comment]
Yes, that worked fine too. Make sure you delete your old riff.exe.

**Comment by glyn** [comment]
@trisberg Are you ready to close this issue now?

**Comment by trisberg** [comment]
let me test it

**Comment by trisberg** [comment]
Still getting errors running `riff namespace init -m ...`:

```
PS C:\Users\trisberg> riff version
Version
  riff cli: 0.3.0-snapshot (9664376303c3807e94e923a685d0b669af797be7)
PS C:\Users\trisberg> riff namespace init test --dockerhub trisberg --manifest file:///Users/trisberg/Downloads/manifest
.yaml
panic: readAbsFile called with relative file path: Users/trisberg/Downloads/manifest.yaml

goroutine 1 [running]:
github.com/projectriff/riff/pkg/fileutils.readAbsFile(0xc000036a88, 0x26, 0x0, 0x0, 0xc000036a80, 0x2e, 0x0)
        C:/Users/trisberg/go/src/github.com/projectriff/riff/pkg/fileutils/read.go:92 +0x2f4
github.com/projectriff/riff/pkg/fileutils.Read(0xc000036300, 0x2e, 0x0, 0x0, 0x148e801, 0xc0004146fe, 0x1, 0x0, 0x0)
        C:/Users/trisberg/go/src/github.com/projectriff/riff/pkg/fileutils/read.go:38 +0xa6
github.com/projectriff/riff/pkg/core.NewManifest(0xc000036300, 0x2e, 0xc000036300, 0x2e, 0x1fb50a0)
        C:/Users/trisberg/go/src/github.com/projectriff/riff/pkg/core/manifest.go:48 +0x76
github.com/projectriff/riff/pkg/core.ResolveManifest(0xc0004a9b90, 0xc000036300, 0x2e, 0x14b4301, 0xc000535de0, 0xc000525970)
        C:/Users/trisberg/go/src/github.com/projectriff/riff/pkg/core/manifest.go:43 +0x97
github.com/projectriff/riff/pkg/core.(*kubectlClient).NamespaceInit(0xc000535e00, 0xc0004a9b90, 0xc0000340d0, 0x4, 0xc000036300, 0x2e, 0x0, 0x133a11e, 0x10, 0x0, ...)
        C:/Users/trisberg/go/src/github.com/projectriff/riff/pkg/core/namespace.go:79 +0x64
github.com/projectriff/riff/cmd/commands.NamespaceInit.func1(0xc000027b80, 0xc0000b5540, 0x1, 0x5, 0x0, 0x0)
        C:/Users/trisberg/go/src/github.com/projectriff/riff/cmd/commands/namespace.go:60 +0xa5
github.com/projectriff/riff/cmd/commands.CreateAndWireRootCommand.func1.1(0xc000027b80, 0xc0000b5540, 0x1, 0x5, 0x0, 0x0)
        C:/Users/trisberg/go/src/github.com/projectriff/riff/cmd/commands/wiring.go:170 +0x5f
github.com/projectriff/riff/vendor/github.com/spf13/cobra.(*Command).execute(0xc000027b80, 0xc0000b54f0, 0x5, 0x5, 0xc000027b80, 0xc0000b54f0)
        C:/Users/trisberg/go/src/github.com/projectriff/riff/vendor/github.com/spf13/cobra/command.go:762 +0x47a
github.com/projectriff/riff/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00000d180, 0x133d21a, 0x13, 0x1333a09)
        C:/Users/trisberg/go/src/github.com/projectriff/riff/vendor/github.com/spf13/cobra/command.go:852 +0x304
main.main()
        C:/Users/trisberg/go/src/github.com/projectriff/riff/main.go:70 +0x76
```

or without file url:

```
PS C:\Users\trisberg> riff namespace init test --dockerhub trisberg --manifest Downloads/manifest.yaml
Initializing namespace "test"

Enter dockerhub password for user "trisberg"
Creating secret "push-credentials" with DockerHub authentication for user "trisberg"
Serviceaccount "riff-build" already exists in namespace "test" with secret "push-credentials". Skipping.
Applying riff-cnb-buildtemplate-0.1.0-66c3cc7a6054c438d8505b30cf4772a9.yaml in namespace "test"
error: the path "Downloads\\riff-cnb-buildtemplate-0.1.0-66c3cc7a6054c438d8505b30cf4772a9.yaml" does not exist


Error: exit status 1
```

**Comment by trisberg** [comment]
otherwise it seems to work specifying either relative or absolute path Windows style

**Comment by glyn** [comment]
You can use the following forms of path from a Windows command prompt:
```
C:\path\to\manifest.yaml
file:///C:\path\to\manifest.yaml
\\localhost\c$\path\to\manifest.yaml
file:///\\localhost\c$\path\to\manifest.yaml
```

I think the first two of these are the natural way to write absolute file paths. The second two use UNC paths, which just happen to work thanks to Windows.

However, I don't think we should attempt to support file URLs with UNIX-style paths like the one you tried. It's not clear to me what `file:///path/to/manifest.yaml` would mean when, for example, both the files `C:\path\to\manifest.yaml` and `D:\path\to\manifest.yaml` exist.

You can use the following forms of path from a git bash prompt on Windows:
```
/c/path/to/manifest.yaml
file:///C:/path/to/manifest.yaml
```

Again, we can't support file URLs with UNIX-style paths such as `file:///c/path/to/manifest.yaml` as this form is interpreted as a relative path when we strip off the leading slash of the path.

I'm not sure how much detail to go into in the docs as I don't want to have lots of Windows-specific help. I considered adding that help when executing on Windows, but then that help would be omitted from the generated docs that we check in. I think it's probably best to leave it as is for now as the natural ways of writing paths seem to work.

**Comment by trisberg** [comment]
I can't get any file URLs to work, maybe we should just support absolute and relative Windows style file paths.

```
PS C:\Users\trisberg> riff namespace init test --dockerhub trisberg --manifest file:///C:\Users\trisberg\Downloads\pfs-files\manifest.yaml
Initializing namespace "test"

Enter dockerhub password for user "trisberg"
Creating secret "push-credentials" with DockerHub authentication for user "trisberg"
Serviceaccount "riff-build" already exists in namespace "test" with secret "push-credentials". Skipping.
Applying riff-cnb-buildtemplate-0.1.0-66c3cc7a6054c438d8505b30cf4772a9.yaml in namespace "test"
error: the path "file:\\C:\\Users\\trisberg\\Downloads\\pfs-files\\riff-cnb-buildtemplate-0.1.0-66c3cc7a6054c438d8505b30cf4772a9.yaml" cannot be accessed: CreateFile file:\C:\Users\trisberg\Downloads\pfs-files\riff-cnb-buildtemplate-0.1.0-66c3cc7a6054c438d8505b30cf4772a9.yaml: The filename, directory name, or volume label syntax is incorrect.


Error: exit status 1
```

**Comment by trisberg** [comment]
Resolved for Windows style file paths via https://github.com/glyn/riff/commit/dd63a4add35c7a5b52f2c16f6aadb76057fb8c64

**Comment by trisberg** [comment]
Was this fix ever merged into master or is there a PR? I can't find it other than in the clone under @glyn.

**Comment by trisberg** [comment]
Maybe I've been testing the wrong thing.

**Comment by trisberg** [comment]
Maybe the difference in my testing is that I'm actually applying the manifest which means that the path to the manifest is resolved plus any relative paths included in the manifest needs to get properly resolved as well.

**Comment by glyn** [comment]
I'm afraid https://github.com/glyn/riff/commit/dd63a4add35c7a5b52f2c16f6aadb76057fb8c64 was an early attempt at some testing, it wasn't the subject of a PR, and it wasn't merged.

The relevant PR was actually https://github.com/projectriff/riff/pull/1006 which was merged a while back. So please could you build at the tip and try again?

**Comment by ericbottard** [comment]
From a quick read through this conversation, please note that URLs with the `file:` scheme are **always** absolute paths because the first part, even if missing and assumed to equal localhost, is the host. So everything after that starts from "the root"

**Comment by glyn** [comment]
Reproduced the problem in https://github.com/projectriff/riff/issues/1007#issuecomment-449028600 in a git bash shell as follows:

1. `pfs-distro system download ... -o pfs-download`
2. `pfs-distro image list ...`
3. `mkdir pfsdownload/images`
4. `pfs image relocate ... -o pfs-relocated`
5. `pfs namespace init ... -m file:///C:/workspace/pfs/pfs-relocated/manifest.yaml`

The path showing up in the error was `file:\\C:\\workspace\\pfs\\pfs-relocated\\riff-cnb-buildtemplate-0.1.0.yaml`.

(Step 5 worked if an absolute path `C:/workspace/pfs/pfs-relocated/manifest.yaml` was provided instead.)

**Comment by fbiville** [comment]
Out of curiosity, does `file:C:/workspace/pfs/pfs-relocated/manifest.yaml` also work @glyn?

**Comment by glyn** [comment]
@fbiville Nope - that panics! Feel free to raise a bug and/or fix to return an error instead of panicking. Please note that I tested with the in-flight PR https://github.com/projectriff/riff/pull/1037.

**Comment by trisberg** [comment]
Should we just say that we don't support file URLs? Using absolute paths like `C:\path\to\manifest.yaml` and relative paths like `my-files\manifest.yaml` seem to work fine.

**Comment by glyn** [comment]
Perhaps, although the code is shaking out in PR https://github.com/projectriff/riff/pull/1037 and is making the behaviour in riff and well as PFS more uniform, so I don't think there's much harm in getting some reasonable file URL formats to work.

**Comment by trisberg** [comment]
I tried with the latest changes and now I can get this to work in PowerShell/Command Prompt:

```
--manifest C:\Users\trisberg\Downloads\pfs-files\manifest.yaml
--manifest file:///C:/Users/trisberg/Downloads/pfs-files/manifest.yaml
```

In the Git Bash shell the following works:

```
--manifest C:/Users/trisberg/Downloads/pfs-files/manifest.yam
--manifest file:///C:/Users/trisberg/Downloads/pfs-files/manifest.yaml
--manifest file:///C:\\Users\\trisberg\\Downloads\\pfs-files\\manifest.yaml
--manifest C:\\Users\\trisberg\\Downloads\\pfs-files\\manifest.yaml
```

Most other combinations fail either via a panic or not being able to find the `riff-cnb-buildtemplate` file.

**Comment by glyn** [comment]
@trisberg A panic isn't very friendly. Please could you give an example.

**Comment by trisberg** [comment]
I've only seen panics when using the Git Bash shell.
 
```
$ riff namespace init test --no-secret --manifest file:///C:\Users\trisberg\Downloads\pfs-files\manifest.yaml
panic: readAbsFile called with relative file path: C:UserstrisbergDownloadspfs-filesmanifest.yaml

goroutine 1 [running]:
github.com/projectriff/riff/pkg/fileutils.readAbsFile(0xc0000b0048, 0x2e, 0x0, 0x0, 0xc0000b0048, 0x2e, 0x0)
        C:/Users/trisberg/workspace/projectriff/riff/pkg/fileutils/read.go:52 +0x309
github.com/projectriff/riff/pkg/fileutils.Read(0xc0000b0040, 0x36, 0x0, 0x0, 0x2030001, 0x30001, 0x20, 0xaaabc0, 0x14c5ebd)
        C:/Users/trisberg/workspace/projectriff/riff/pkg/fileutils/read.go:36 +0xa6
github.com/projectriff/riff/pkg/core.NewManifest(0xc0000b0040, 0x36, 0xc0000b0040, 0x36, 0x1f280e0)
        C:/Users/trisberg/workspace/projectriff/riff/pkg/core/manifest.go:50 +0x76
github.com/projectriff/riff/pkg/core.ResolveManifest(0xc0004c7c50, 0xc0000b0040, 0x36, 0x20, 0x1250c00, 0x14ea201)
        C:/Users/trisberg/workspace/projectriff/riff/pkg/core/manifest.go:45 +0x97
github.com/projectriff/riff/pkg/core.(*kubectlClient).NamespaceInit(0xc0004bfe20, 0xc0004c7c50, 0xc00007e0c0, 0x4, 0xc0000b0040, 0x36, 0x1, 0x136dfd1, 0x10, 0x0, ...)
        C:/Users/trisberg/workspace/projectriff/riff/pkg/core/namespace.go:78 +0x64
github.com/projectriff/riff/cmd/commands.NamespaceInit.func1(0xc00000e280, 0xc0004f3f40, 0x1, 0x4, 0x0, 0x0)
        C:/Users/trisberg/workspace/projectriff/riff/cmd/commands/namespace.go:68 +0xa5
github.com/projectriff/riff/cmd/commands.CreateAndWireRootCommand.func1.1(0xc00000e280, 0xc0004f3f40, 0x1, 0x4, 0x0, 0x0)
        C:/Users/trisberg/workspace/projectriff/riff/cmd/commands/wiring.go:171 +0x5f
github.com/spf13/cobra.(*Command).execute(0xc00000e280, 0xc0004f3f00, 0x4, 0x4, 0xc00000e280, 0xc0004f3f00)
        C:/Users/trisberg/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x47a
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004cd680, 0x13710e1, 0x13, 0x136787c)
        C:/Users/trisberg/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x304
main.main()
        C:/Users/trisberg/workspace/projectriff/riff/main.go:70 +0x76
```

**Comment by glyn** [comment]
Ok, thanks @trisberg. I think that error case is legitimate since the backslashes are interpreted as bash escape characters. However, we shouldn't panic in that case. I'll raise a further PR to return a reasonable error rather than panicking.
