### ISSUE TITLE
riff can't pull images, but pushing correct

### ISSUE THREAD

**Issue by set4812** [projectriff/riff#1019]
Hi, I followed start tutorials
https://projectriff.io/docs/getting-started/minikube/
https://projectriff.io/docs/getting-started/gke/ (configure gcr)

and spend evening for getting UNAUTHORIZED error for **docker hub** and gcr. Images was pushed correctly into repo but riff can't pull there. After change **docker hub** or **gcr** to public repo all is working correctly. Secret appear on secret list
![obraz](https://user-images.githubusercontent.com/5082431/50069132-fc549780-01c8-11e9-99fb-7ca0c759412f.png)
I doing something wrong or this is bug?

**Comment by fbiville** [comment]
Hi @set4812, thanks for reporting this.
We have tracked this specific issue and are already working on it.

**Comment by set4812** [comment]
@fbiville thank you for answer. This is possible to use local repository? Public repository is not for me.

**Comment by fbiville** [comment]
Actually @set4812 , my apologies, I read your description a bit too hastily and got it mixed up with another one.
Would you mind retracing step by step what you did and what led to the problem?

**Comment by jldec** [comment]
I can create functions on GKE with images in private GCR repos following the projectriff.io GKE getting started instructions. (create secret for GCR and initialize namespace with --gcr and use gcr.io/project/... image names)

I can also create functions on GKE with images in a public public docker repo, if i first initialize the namespace with --dockerhub and use a docker.io/user/repo... image name.

I can confirm that there is a problem pulling images from a **private** docker repo. You will see errors like this

```
Error: function creation failed: RevisionMissing: Configuration "square" does not have any ready Revision.; Revision "square-00001" failed with message: "UNAUTHORIZED: \"authentication required\"".
```

NOTE: If you want to reinitialize a namespce for building with a different regsitry i suggest doing `kubectl delete serviceaccount riff-build` and `kubectl delete secret push-credentials` before running `riff namespace init`.

**Comment by set4812** [comment]
When i back from work i will post step by step.  I had some error message like @jldec on docker. On GCR  is another message but  UNAUTHORIZED too. I was doing this on minikube on my local PC.

**Comment by jldec** [comment]
Ahh, yes, that makes sense, if you're trying to build from a minikube "cluster" using a private GCR repo for the image, the same problem would apply.

We have a PR in progress to document the steps required to configure an image pull secret for these cases.

see #973

**Comment by set4812** [comment]
@jldec after follow #973 it`s working. Now for docker hub need  similar docs.
Thx for help.

**Comment by lukaszdrabiuk** [comment]
@jldec can we close this?

**Comment by fbiville** [comment]
Private registry support has been documented via #973. 
Feel free to reopen the issue if more help is needed on the matter.
