### ISSUE TITLE
Publish snapshot riff builds somewhere

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#1031]
There are times I'd like to consume a pre-release version of riff but would rather not build it myself. Especially with the move to go modules, building riff from scratch (clean cache) takes a while. Assuming the tests pass it would be nice to publish snapshot binaries for each commit

```
# only from master
gs://projectriff/riff-cli/latest/*

# for master and release branches
gs://projectriff/riff-cli/$(cat VERSION)/*
gs://projectriff/riff-cli/builds/$(cat VERSION)-$(git rev-parse HEAD)/*
```

**Comment by trisberg** [comment]
wouldn't you need the GOARCH as part of the path?

**Comment by trisberg** [comment]
actually we only use amd64 but could add GOOS

**Comment by scothis** [comment]
> wouldn't you need the GOARCH as part of the path?

@trisberg we don't, but only because it's already part of the file name 😄
