### ISSUE TITLE
riff system install fails to install using manifest from local directory on Windows

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#1036]
To reproduce this, download a riff manifest and the corresponding kubernetes configuration files so that `manifest.yaml` looks something like this:
```
manifestVersion: "0.1"
istio:
- istio-riff-knative-serving-v0-2-3.yaml
knative:
- release.yaml
- serving.yaml
- eventing.yaml
- in-memory-channel.yaml
namespace:
- riff-cnb-buildtemplate-0.1.0.yaml
```
Notice that the kubernetes configuration files are referenced using relative file paths rather than URLs. These files are in the same directory as the manifest.

With this in place, issue the following from a Windows command prompt:
```
riff system install -m file:///C:\path\to\manifest\manifest.yaml
```

The failure is as follows:
```
Istio is already installed, do you want to install the Knative components for riff? [y/N]: y
Waiting for the Istio components to start . all components are 'Running'

Installing Knative components
Error applying resources, trying again

Error: open file:\C:\path\to\manifest\release.yaml: The filename, directory name, or volume label syntax is incorrect.
```

**Comment by glyn** [comment]
Re-opening until @trisberg has had a chance to break the code again. :-)

**Comment by trisberg** [comment]
Tried with `riff system install -m file:///C:\path\to\manifest\manifest.yaml` and that still doesn't work which could be expected.

This works fine: `riff system install -m file:///C:/path/to/manifest/manifest.yaml`, so I think we can close this issue.

**Comment by trisberg** [comment]
This seems to be failing again, can't find a file URL combination that works with the latest riff CLI

**Comment by glyn** [comment]
I've unassigned this so others can take a crack at it. My Windows VM has probably rotted by now.

Also, I'm not comfortable with the absence of automatically-triggered and mandatory Windows CI as we can easily break Windows support without knowing (e.g. if those running Windows tests go on vacation).

**Comment by trisberg** [comment]
I agree that we do need to set up automated CI build somewhere. Question is where should we set this up? We could try using build.spring.io which had Windows support.
