### ISSUE TITLE
Function create doesn't work with DockerHub repository and git-repo

### ISSUE THREAD

**Issue by developerpat** [projectriff/riff#1039]
Hello everybody,

maybe someone can help me. I try to deploy the square function at minikube with following command:
`riff function create square --git-repo https://github.com/projectriff-samples/node-square --image developerpat/square:v2 --verbose`

Then i get following response:
`Waiting for LatestCreatedRevisionName
Waiting on function creation: function creation incomplete: service status unknown: RevisionMissing: Configuration "square" is waiting for a Revision to become ready.
LatestCreatedRevisionName available: square-00001
Waiting on function creation timed out

Error: function creation incomplete: service status unknown: RevisionMissing: Configuration "square" is waiting for a Revision to become ready.`

After the command the service is in an unknown status. I don't know why the creation ist timed out.

Thanks for your help.

**Comment by trisberg** [comment]
This could happen if you didn't initialize the namespace. Did you run `riff namespace init default --dockerhub developerpat`?

Try the following (enter your dockerhub password at the prompt):

```
riff service delete square
riff namespace init default --dockerhub developerpat
riff function create square --git-repo https://github.com/projectriff-samples/node-square --image developerpat/square:v2 --verbose
```

**Comment by developerpat** [comment]
Hi @trisberg,

yes i have run the initialization of the default namespace. I reset my minikube now and do all the stuff from the start and now it is working. But when i do an invoke an the square function i get an connection refused.  In the logs of the knative-ingresscontroller is nothing to see. 

Pods:
default            square-00001-55hjs                            0/1     Completed
docker             compose-74649b4db6-w2wvv                      1/1     Running
docker             compose-api-5cb456b5b5-2mf2n                  1/1     Running
istio-system       istio-citadel-84fb7985bf-27sg2                1/1     Running
istio-system       istio-cleanup-secrets-v2bk2                   0/1     Completed
istio-system       istio-egressgateway-bd9fb967d-95g4z           1/1     Running
istio-system       istio-galley-655c4f9ccd-m92rg                 1/1     Running
istio-system       istio-ingressgateway-688865c5f7-8x82m         1/1     Running
istio-system       istio-pilot-6cd69dc444-cqmnn                  2/2     Running
istio-system       istio-policy-6b9f4697d-67vvr                  2/2     Running
istio-system       istio-sidecar-injector-8975849b4-bhclz        1/1     Running
istio-system       istio-statsd-prom-bridge-7f44bb5ddb-9m4z5     1/1     Running
istio-system       istio-telemetry-6b5579595f-r4xbh              2/2     Running
istio-system       knative-ingressgateway-76b7677587-796hw       1/1     Running
knative-build      build-controller-747b8fd966-jqw6j             1/1     Running
knative-build      build-webhook-6dc78d8f6d-7qwjj                1/1     Running
knative-eventing   eventing-controller-f5b4d57bb-m9m2s           1/1     Running
knative-eventing   stub-clusterbus-dispatcher-6cf9dbfc59-lv9fh   2/2     Running
knative-eventing   webhook-76f48b5494-ck8xz                      1/1     Running
knative-serving    activator-df78cb6f9-kbzgk                     2/2     Running

knative-ingressgateway:
<table>
<tr>
<td>NAME</td>
<td>TYPE</td>
<td>CLUSTER-IP</td>
<td>EXTERNAL-IP</td>
<td>PORT(S)</td>
<td>AGE</td>
</tr>
<tr>
<td>knative-ingressgateway</td>
<td>LoadBalancer</td>
<td>10.105.40.112</td>
<td><pending></td>
<td>80:32380/TCP,443:32390/TCP,31400:32400/TCP,15011:32246/TCP,8060:30065/TCP,853:32186/TCP,15030:31766/TCP,15031:31615/TCP</td>
<td>4h</td>
</tr>
</table>

command to invoke:
`riff service invoke square --text -- -w '\n' -d 8`
`curl http://localhost:32380/ -H 'Host: square.default.example.com' -H 'Content-Type: text/plain' -w '\n' -d 8`
`curl: (7) Failed to connect to localhost port 32380: Connection refused`

Maybe you have an idea?

**Comment by developerpat** [comment]
Sorry was my fault. I installed the second time without --node-port. Now it is working. I close the Issue.
