### ISSUE TITLE
function update with --local-path fails detection

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#1055]
```
$ riff function update pipeline --local-path .
2019/01/09 16:41:08 Pulling builder image 'projectriff/builder' (use --no-pull flag to skip this step)
2019/01/09 16:41:08 Using user provided run image 'packs/run'
*** DETECTING:
2019/01/09 21:41:13 Group: Cloud Foundry OpenJDK Buildpack: pass | Node.js Buildpack: pass | Cloud Foundry Build System Buildpack: pass | NPM Buildpack: fail | riff Buildpack: fail
2019/01/09 21:41:13 Error: failed to detect

Error: run detect container: failed with status code: 6
```

**Comment by trisberg** [comment]
It's on my Mac. Seems to be a cross the board regression.

Just try a local square nodejs function.

```
$ riff function update square --local-path .
2019/01/10 09:51:11 Pulling builder image 'projectriff/builder' (use --no-pull flag to skip this step)
2019/01/10 09:51:12 Using user provided run image 'packs/run'
*** DETECTING:
2019/01/10 14:51:17 Group: Cloud Foundry OpenJDK Buildpack: pass | Node.js Buildpack: pass | Cloud Foundry Build System Buildpack: fail | NPM Buildpack: fail | riff Buildpack: fail
2019/01/10 14:51:17 Error: failed to detect

Error: run detect container: failed with status code: 6
```

**Comment by trisberg** [comment]
Looks like we now delete the `riff.toml` file after the initial build. We could store that information in an annotation in the k-service resource and  then recreate `riff.toml` for local updates.

**Comment by ericbottard** [comment]
Yes, just got to that same conclusion. 70553fcd72bf62a61fdd588cacd811bb4ef76b8d is the culprit commit. 
I'm being confused now though: how do we handle rebuilding on cluster ? Where are the artifact, handler etc parameters saved in that case?

**Comment by trisberg** [comment]
In that case we bump the nonce annotation on the build resource, so the args are already in there

**Comment by ericbottard** [comment]
It's also that the values from the CLI parameters are actually captured in the Build parameters, so the step that writes the riff.toml has the info.

We definitely need to save those values in the service definition for the local case. I'll issue a PR in that direction
