### ISSUE TITLE
Scale from 0 for Java apps get 502

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#1056]
Scaling a Java app from 0 get's a 502 response on the first request that initiates the scale up.

I wonder if there is a way to specify a readiness probe to get a better experience. There is a corresponding issue with Knative and a PR here: https://github.com/knative/serving/pull/2706

This becomes a problem when you have multiple Java apps in an event chain via subscriptions. Each cold start app breaks the chain with a 500 error message.

**Comment by sbawaska** [comment]
related: https://github.com/projectriff/riff/issues/1004

**Comment by trisberg** [comment]
haven't seen this since we upgraded Knative to 0.3.0. Closing for now.
