### ISSUE TITLE
Correct the advice on how to skip pulling builder image

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#1072]
```
riff function create square --image gcr.io/$GCP_PROJECT_ID/square --verbose --local-path /path/to/node-square
```
logs this:
```
2019/01/24 11:23:38 Pulling builder image 'projectriff/builder' (use --no-pull flag to skip this step)
```
but `--no-pull` is not a valid flag for `riff function create`.

**Comment by ericbottard** [comment]
This is `pack` printing this message. I've reported the issue already, and maybe it is fixed. We'll see when we upgrade

**Comment by trisberg** [comment]
There is an issue here https://github.com/buildpack/pack/issues/84

**Comment by glyn** [comment]
Thanks both of you. Let's leave this bug open for tracking.

**Comment by scothis** [comment]
Done with the upgrade to pack 0.2.0
