### ISSUE TITLE
Provide feedback when function create is pulling (large builder) images

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#1073]
```
riff function create square --image gcr.io/$GCP_PROJECT_ID/square --verbose --local-path /path/to/node-square
```
prints the log:
```
2019/01/24 11:23:38 Pulling builder image 'projectriff/builder' (use --no-pull flag to skip this step)
```
and, in the case when this image and all its layers need to be downloaded, there is no feedback (in spite of `--verbose` having been specified) and the command might be hanging for all the user knows.

It would be great to provide _some_ feedback during the image pulling process. Bonus points for providing similar feedback to `docker pull`.

**Comment by scothis** [comment]
done with the upgrade to pack 0.2.0. The status of each layer is shown along with a percent and size for layers in flight.

<img width="834" alt="Screen Shot 2019-05-30 at 4 38 09 PM" src="https://user-images.githubusercontent.com/302992/58663052-93d22080-82f9-11e9-803c-6b9d33b5e0ce.png">
