### ISSUE TITLE
Provide inverse operation to `riff namespace init`

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#1074]
This is desirable from a UX perspective. See, for example, rule 6 [here](https://faculty.washington.edu/jtenenbg/courses/360/f04/sessions/schneidermanGoldenRules.html).

**Comment by glyn** [comment]
See https://github.com/projectriff/riff/issues/1025 for a description of the resources that need cleaning up.

**Comment by fbiville** [comment]
After chatting with @glyn, proposal is to have:
```
riff namespace cleanup [--remove-ns]
```
The associated service account, its secret the related PVC will be removed.
If `--remove-ns` is provided, the namespace itself will be deleted.

For now, the implementation would rely on the hardcoded names of service account/secret/PVC to remove them.

**Comment by ericbottard** [comment]
Cool.
Note that `--remove-ns` doesn't bring any value over `kubectl delete ns`, has deleting it will destroy the riff things

**Comment by ericbottard** [comment]
Or [maybe not](https://github.com/projectriff/riff/issues/1025)

**Comment by fbiville** [comment]
That's the whole point of this command: cleaning up the remaining service account, secret and PVC. The logic could be reused for #1025.

The `--remove-ns` option is just to indicate whether the namespace itself should be deleted as well.
`riff namespace init` creates the namespaces only it it wasn't there in the first place. 
We cannot assume that riff created the namespace hence we should not delete it unless prompted to.

**Comment by ericbottard** [comment]
Indeed, my bad. My point was more because I thought the namespace "owned" the account, secret, etc and hence it would have teared them down with itself.
