### ISSUE TITLE
Make annotation names consistent

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#1076]
One of the current function annotation names has a slash and the others avoid slashes (see [function.go](https://github.com/projectriff/riff/blob/a73c6d085a5d29e6c013b87623d5055163d091eb/pkg/core/function.go#L47-L50)), although slashes seem to be acceptable (https://github.com/projectriff/riff/pull/1067 worked fine with them). We should adopt a consistent convention across all our annotations.

According to [these k8s docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/):

> Valid annotation keys have two segments: an optional prefix and name, separated by a slash (/).

Let's use a slash as the result seems more readable.

**Comment by glyn** [comment]
@scothis Apparently Knative has never had a problem with slashes in annotations, but Istio 1.0.3 did.

**Comment by scothis** [comment]
Fixed indirectly in #1132
