### ISSUE TITLE
Multiple functions in a single repo

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#1089]
It's sometimes advantageous to store more than one function in the same git repository. Currently, riff doesn't support this case, however, Knative Build does with the SubPath field on the SourceSpec.

We can add a `--sub-path` flag to `riff function create`. When doing an in-cluster build we should set `build.Spec.SubPath` with the value. When doing a local build the flag could either be ignored, forbidden or appended onto the value of `--local-path` depending on what produces the clearest command help text and test cases.

**Comment by trisberg** [comment]
This could be useful for Boot functions as well since SCFn exposes each function bean as it's own path using the bean name

**Comment by scothis** [comment]
@trisberg I don't think this will help. SubPath is a path within a git repo to build, not an http subpath. Or am I confused?

**Comment by trisberg** [comment]
Ahh, never mind then, I'm the confused one.
