### ISSUE TITLE
Invoker extensibility

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#1093]
In the past riff had an Invoker CRD that allowed users to create riff functions with a new language. With the transition to buildpacks, we scaled back the number of languages we support and lost the extensibility to add new languages.

There are three key components to adding a new language
- a [CNB (Cloud Native Buildpack)](https://buildpacks.io) for the language runtime and build tooling
- an [invoker](https://github.com/projectriff?utf8=✓&q=function-invoker&type=&language=) that exposes functions written in that language
- wiring the CNB and invoker into [riff-buildpack](https://github.com/projectriff/riff-buildpack) and [riff-buildpack-group](https://github.com/projectriff/riff-buildpack-group).

With an appropriate buildpack and invoker, adding a new language/runtime support to riff should be as easy as it was previously. Before exposing a model to users, we should experiment with making all current languages and invokers pluggable. Eliminating, or isolating, imperative logic and coupling between invokers.

**Comment by scothis** [comment]
Our current thinking is that we will create a buildpack per language that is responsible for contributing the invoker and managing any build time configuration or steps required. The invoker manages the runtime lifecycle of the function, the buildpack managed the compile time aspects of the function.

This means that invoker authors will also be responsible for authoring a buildpack in order for the invoker to be consumed. In riff 0.0.x this role was managed by a Dockerfile provided by the invoker that knew how to compile the function atop a base image.

In theory, a buildpack can be implemented in any language. In practice, using a library is much more convenient. We are looking at creating a function buildpack library in the model of libbuildpack and  libcfbuildpack.

**Comment by kingdonb** [comment]
I'll sign me up for adding the Ruby invoker/buildpack support

Is there any language maintainer documentation planned? That seems like a realistic idea, given our last invoker was ~100-200 LOC only

**Comment by scothis** [comment]
Thanks @kingdonb. I really appreciate your sticking with us through these changes.

We'll absolutely need to create a guide and reference documentation for creating new invokers and registering them within the system. I'll let you know when we're ready to test the model.

**Comment by scothis** [comment]
I spiked splitting out each language from [riff-buildpack](https://github.com/projectriff/riff-buildpack/pull/51) into [independent function buildpacks](https://github.com/projectriff/?utf8=✓&q=function-buildpack&type=&language=). The individual buildpacks are reassembled in [riff-buildpack-group](https://github.com/projectriff/riff-buildpack-group/pull/32).

riff-buildpack is acting as:
- a "finalizer" buildpack that ensures exactly one function buildpack is detected. Ambiguous detection requires the user to specify which function buildpack to consume.
- a library for other function buildpacks to consume to normalize the detection behavior. We may split this out, minimally it needs additional iteration

With this change, it is possible to implement a custom invokers and a function buildpack that are pulled into a builder image that contains that buildpack/invoker.

Next steps:
- ensure riff-buildpack is exposing a library abstraction we are comfortable with
- create a mechanism to create a builder image from a declarative set of function buildpacks (builder inception). Perhaps bringing back the Invoker CRD
- have riff consume the custom builder image without manually updating the ClusterBuildTemplate or recompiling the riff cli
- docs, more tests, all the good stuff

@ericbottard @kingdonb @nebhale WDYT?

**Comment by kingdonb** [comment]
Interesting! I will take a look at the links you posted this weekend, and give some feedback.

**Comment by scothis** [comment]
Function buildpack decomposition has landed with riff-buildpack acting as both a finalizer and a library for other function buildpacks. Next up is to make the riff-buildpack-group more configurable.

**Comment by scothis** [comment]
The requirements for invokers are being defined at https://github.com/projectriff/invoker-specification
