### ISSUE TITLE
Document how to authenticate local builds to container registries

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#1094]
For each supported environment on projectriff.io, we document how to configure in-cluster builds to the container registry, but never show how to authenticate local builds to the registry.

Local (Minikube, Docker for Desktop): none (it's open to all)
DockerHub: `docker login`
GCR: `gcloud auth configure-docker`

We should also document that local builds require a Docker daemon.

Follow up to #1054

**Comment by trisberg** [comment]
where would we document this? Should we add something in addition to the getting started pages?

**Comment by scothis** [comment]
> where would we document this? Should we add something in addition to the getting started pages?

On each getting started page is ideal. Perhaps just below the `riff namespace init` command since users will readily have access to their credentials (if any).
