### ISSUE TITLE
Investigate using kustomize with system install

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#1096]
We could use kustomize to modify any release yaml with NodePort during the system install

**Comment by trisberg** [comment]
We could also use this to add image pull secrets during the install to support pulling private images both for knative/builder images and for images built for functions

**Comment by jldec** [comment]
see also #1028 - i would be in favor of reconsidering the decision not to help automate image pull secrets.

**Comment by scothis** [comment]
We implemented kustomize for riff 0.3
