### ISSUE TITLE
riff system install errors with latest as of Feb12

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#1099]
Seeing those errors when trying to install "latest" today (error may be anterior). This is with riff built from today's master. Installing "stable" works fine:

```
...
Applying resources defined in: https://storage.googleapis.com/knative-releases/eventing/latest/in-memory-channel.yaml
Applying resources defined in: https://storage.googleapis.com/projectriff/riff-buildtemplate/riff-cnb-clusterbuildtemplate.yaml
error: error validating "STDIN": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false

Applying resources defined in: https://storage.googleapis.com/projectriff/riff-buildtemplate/riff-cnb-clusterbuildtemplate.yaml
error: error validating "STDIN": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by trisberg** [comment]
are you trying to solve tomorrow's problems?

I'm getting a 403 on that `https://storage.googleapis.com/projectriff/riff-buildtemplate/riff-cnb-clusterbuildtemplate.yaml` file

```
$ wget https://storage.googleapis.com/projectriff/riff-buildtemplate/riff-cnb-clusterbuildtemplate.yaml
--2019-02-11 10:06:28--  https://storage.googleapis.com/projectriff/riff-buildtemplate/riff-cnb-clusterbuildtemplate.yaml
Resolving storage.googleapis.com... 172.217.9.240
Connecting to storage.googleapis.com|172.217.9.240|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-02-11 10:06:29 ERROR 403: Forbidden.
```

**Comment by trisberg** [comment]
shouldn't the file be `https://storage.googleapis.com/projectriff/riff-buildtemplate/riff-cnb-clusterbuildtemplate-0.2.0-snapshot.yaml`?

**Comment by scothis** [comment]
Since `https://storage.googleapis.com/projectriff/riff-buildtemplate/riff-cnb-clusterbuildtemplate.yaml` is a new resource we can go back to publishing latests without worrying about breaking existing users. We just never want to use this as the default in a release.

**Comment by ericbottard** [comment]
"Creating today's issues by trying to solve tomorrow's problems", established 2019.
Note that I assumed I needed "latest" to play with serving@master

**Comment by scothis** [comment]
> Note that I assumed I needed "latest" to play with serving@master

"latest" is the most recent release. To track master you want the "nightly" manifest, or a custom build from source via `ko`.

Currently "stable" and "latest" should be effectively the same, but they will drift over time before "latest" moves before "stable" catches back up.
