### ISSUE TITLE
Provide default `--image` for `riff function create`

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#1101]
When creating a function, the location of the source code is often top of mind, but the image is secondary. It adds friction to manually specify an image repository. Particularly when much of the information is redundant with the credentials used to initialize the namespace. I constantly struggle to remember simple things like which gcloud project my cluster is running in.

I'd like to see the `--image` flag be optional with riff providing a reasonable default based on a base value saved in the namespace and the name of the function. The image repository base can be saved when running `riff namespace init`. Since there is strong correlation between the credentials being set and the image repository base, in many cases we can automatically set the default value, in other cases, we can require the user specify the base value.

- `--gcr` => `gcr.io/{<creds> | jq -r .project_id}`
- `--dockerhub` => `{username}`
- others => require `--image-prefix` to be set

In all cases, the user must be able to provide an explicit image to `riff function create`. It may be desirable to offer a shortcut to use the image repository prefix with a different repository, ie `--image _base/some-name-that-is-not-the-same-as-my-function`.

The exact mechanism to persist the prefix in the namespace is TBD, however, a ConfigMap named `riff-build` is a logical choice.

Current command:

```
riff function create square \
  --git-repo https://github.com/projectriff-samples/node-square \
  --image gcr.io/project-id/square
```

Becomes:

```
riff function create square \
  --git-repo https://github.com/projectriff-samples/node-square
```

The change is event more dramatic for local builds. Before:

```
riff function create square --local-path . --image gcr.io/project-id/square
```

After:

```
riff function create square --local-path .
```

**Comment by trisberg** [comment]
Should the image be named after the repo rather than the function?

**Comment by scothis** [comment]
> Should the image be named after the repo (name of current dir for --local-path) rather than the function?

There may not be a git repo, there is always a function name.

> Why is the upper function using the node-square repo?

Updated the example
