### ISSUE TITLE
waiting for a Revision to become ready for when using --git-repo flag

### ISSUE THREAD

**Issue by elbandito** [projectriff/riff#1111]
Hi Riff,

I'm running on:
- Mac
- minikube version: v0.34.1
- hyperkit driver 
- riff cli: 0.2.0 (1ae190ff3c7edf4b375ee935f746ebfd1d8eaf5c) 

Here's the output every time I try to run `riff function create` with `--git-repo` flag:
```
$ riff function create square --git-repo https://github.com/elbandito/square.git --image aperolabs/square:v6 --verbose
Waiting for LatestCreatedRevisionName
Waiting on function creation: checkService failed to obtain service status for observedGeneration 1
LatestCreatedRevisionName available: square-00001
Waiting on function creation: function creation incomplete: service status unknown: RevisionMissing: Configuration "square" is waiting for a Revision to become ready.
```

However, if I clone this repo, I'm successfully able to create the function with the following command:
```
riff function create square --invoker node -l square/ --artifact square.js --image aperolabs/square:v6
```

Any insight into why it's failing for the `--git-repo` flag?  I must be overlooking something...

Thanks for any help!
Travis

**Comment by trisberg** [comment]
Any chance you forgot to initiate a namespace using `riff namespace init default --dockerhub aperolabs`?

**Comment by elbandito** [comment]
Thanks for your response @trisberg.  I didn't forget to run the init command.  What puzzles me is why it's working if I'm going off of local disk, but not for my github repo?

**Comment by trisberg** [comment]
It's a completely different build path, the `--git-repo` version runs the build in the cluster while `--local-path` runs the build on your local system. 

Do you have any build resources - `kubectl get build`, if you do could you post the output from `kubectl describe build <build-name>`.

**Comment by elbandito** [comment]
@trisberg 
```
$ kubectl get build
No resources found.
```

**Comment by elbandito** [comment]
@trisberg I abandoned `minikube` and decided to try `docker`, and it worked just fine using the `--git-repo` flag.
