### ISSUE TITLE
riff function create failed invalid run image packs/run: missing required label io.buildpacks.stack.id

### ISSUE THREAD

**Issue by eesan** [projectriff/riff#1118]
I am using riff 
Version
  riff cli: 0.2.0 (1ae190ff3c7edf4b375ee935f746ebfd1d8eaf5c)
Minikube version 0.34
Ubuntu Bionic
I followed the guide Getting started working on minikube - https://projectriff.io/docs/getting-started/minikube/
and riff create function did work first time. What I did is I stop the minikube and restarted it successfully and tried creating riff function again using the same command as before:

Minikube start command:
minikube start --vm-driver=kvm2 --bootstrapper=kubeadm --kubernetes-version=v1.13.2 --memory=4096 --cpus=4

riff function create uppercase --local-path . --artifact target/function-demo-0.0.1-SNAPSHOT.jar --handler "uppercase&main=nz.functiondemo.FunctionDemoApplication" --image $DOCKER_ID/uppercase

I get the following message:
2019/02/26 16:12:49 Pulling builder image 'projectriff/builder' (use --no-pull flag to skip this step)
2019/02/26 16:12:55 Using user provided run image 'packs/run'

Error: invalid run image "packs/run": missing required label "io.buildpacks.stack.id"

I tried riff function create ..... --dry-run and got the following

Skipping local build
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  annotations:
    riff.projectriff.io-buildpack-buildImage: projectriff/builder
    riff.projectriff.io-buildpack-runImage: packs/run
  creationTimestamp: null
  name: uppercase
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            riff.projectriff.io/nonce: "1"
          creationTimestamp: null
          labels:
            riff.projectriff.io/function: uppercase
        spec:
          container:
            image: $DOCKER_ID/uppercase
            name: ""
            resources: {}
status: {}
---

Added below the required istio and knative running components

Every 1.0s: kubectl get pod --all-namespaces                                                                                                            eesan-HP-EliteBook-1050-G1: Wed Feb 27 10:51:13 2019

NAMESPACE          NAME                                          READY   STATUS      RESTARTS   AGE
istio-system       istio-citadel-7d64db8bcf-q7km5                1/1     Running     0          46h
istio-system       istio-cleanup-secrets-9s4hf                   0/1     Completed   0          46h
istio-system       istio-egressgateway-6ddf4c8bd6-swqt6          1/1     Running     0          46h
istio-system       istio-galley-7dd996474-qlvg8                  1/1     Running     0          46h
istio-system       istio-ingressgateway-84b89d647f-thncf         1/1     Running     0          46h
istio-system       istio-pilot-86bb4fcbbd-qghnq                  2/2     Running     0          46h
istio-system       istio-policy-5c4d9ff96b-tkskk                 2/2     Running     0          46h
istio-system       istio-sidecar-injector-6977b5cf5b-rxqtx       1/1     Running     0          46h
istio-system       istio-statsd-prom-bridge-b44b96d7b-t8fp2      1/1     Running     0          46h
istio-system       istio-telemetry-7676df547f-hjzxb              2/2     Running     0          46h
istio-system       knative-ingressgateway-75644679c7-48l86       1/1     Running     0          46h
knative-build      build-controller-5bdf899f56-jbfvt             1/1     Running     0          46h
knative-build      build-webhook-5cc5698f5d-l8k8b                1/1     Running     0          46h
knative-eventing   eventing-controller-5557745944-zh8t5          1/1     Running     0          46h
knative-eventing   stub-clusterbus-dispatcher-55779cb455-7j4jq   2/2     Running     0          46h
knative-eventing   webhook-6f486f9cb-hswmf                       1/1     Running     0          46h
knative-serving    activator-c47879875-2kzvl                     2/2     Running     0          46h
knative-serving    activator-c47879875-9kjq6                     2/2     Running     0          46h
knative-serving    activator-c47879875-lh7wh                     2/2     Running     0          46h
knative-serving    autoscaler-5fc89645cd-hrgj8                   2/2     Running     0          46h
knative-serving    controller-64cfb4859f-vngnk                   1/1     Running     0          46h
knative-serving    webhook-74dff4f764-gsv5p                      1/1     Running     0          46h
kube-system        coredns-86c58d9df4-skgdj                      1/1     Running     0          46h
kube-system        coredns-86c58d9df4-t2wgv                      1/1     Running     0          46h
kube-system        etcd-minikube                                 1/1     Running     0          46h
kube-system        kube-addon-manager-minikube                   1/1     Running     0          46h
kube-system        kube-apiserver-minikube                       1/1     Running     0          46h
kube-system        kube-controller-manager-minikube              1/1     Running     0          46h
kube-system        kube-proxy-lqw6p                              1/1     Running     0          46h
kube-system        kube-scheduler-minikube                       1/1     Running     0          46h
kube-system        kubernetes-dashboard-ccc79bfc9-xqf9j          1/1     Running     0          20h
kube-system        storage-provisioner                           1/1     Running     0          46h

**Comment by eesan** [comment]
Tried using --git-repo the riff function create works. Failing only when using --local-path.

**Comment by scothis** [comment]
Hi @eesan, thanks for the detailed report. riff no longer supports creating a function from a pre-compiled JAR. Instead, it expects to operate on the source with either a Maven or Gradle based build. You can find a sample function here https://github.com/projectriff-samples/java-boot-uppercase.

Please add a comment if this solves your issue and reopen if you have further trouble.

**Comment by eesan** [comment]
Hi @scothis , thanks for the reply. Does it mean riff no longer support support --local-path ? 

riff function create uppercase --local-path . --artifact target/function-demo-0.0.1-SNAPSHOT.jar --handler "uppercase&main=nz.functiondemo.FunctionDemoApplication" --image $DOCKER_ID/uppercase

The above riff create function code did worked first time, I stopped the minikube and restarted them and tried the same riff create function - it fails.

I use exactly the same sample code for uppercase with following riff create command - it fails

~/workspace/demo-function$ riff function create uppercase --local-path . --handler "uppercase&main=nz.functiondemo.FunctionDemoApplication" --image $DOCKER_ID/uppercase

2019/02/28 10:28:17 Pulling builder image 'projectriff/builder' (use --no-pull flag to skip this step)
2019/02/28 10:28:21 Using user provided run image 'packs/run'

Error: invalid run image "packs/run": missing required label "io.buildpacks.stack.id"

**Comment by scothis** [comment]
`--local-path` is supported, the path should be to the directory that contains either a pom.xml or build.gradle file. You shouldn't need to specify the `--artifact`.

For example, if you clone this repo, https://github.com/projectriff-samples/java-boot-uppercase, and move into that directory, then you should then be able to run `riff function create uppercase --local-path . --image $DOCKER_ID/uppercase`.

**Comment by eesan** [comment]
Hi @scothis - I did clone that project and tried - still the same issue
~/workspace/java-boot-uppercase$ riff function create uppercase --local-path . --image eesanaws/uppercase

2019/02/28 12:17:42 Pulling builder image 'projectriff/builder' (use --no-pull flag to skip this step)
2019/02/28 12:17:46 Using user provided run image 'packs/run'

Error: invalid run image "packs/run": missing required label "io.buildpacks.stack.id"


Also the same result with --dry-run as well
~/workspace/java-boot-uppercase$ riff function create uppercase --local-path . --image eesanaws/uppercase --dry-run

Skipping local build
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  annotations:
    riff.projectriff.io-buildpack-buildImage: projectriff/builder
    riff.projectriff.io-buildpack-runImage: packs/run
  creationTimestamp: null
  name: uppercase
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            riff.projectriff.io/nonce: "1"
          creationTimestamp: null
          labels:
            riff.projectriff.io/function: uppercase
        spec:
          container:
            image: eesanaws/uppercase
            name: ""
            resources: {}
status: {}
---

**Comment by scothis** [comment]
Hmmm, can you post the output of `docker inspect packs/run` and `docker inspect
projectriff/builder`?

**Comment by eesan** [comment]
$docker inspect packs/run
Error: No such object: packs/run

$docker inspect projectriff/builder
[
    {
        "Id": "sha256:7c6f437b6708242bdb8af2095fa00295238a1d01531e91fb9b5cfd41f43eada1",
        "RepoTags": [
            "projectriff/builder:latest"
        ],
        "RepoDigests": [
            "projectriff/builder@sha256:896511f8fdb2f4f477ffc72fc83e3e425712f53a0c60ba844f97ad10612c8487"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-11-16T22:06:29.102827427Z",
        "Container": "b12561f236f6eb0eae1a5eb8f20181eb2fc2949035083f5034051988d4a91178",
        "ContainerConfig": {
            "Hostname": "b12561f236f6",
            "Domainname": "",
            "User": "pack",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PACK_USER_ID=1000",
                "PACK_GROUP_ID=1000",
                "PACK_USER_GID=1000",
                "PACK_STACK_ID=io.buildpacks.stacks.bionic"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "ENV PACK_STACK_ID=io.buildpacks.stacks.bionic"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:de6e3a72c47177b649ed75b95122efebdde2adc34826c78846b7f108bf00e56d",
            "Volumes": null,
            "WorkingDir": "/workspace",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {
                "io.buildpacks.stack.id": "io.buildpacks.stacks.bionic"
            }
        },
        "DockerVersion": "17.09.0-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "pack",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PACK_USER_ID=1000",
                "PACK_GROUP_ID=1000",
                "PACK_USER_GID=1000",
                "PACK_STACK_ID=io.buildpacks.stacks.bionic"
            ],
            "Cmd": [
                "/bin/bash"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:de6e3a72c47177b649ed75b95122efebdde2adc34826c78846b7f108bf00e56d",
            "Volumes": null,
            "WorkingDir": "/workspace",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {
                "io.buildpacks.stack.id": "io.buildpacks.stacks.bionic"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 689742390,
        "VirtualSize": 689742390,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/6ece069948e32f5d5d9ba6d4e1244192913881d518ee394d0b1f0ee6045899e9/diff:/var/lib/docker/overlay2/22fd447339c55854b4578514180d25c51b418e31301ae5e46381a0a3b7894c36/diff:/var/lib/docker/overlay2/728f47b613150f166f1624a54ba680db845915d9b4c488b3eae14a725c4b409d/diff:/var/lib/docker/overlay2/20ec8f254c25b103faf96f7410f03b82671681d23c8dc0c23de47d166d63f224/diff:/var/lib/docker/overlay2/71773a620e94aef72a2befa7ac7818b714d63f6c1b14954951a57ddb18a03601/diff:/var/lib/docker/overlay2/fa5b7476128f1b821885e0ac737b6ec9e7721a01f4f3a0eeeb2d615f8cb70ef4/diff:/var/lib/docker/overlay2/614c79fafbacc32f8b3dc6762101b473526bbdfd9fb79118a46e4d422b1ce6b6/diff:/var/lib/docker/overlay2/ba08c42b19c197358393bea7ef71b002a34d572bd77af69cd24f2021cc9c8c28/diff:/var/lib/docker/overlay2/7afd367c3f26e131ad43d216a3e25ee8a78972f574f81483b902eafe1450072d/diff:/var/lib/docker/overlay2/a30abadf243df580b47ab633a56916071b1dd03165a69faa8b5116c68f585ebd/diff:/var/lib/docker/overlay2/3e3004faf8293a83cee8a9e11b1a3d1abf397166da46938fce9f7f533d1f7921/diff:/var/lib/docker/overlay2/1a5830e2ca6f845da6db67898b00b6a756bad402bc5140948d400c7aadc74ab9/diff:/var/lib/docker/overlay2/9f7c5aa62820abc82b12c8f1579cb1b2adbd32cc7472fd98f4cae42f0c5b3a88/diff:/var/lib/docker/overlay2/58eec3bdc2754c003949f08d80d6fa8aaf4f9ef3a8018867f6d48c69c3feb887/diff:/var/lib/docker/overlay2/1ce52da8b8f8936be713ec3ef6e5ffa9f8f95048535957c4aebaca80a25c659b/diff:/var/lib/docker/overlay2/5cb22e76ecec445fd7106045ddbef858d510ca569d7f5eb46a17ee4d0e58e7d2/diff:/var/lib/docker/overlay2/153efab29cef6d06eecae1b98904af0fd729efc8893a71a76840382196f76c3d/diff:/var/lib/docker/overlay2/3e44a86af4ad5b492a132bf75c123ce6396a304913f88c2edee703dbdd85081c/diff",
                "MergedDir": "/var/lib/docker/overlay2/4918b1a76da7381ac729f5f7aa6cf48c6f25f1641179bdf73a5115c7a06fc1c5/merged",
                "UpperDir": "/var/lib/docker/overlay2/4918b1a76da7381ac729f5f7aa6cf48c6f25f1641179bdf73a5115c7a06fc1c5/diff",
                "WorkDir": "/var/lib/docker/overlay2/4918b1a76da7381ac729f5f7aa6cf48c6f25f1641179bdf73a5115c7a06fc1c5/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:102645f1cf722254bbfb7135b524db45fbbac400e79e4d54266c000a5f5bc400",
                "sha256:ae1f631f14b7667ca37dca207c631d64947c60d923995cf0d73ceb1b08c406bb",
                "sha256:2146d867acf390370d4d0c7b51951551e0e91fb600b69dbc8922d531b05b12bc",
                "sha256:76c033092e100f56899d7402823c5cb6ce345442b3382d7b240350ef4252187e",
                "sha256:c10efabf98772b6535b0cde4a43eb6412a6a301240c41f96cb76bdb427f62b3f",
                "sha256:f3a4183a422829f45d9e0cee38de89dc315014bd55ec9f718cfdc4c515028fa1",
                "sha256:063ad9c0de0941345fa7483c837da8e60447352cdf4d63483e046012c8ac2d1c",
                "sha256:4aa81ade9932ac33df5b431f0bb97e7dcd72eaff951fb16d2513870c4de04c40",
                "sha256:abcb9772268e5144728a765068bafe3cacb4ff892472b936d88317c57d4c73c6",
                "sha256:c83b22d74d49e58c7432e4752fc22c1142572cbc5a8c8187ca5036ecf19acbf3",
                "sha256:899c7b5a34ea03eae4b0ffb8054fdfcdb5c6a2a2e92720f838c83bb3d9b722dd",
                "sha256:cfff41ebf789fc0c7b4fda23345c9bfe1f982e9f8e8c3726104072a52e7cac67",
                "sha256:6ff4dae1d3d7335ca275ec0abebd6bc834b0771b425c3c587b316f5d0fb8dada",
                "sha256:b31b4efcd623fba764970a8d1f98141f17f28ec73c4ea85acc3faa65f5c06f3b",
                "sha256:4307f858e944daaf56ecfd01f2929571df9fb48ab0caeedac0533f1801dfcdf4",
                "sha256:135235790e8278c9996f58392eb9d289f3027015935f33ca578890703edae765",
                "sha256:8bb573e1e8695a87bf277f3b53a5b2c24046277081768f2a2e063fd61707a90f",
                "sha256:1af0caa86d57c2ef4c2722f1474f0937233b3239a19c9029bd565cc9be4f17c0",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Comment by eesan** [comment]
Hi @scothis 
I pulled the packs/run image - $ docker pull packs/run
$docker inspect packs/run
[
    {
        "Id": "sha256:262a6e446f6ce7afa5d54d763ce3ed34410c0ba7120d2679f3e5f4d952bb946d",
        "RepoTags": [
            "packs/run:latest"
        ],
        "RepoDigests": [
            "packs/run@sha256:eba96876f4ddd9d6f4bfe0a0d7baf51bd7c77882b9e829ca7b49c43896d1b183"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-11-16T22:06:29.878694694Z",
        "Container": "1f08051a72483624aff9702cf559e7491a40d3bb7bec7701b07db2372bc53254",
        "ContainerConfig": {
            "Hostname": "1f08051a7248",
            "Domainname": "",
            "User": "pack",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PACK_USER_ID=1000",
                "PACK_GROUP_ID=1000",
                "PACK_USER_GID=1000"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "ENTRYPOINT [\"/lifecycle/launcher\"]"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "wget --quiet --tries=1 --spider http://localhost:8080/ || exit 1"
                ],
                "Interval": 30000000000,
                "Timeout": 1000000000,
                "StartPeriod": 60000000000,
                "Retries": 1
            },
            "ArgsEscaped": true,
            "Image": "sha256:7ec594c471f3b1d662243a0931dc4b93fa6c05eca752a12408ad0c4d4bc797cc",
            "Volumes": null,
            "WorkingDir": "/workspace",
            "Entrypoint": [
                "/lifecycle/launcher"
            ],
            "OnBuild": [],
            "Labels": {
                "io.buildpacks.stack.id": "io.buildpacks.stacks.bionic"
            }
        },
        "DockerVersion": "17.09.0-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "pack",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PACK_USER_ID=1000",
                "PACK_GROUP_ID=1000",
                "PACK_USER_GID=1000"
            ],
            "Cmd": null,
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "wget --quiet --tries=1 --spider http://localhost:8080/ || exit 1"
                ],
                "Interval": 30000000000,
                "Timeout": 1000000000,
                "StartPeriod": 60000000000,
                "Retries": 1
            },
            "ArgsEscaped": true,
            "Image": "sha256:7ec594c471f3b1d662243a0931dc4b93fa6c05eca752a12408ad0c4d4bc797cc",
            "Volumes": null,
            "WorkingDir": "/workspace",
            "Entrypoint": [
                "/lifecycle/launcher"
            ],
            "OnBuild": [],
            "Labels": {
                "io.buildpacks.stack.id": "io.buildpacks.stacks.bionic"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 161582522,
        "VirtualSize": 161582522,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/a30abadf243df580b47ab633a56916071b1dd03165a69faa8b5116c68f585ebd/diff:/var/lib/docker/overlay2/3e3004faf8293a83cee8a9e11b1a3d1abf397166da46938fce9f7f533d1f7921/diff:/var/lib/docker/overlay2/1a5830e2ca6f845da6db67898b00b6a756bad402bc5140948d400c7aadc74ab9/diff:/var/lib/docker/overlay2/9f7c5aa62820abc82b12c8f1579cb1b2adbd32cc7472fd98f4cae42f0c5b3a88/diff:/var/lib/docker/overlay2/58eec3bdc2754c003949f08d80d6fa8aaf4f9ef3a8018867f6d48c69c3feb887/diff:/var/lib/docker/overlay2/1ce52da8b8f8936be713ec3ef6e5ffa9f8f95048535957c4aebaca80a25c659b/diff:/var/lib/docker/overlay2/5cb22e76ecec445fd7106045ddbef858d510ca569d7f5eb46a17ee4d0e58e7d2/diff:/var/lib/docker/overlay2/153efab29cef6d06eecae1b98904af0fd729efc8893a71a76840382196f76c3d/diff:/var/lib/docker/overlay2/3e44a86af4ad5b492a132bf75c123ce6396a304913f88c2edee703dbdd85081c/diff",
                "MergedDir": "/var/lib/docker/overlay2/7afd367c3f26e131ad43d216a3e25ee8a78972f574f81483b902eafe1450072d/merged",
                "UpperDir": "/var/lib/docker/overlay2/7afd367c3f26e131ad43d216a3e25ee8a78972f574f81483b902eafe1450072d/diff",
                "WorkDir": "/var/lib/docker/overlay2/7afd367c3f26e131ad43d216a3e25ee8a78972f574f81483b902eafe1450072d/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:102645f1cf722254bbfb7135b524db45fbbac400e79e4d54266c000a5f5bc400",
                "sha256:ae1f631f14b7667ca37dca207c631d64947c60d923995cf0d73ceb1b08c406bb",
                "sha256:2146d867acf390370d4d0c7b51951551e0e91fb600b69dbc8922d531b05b12bc",
                "sha256:76c033092e100f56899d7402823c5cb6ce345442b3382d7b240350ef4252187e",
                "sha256:c10efabf98772b6535b0cde4a43eb6412a6a301240c41f96cb76bdb427f62b3f",
                "sha256:f3a4183a422829f45d9e0cee38de89dc315014bd55ec9f718cfdc4c515028fa1",
                "sha256:063ad9c0de0941345fa7483c837da8e60447352cdf4d63483e046012c8ac2d1c",
                "sha256:4aa81ade9932ac33df5b431f0bb97e7dcd72eaff951fb16d2513870c4de04c40",
                "sha256:abcb9772268e5144728a765068bafe3cacb4ff892472b936d88317c57d4c73c6",
                "sha256:c83b22d74d49e58c7432e4752fc22c1142572cbc5a8c8187ca5036ecf19acbf3"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

Tried riff create function using local path and still failing with same issue
~/workspace/java-boot-uppercase$ riff function create uppercase --local-path . --image eesanaws/uppercase
2019/02/28 15:10:38 Pulling builder image 'projectriff/builder' (use --no-pull flag to skip this step)
2019/02/28 15:10:42 Using user provided run image 'packs/run'

Error: invalid run image "packs/run": missing required label "io.buildpacks.stack.id"

**Comment by scothis** [comment]
@ekcasey have you seen an error like this before?

```
~/workspace/java-boot-uppercase$ riff function create uppercase --local-path . --image eesanaws/uppercase
2019/02/28 15:10:38 Pulling builder image 'projectriff/builder' (use --no-pull flag to skip this step)
2019/02/28 15:10:42 Using user provided run image 'packs/run'

Error: invalid run image "packs/run": missing required label "io.buildpacks.stack.id"
```

I'm unable to reproduce the error. This version of riff is using pack 0.0.4 internally. We're blocked from upgrading until pack@0.1.0.

**Comment by eesan** [comment]
Hi @scothis 
I read through this link https://github.com/projectriff/java-function-invoker and found that :
If using Minikube then should configure Docker to use the Docker environment running in Minikube:
$ eval $(minikube docker-env)

After issuing this command it works. Thanks for the help...
