### ISSUE TITLE
`riff system uninstall` should remove Istio by default

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#1125]
Currently to remove Istio you must opt-in during `riff system uninstall --istio`. This is backwards, `riff system uninstall` should remove all resources created by `riff system install`. Istio should be removed by default, the exceptional case is wanting to preserve istio between installs.

I propose we remove the `--istio` flag. If still have a strong use case for keeping Istio around, we can add a `--keep-istio` flag for users who want to preserve the Istio install. (The original rational was to make it easier for rapid install/uninstall cycles, but I'd argue we're not actually testing full uninstall/install in that case). Keeping Istio between installs implies that version of Istio is compatible with the new Knative install, which may not be true.

cc @trisberg

**Comment by trisberg** [comment]
The intention was to separate Istio from Knative in terms of installation. We wanted to allow for installing riff on a cluster that already had Istio installed. In that case there is no way of knowing where Istio came from. It seems that the goal for Knative was to be able to use a standard Istio install separate from Knative.

In practice Knative and Istio are still installed together most of the time for riff. I don't see a strong point for changing the flags but don't really mind if we do change it to `--keep-istio` or something like `--knative-only`

**Comment by scothis** [comment]
The `riff system` commands no longer exist. The cnab bundle is responsible for removing resources it created during uninstall
