### ISSUE TITLE
Combine --registry-host and --registry-protocol as --registry for namespace init

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#1140]
Why are `--registry-host` and `--registry-protocol` separate flags? I would expect a single flag named `--registry` that optionally includes the scheme. It seems the only reason they are separate to to make input validation a little bit easier within riff. We should bias towards making the experience easier for users by combining the flags.

cc @fbiville

**Comment by fbiville** [comment]
Looking at https://github.com/projectriff/riff/pull/1104, the motivation was based on [this comment](
https://github.com/projectriff/riff/pull/1104#issuecomment-464819185). In a nutshell:

```
 $ docker pull index.docker.io/ubuntu:16.04 #works fine
 $ docker pull https://index.docker.io/ubuntu:16.04
```

Happy to revisit the ergonomics if that still seems necessary.

**Comment by scothis** [comment]
@fbiville thanks.

Registry authentication is orthogonal to the image name that is pushed/pulled from the registry. They are so close it's tempting to conflate them, but they are distinct.

- DockerHub is a single registry with multiple users, putting the username into the path
- GCR is similar to DockerHub, but the path contains the project-id instead of a username, the username is hardcoded
- ACR and ECR create multiple distinct registries

There's no generic way to take a registry host and an auth username and derive an image prefix.
