### ISSUE TITLE
Introduce `riff status/doctor`

### ISSUE THREAD

**Issue by fbiville** [projectriff/riff#1156]
This command would report whether Knative/Istio and various riff bits are installed.
If they are, it would output the version of each component.

**Comment by scothis** [comment]
`riff system` has been put out to pasture, but the concept here is good.

I'd like to have a single command that checks if the system components are installed, healthy, and that the current user has the correct RBAC permissions for the namespace to successfully use riff. I proposed `riff doctor` at one point, but the name isn't critical.

**Comment by scothis** [comment]
Resolved by #1331
