### ISSUE TITLE
k3s support

### ISSUE THREAD

**Issue by ghost** [projectriff/riff#1171]
https://github.com/rancher/k3s
its 40 mb as a binary.

can run knative
https://github.com/rancher/k3s/issues/90

it also runs on rasp pi
https://blog.alexellis.io/test-drive-k3s-on-raspberry-pi/

seems like a perfect match for serverless.

**Comment by scothis** [comment]
@gedw99 thanks for your interest. From skimming that issue, it looks like there are still a couple issues to be worked out between k3s and Knative. That basic level of compatibility will need to be solved first.

In order for riff to include k3s as a supported environment, we need to add it to our acceptance test suite [FATS](https://github.com/projectriff/fats). I'd expect k3s to be similar to Minikube, which we [already have support for](https://github.com/projectriff/fats/tree/master/clusters/minikube).

Would you be willing to contribute k3s support to riff/FATS? If you need a quick tour of FATS please let me know, we haven't seen any external contribution there so far, and the docs are a bit sparse.
