### ISSUE TITLE
Maven cache not shared across java function builds

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#1198]
recording here for discussion and consideration to include in v0.3.0 milestone
running riff cli: 0.3.0-snapshot (b07ffe0366ce7474a99db484c95ab245cbfb9cd1)

java builds for 2 different functions do not appear to be able to share the maven download cache.

To reproduce create 2 different functions using the same git repo:. All the maven artifacts will be downloaded twice.

```
riff function create hello1 --git-repo https://github.com/jldec/java-hello --handler functions.Hello --verbose
```
```
riff function create hello2 --git-repo https://github.com/jldec/java-hello --handler functions.Hello --verbose
```

**Comment by jldec** [comment]
The same currently also applies to --local-path builds.

**Comment by scothis** [comment]
In general, this is working as designed.

If you don't know the providence of the maven cache, it's dangerous to use. If I was a malicious actor and wanted to take control of all java processes running on the system without having commit rights to the source repo or control over the maven repository dependencies are pulled from, I could run a malicious build that poisons the cache that other build use, poisoning the output of those builds.

pack isolates the cache based on the image name that is being published. So even if we used the same cache volume, the buildpacks will not use the same cache. The cache is intended to speed up rebuilds of the same image, not independent builds.

**Comment by trisberg** [comment]
I agree that what we currently have should be the default behavior.  I do think that we could give the developer more control though and manage what cache PVC is used for each build and also manage the cache lifecycle by allowing the cache to stick around after the function is deleted.

**Comment by scothis** [comment]
> I do think that we could give the developer more control though and manage what cache PVC is used for each build and also manage the cache lifecycle by allowing the cache to stick around after the function is deleted.

Sharing the same PVC doesn't actually solve your problem and hurts build performance as the volume can only be actively bound to a single pod.

**Comment by trisberg** [comment]
> Sharing the same PVC doesn't actually solve your problem

If we request the feature to provide a shared cache for the "buildpack" then it could help. We are not the only ones that are going to complain about the excessive maven downloads. As long as the developer manages the maven cache for their builds it would be up to the developer to make sure that each build either use different cache if they have to run concurrently or run them in sequence.

**Comment by scothis** [comment]
@nebhale what are your thoughts here?

**Comment by nebhale** [comment]
I don't think you should ever share dependencies caches in a multi-tenant environment for the obvious security issues identified above.  On the application side, this is manifest as pipelines responsible for building artifacts for deployments and deploying compiled applications, but obviously this doesn't match on the function side.

For what it's worth, node applications and ruby applications don't even have the concept of a shared cache and no one really has a problem with them going off and downloading the world the first time.
