### ISSUE TITLE
Improve function create log gathering and polling logic

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#1233]
The current code, particularly the [logic ](https://github.com/projectriff/riff/blob/2a9795bdf4c5d167daca0c3d213591f16457ade2/pkg/core/function.go#L186-L201)which handles `--verbose` and `--wait`, is complex and hard to maintain. We should look at ways of improving the unit testing of this code. This is non-trivial because of the concurrency involved.

**Comment by scothis** [comment]
done in #1266
