### ISSUE TITLE
cut riff release v0.3.0

### ISSUE THREAD

**Issue by fbiville** [projectriff/riff#1248]
- [x] set `VERSION` file to `0.3.0` and push to `v0.3.x`
- [x] wait for CI to pass
- [x] smoke test release binaries
- [x] tag new commit on `v0.3.x` branch: `v0.3.0`
- [x] create a draft release on GitHub for the `v0.3.0` tag
- [x] upload binaries (from GCS) to new release on GitHub (needs to use the exact sha, as this appears in `riff version`)
- [x] set `VERSION` file to `0.3.1-snapshot`, commit and push to `v0.3.x`
- [x] push remaining open issues from current to next milestone
- [x] rename next milestone to current
- [x] create new next milestone
- [x] publish the draft release on GitHub for the `v0.3.0` tag
- [x] update Homebrew recipe
    - [x] [PR](https://github.com/Homebrew/homebrew-core/pull/38815) merged
- [x] update Chocolatey repo ([change](https://github.com/projectriff/chocolatey/commit/d3f1bd553b33a47e5f427492a222c1a973c7fc9a))
    - [x] update validated | [link](https://chocolatey.org/packages/riff/0.3.0)
- [x] merge blog post

**Comment by trisberg** [comment]
FYI: to generate the binaries for previous releases I've been running the build as either root (suing sudo) or as a separate user account named riff since the owner of the binary file shows up inside the archives

**Comment by scothis** [comment]
@trisberg yep, we'll grab the CI tested artifacts off GCS

**Comment by fbiville** [comment]
Homebrew PR created: https://github.com/Homebrew/homebrew-core/pull/38815.

**Comment by fbiville** [comment]
Preparing Chocolatey update: https://github.com/projectriff/chocolatey/pull/3.

**Comment by fbiville** [comment]
Now only waiting for Homebrew.

**Comment by fbiville** [comment]
Homebrew PR is merged 🎉
