### ISSUE TITLE
Reuse the initial secret to configure the default service account image pull secret

### ISSUE THREAD

**Issue by fbiville** [projectriff/riff#1263]
The process is described [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account).

TODO: verify push secrets can be used as pull secrets.

Now, `namespace init`/`namespace cleanup` are going to be deprecated/removed as specified https://github.com/projectriff/riff/issues/817#issuecomment-489078485 so the imagePullSecret binding has to be done in `credentials set`.

This should be done with an explicit option as the default service account is going to be modified.
Note: the default secret name `push-credentials` will have to be changed because the secret to be set is not necessarily only about image push from now on.

**Comment by scothis** [comment]
This is actionable, but will need to be implemented in projectriff/system
