### ISSUE TITLE
cut riff release v0.3.2

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#1279]
- [ ] set `VERSION` file to `0.3.2` and push to `v0.3.x`
- [ ] wait for CI to pass
- [ ] smoke test release binaries
- [ ] tag new commit on `v0.3.x` branch: `v0.3.2`
- [ ] create a draft release on GitHub for the `v0.3.2` tag
- [ ] upload binaries (from GCS) to new release on GitHub (needs to use the exact sha, as this appears in `riff version`)
- [ ] set `VERSION` file to `0.3.3-snapshot`, commit and push to `v0.3.x`
- [ ] publish the draft release on GitHub for the `v0.3.2` tag
- [ ] update Homebrew recipe and create PR
- [ ] update Chocolatey repo and publish
- [ ] merge blog post

**Comment by scothis** [comment]
We haven't done this yet, so I doubt we will
