### ISSUE TITLE
Implement TCK for function invokers

### ISSUE THREAD

**Issue by dturanski** [projectriff/riff#128]
(from #267) There must be a clear contract between the function-sidecar and the *-function-invokers. As the protocol is formalized between the sidecar and invoker (whether based on HTTP, gRPC or something else) we should have confidence that the invoker is correctly invoking functions. An acceptance test suite will make it easier for us to ensure each provided invoker is functioning correctly, as well as third party invokers can ensure their compatibility.

**Comment by jldec** [comment]
@dturanski could you explain a little more what this means? (feel free to edit the original description)

**Comment by scothis** [comment]
From #267

> There must be a clear contract between the `function-sidecar` and the `*-function-invoker`s. As the protocol is formalized between the sidecar and invoker (whether based on HTTP, gRPC or something else) we should have confidence that the invoker is correctly invoking functions. An acceptance test suite will make it easier for us to ensure each provided invoker is functioning correctly, as well as third party invokers can ensure their compatibility.

A TCK would drive the invoker as the function-sidecar would in production. The TCK produces test messages and asserts on the response messages. The invoker would need to implement a function in it's natural language that can satisfy the TCK test.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
