### ISSUE TITLE
Proposal: move CLI into a separate repo, leaving an issue/roadmap repo

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#1323]
We don't have a good place to open cross cutting issues that effect multiple repositories. The best place is in this repo, but it get mixed up with issues specific to the CLI.

We don't want to rewrite history, or break links to existing releases, so we should **not** rename the repo.

- create a `cli` repo
- push all of the commits from this repo into the `cli` repo (rename go import as needed)
- add a commit to the `riff` repo removing all source code
- migrate CLI issues to the `cli` repo
- migrate CI to the new repo
- close open PRs asking the author to recreate the PR

**Comment by sbawaska** [comment]
I think this repository can also serve as a getting started guide, since our install and cli are now spread across two repos.
