### ISSUE TITLE
Expose concurrency controls on knative deployers 

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#1340]
As a developer i would like to be able to limit per-instance concurrency of handled requests e.g. to 1.

Knative serving supports this with `containerConcurrency` in the [revision spec](https://github.com/knative/serving/blob/master/docs/spec/spec.md) but is not [yet](https://github.com/knative/serving/issues/4833) globally defaultable.

This is also exposed on https://cloud.google.com/run/docs/about-concurrency.

**Comment by joshrider** [comment]
Concurrency added to [system](https://github.com/projectriff/system/pull/294) and [CLI](https://github.com/projectriff/cli/pull/186).
