### ISSUE TITLE
Rename Handler types

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#1346]
"Handler" is overloaded with the Function's handler field and the core and knative runtime Handler types.

Proposal:
- Handler.core.projectriff.io -> Deployer.core.projectriff.io
- Handler.knative.projectriff.io -> Deployer.knative.projectriff.io

**Comment by trisberg** [comment]
Don't these CRDs do the same thing? Launch an app with a way to invoke it? Why different names?

**Comment by scothis** [comment]
Landed on `Deployer.(core|knative).projectriff.io` with short names to distinguish in kubectl
