### ISSUE TITLE
Make Knative Serving optional

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#1347]
Now that we have multiple runtime options, some users may not want Knative installed by default. riff System current assumes Knative Serving is available and will need to be coaxed when not available. The helm charts should be updated to make Knative Serving opt-in.

Knative Build will remain a hard requirement.

**Comment by trisberg** [comment]
We also need to fix `riff doctor` to accept that it's OK for knative-serving to be missing

**Comment by scothis** [comment]
Done in https://github.com/projectriff/charts/pull/14
