### ISSUE TITLE
Expose autoscaling controls like minScale, maxScale, and scale-to-zero-grace-period on Knative deployers 

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#1368]
As a riff user I would like to deploy long-running apps or apps which don't receive input requests using a Knative deployer. Currently this is difficult because of autoscaling to zero after a 30s default idle time.

See also #1340 and Knative Serving [docs](https://knative.dev/docs/serving/configuring-the-autoscaler/#configuring-scale-bounds-minscale-and-maxscale)

**Comment by jldec** [comment]
Suggest following RFC process to evaluate design alternatives e.g. new CLI flags or alternative kustomization.

**Comment by joshrider** [comment]
Added min and max scale flags to the cli for the knative deployer:
https://github.com/projectriff/cli/pull/174

**Comment by joshrider** [comment]
UPDATE
Support for min and max flags added to [system](https://github.com/projectriff/system/pull/228) and [CLI](https://github.com/projectriff/cli/pull/174).

Scale-to-zero-grace-period still outstanding.
