### ISSUE TITLE
Release riff v0.5.0

### ISSUE THREAD

**Issue by ekcasey** [projectriff/riff#1375]
![release-flow](https://user-images.githubusercontent.com/302992/73996519-cbce4080-4929-11ea-8a05-34b50877d306.png)

# riff 0.5.0

- review [open issues](https://github.com/orgs/projectriff/projects/6)
- review [open PRs](https://github.com/pulls?utf8=✓&q=is%3Aopen+is%3Apr+org%3Aprojectriff+draft%3Afalse)

- [x] fats (phase 1)
  - [x] create branch `v0.5.x`
- [x] node-function-invoker (v0.2.0)
  - [x] update version in package.json to `0.2.0`
  - [x] run `npm install && npm test` to update npm-shrinkwrap.json
  - [x] commit changes and push to master
  - [x] wait for CI to go green
  - [x] tag commit as `v0.2.0`, push
  - [x] wait for CI to go green
  - [x] update version in package.json to `0.2.1-snapshot`
  - [x] npm install
  - [x] commit changes and push to master
- [x] java-function-invoker (v0.2.0)
  - [x] update version in pom.xml to `0.2.0`
  - [x] commit changes and push to master
  - [x] wait for CI to go green
  - [x] tag commit as `v0.2.0`, push
  - [x] wait for CI to go green
  - [x] update version in pom.xml to `0.2.1-SNAPSHOT`
  - [x] commit changes and push to master
- [x] command-function-invoker (v0.1.0)
  - [x] update version in VERSION to `0.1.0`
  - [x] commit changes and push to master
  - [x] wait for CI to go green
  - [x] tag commit as `v0.1.0`, push
  - [x] wait for CI to go green
  - [x] update version in VERSION to `0.1.1-snapshot`
  - [x] commit changes and push to master
- [x] streaming-http-adapter (v0.5.0)
  - [x] update version in VERSION to `0.5.0`
  - [x] commit changes and push to master
  - [x] wait for CI to go green
  - [x] tag commit as `v0.5.0`, push
  - [x] update version in VERSION to `0.5.1-snapshot`
  - [x] commit changes and push to master
- [x] libfnbuildpack (v0.4.0)
  - [x] tag commit as `v0.4.0`, push
- [x] node-function-buildpack (v0.2.0)
  - [x] consume libfnbuildpack v0.4.0 in go.mod
  - [x] consume node-function-invoker v0.2.0 in buildpack.toml
  - [x] consume streaming-http-adapter v0.5.0 in buildpack.toml
  - [x] update version in buildpack.toml to `0.2.0`
  - [x] run `go mod tidy` and `make`
  - [x] commit changes and push to master
  - [x] wait for CI to go green
  - [x] tag commit as `v0.2.0`, push
  - [x] wait for CI to go green
  - [x] update version in buildpack.toml to `0.3.0-BUILD-SNAPSHOT`
  - [x] commit changes and push to master
- [x] java-function-buildpack (v0.2.0)
  - [x] consume libfnbuildpack v0.4.0 in go.mod
  - [x] consume java-function-invoker v0.2.0 in buildpack.toml
  - [x] consume streaming-http-adapter v0.5.0 in buildpack.toml
  - [x] update version in buildpack.toml to `0.2.0`
  - [x] run `go mod tidy` and `make`
  - [x] commit changes and push to master
  - [x] wait for CI to go green
  - [x] tag commit as `v0.2.0`, push
  - [x] wait for CI to go green
  - [x] update version in buildpack.toml to `0.3.0-BUILD-SNAPSHOT`
  - [x] commit changes and push to master
- [x] command-function-buildpack (v0.1.0)
  - [x] consume libfnbuildpack v0.4.0 in go.mod
  - [x] consume command-function-invoker v0.1.0 in buildpack.toml
  - [x] update version in buildpack.toml to `0.1.0`
  - [x] run `go mod tidy` and `make`
  - [x] commit changes and push to master
  - [x] wait for CI to go green
  - [x] tag commit as `v0.1.0`, push
  - [x] wait for CI to go green
  - [x] update version in buildpack.toml to `0.2.0-BUILD-SNAPSHOT`
  - [x] commit changes and push to master
- [x] builder (v0.5.0)
  - [x] create branch `v0.5.x`
  - in builder.toml.tpl.tpl
    - [x] consume node-function-buildpack by switching to `releases/master`
    - [x] consume java-function-buildpack by switching to `releases/master`
    - [x] consume command-function-buildpack by switching to `releases/master`
  - [x] run `make templates`
  - [x] verify templated versions
    - node-function-buildpack v0.2.1
    - java-function-buildpack v0.2.1
    - command-function-buildpack v0.1.0
  - [x] update version in VERSION to `0.5.0`
  - [x] commit changes and push to v0.5.x
  - [x] wait for CI to go green
  - [x] tag commit as `v0.5.0`, push
  - [x] wait for CI to go green
  - [x] update version in VERSION to `0.5.1-snapshot`
  - [x] commit changes and push to v0.5.x
  - [x] switch to master branch
  - [x] update version in VERSION to `0.6.0-snapshot`
  - [x] commit changes and push to master
- [x] nop-provisioner (v0.5.0)
  - [x] create branch `v0.5.x`
  - [x] update version in VERSION to `0.5.0`
  - [x] commit changes and push to v0.5.x
  - [x] wait for CI to go green
  - [x] tag commit as `v0.5.0`, push
  - [x] wait for CI to go green
  - [x] update version in VERSION to `0.5.1-snapshot`
  - [x] commit changes and push to v0.5.x
  - [x] switch to master branch
  - [x] update version in VERSION to `0.6.0-snapshot`
  - [x] commit changes and push to master
- [x] kafka-provisioner (v0.5.0)
  - [x] create branch `v0.5.x`
  - [x] update version in VERSION to `0.5.0`
  - [x] commit changes and push to v0.5.x
  - [x] wait for CI to go green
  - [x] tag commit as `v0.5.0`, push
  - [x] wait for CI to go green
  - [x] update version in VERSION to `0.5.1-snapshot`
  - [x] commit changes and push to v0.5.x
  - [x] switch to master branch
  - [x] update version in VERSION to `0.6.0-snapshot`
  - [x] commit changes and push to master
- [x] pulsar-provisioner (v0.5.0)
  - [x] create branch `v0.5.x`
  - [x] update version in VERSION to `0.5.0`
  - [x] commit changes and push to v0.5.x
  - [x] wait for CI to go green
  - [x] tag commit as `v0.5.0`, push
  - [x] wait for CI to go green
  - [x] update version in VERSION to `0.5.1-snapshot`
  - [x] commit changes and push to v0.5.x
  - [x] switch to master branch
  - [x] update version in VERSION to `0.6.0-snapshot`
  - [x] commit changes and push to master
- [x] streaming-processor (v0.5.0)
  - [x] create branch `v0.5.x`
  - [x] update version in pom.xml to `0.5.0`
  - [x] commit changes and push to v0.5.x
  - [x] wait for CI to go green
  - [x] tag commit as `v0.5.0`, push
  - [x] wait for CI to go green
  - [x] update version in pom.xml to `0.5.1-SNAPSHOT`
  - [x] commit changes and push to v0.5.x
  - [x] switch to master branch
  - [x] update version in pom.xml to `0.6.0-SNAPSHOT`
  - [x] commit changes and push to master
- [x] system (v0.5.0)
  - [x] create branch `v0.5.x`
  - [x] consume fats v0.5.x as gitsha in ci.yaml
  - [x] consume nop-provisioner `:0.5.0` in inmemory-gateway.yaml.tpl
  - [x] consume kafka-provisioner `:0.5.0` in kafka-gateway.yaml.tpl
  - [x] consume pulsar-provisioner `:0.5.0` in pulsar-gateway.yaml.tpl
  - [x] consume streaming-processor `:0.5.0` in processor.yaml.tpl
  - [x] run `make templates`
  - [x] run `make`
  - [x] update version in VERSION to `0.5.0`
  - [x] commit changes and push to v0.5.x
  - [x] wait for CI to go green
  - [x] tag commit as `v0.5.0`, push
  - [x] wait for CI to go green
  - [x] update version in VERSION to `0.5.1-snapshot`
  - [ ] ~consume nop-provisioner `:0.5.1-snapshot` in inmemory-gateway.yaml.tpl~
  - [ ] ~consume kafka-provisioner `:0.5.1-snapshot` in kafka-gateway.yaml.tpl~
  - [ ] ~consume pulsar-provisioner `:0.5.1-snapshot` in pulsar-gateway.yaml.tpl~
  - [ ] ~consume streaming-processor `:0.5.1-snapshot` in processor.yaml.tpl~
  - [x] run `make templates`
  - [x] run `make`
  - [x] commit changes and push to v0.5.x
  - [x] switch to master branch
  - [x] update version in VERSION to `0.6.0-snapshot`
  - [x] consume nop-provisioner `:0.6.0-snapshot` in inmemory-gateway.yaml.tpl
  - [x] consume kafka-provisioner `:0.6.0-snapshot` in kafka-gateway.yaml.tpl
  - [x] consume pulsar-provisioner `:0.6.0-snapshot` in pulsar-gateway.yaml.tpl
  - [x] consume streaming-processor `:0.6.0-snapshot` in processor.yaml.tpl
  - [x] run `make templates`
  - [x] run `make`
  - [x] commit changes and push to master
- [x] release (v0.5.0)
  - [x] create branch `v0.5.x`
  - [x] consume fats v0.5.x as gitsha in ci.yaml
  - [x] consume builder v0.5.0 in riff-builders/templates.yaml.tpl, switching to `releases/v0.5.x`
  - [x] consume system v0.5.0
    - [x] in riff-build-runtime/templates.yaml.tpl, switching to `releases/v0.5.x`
    - [x] in riff-core-runtime/templates.yaml.tpl, switching to `releases/v0.5.x`
    - [x] in riff-knative-runtime/templates.yaml.tpl, switching to `releases/v0.5.x`
    - [x] in riff-streaming-runtime/templates.yaml.tpl, switching to `releases/v0.5.x`
  - [x] run `make templates`
  - [x] update version in VERSION to `0.5.0`
  - [x] commit changes and push to v0.5.x
  - [x] wait for CI to go green
  - [x] tag commit as `v0.5.0`, push
  - [x] wait for CI to go green
  - [x] update version in VERSION to `0.5.1-snapshot`
  - [x] commit changes and push to v0.5.x
  - [x] switch to master branch
  - [x] update version in VERSION to `0.6.0-snapshot`
  - [x] commit changes and push to master
- [x] cli (v0.5.0)
  - [x] create branch `v0.5.x`
  - [x] consume fats v0.5.x as gitsha in acceptance.sh
  - [x] consume system v0.5.0 in go.mod
  - [x] run `go mod tidy`
  - [x] update version in VERSION to `0.5.0`
  - [x] commit changes and push to v0.5.x
  - [x] wait for CI to go green
  - [x] tag commit as `v0.5.0`, push
  - [x] wait for CI to go green
  - [x] update version in VERSION to `0.5.1-snapshot`
  - [x] commit changes and push to v0.5.x
  - [x] switch to master branch
  - [x] update version in VERSION to `0.6.0-snapshot`
  - [x] commit changes and push to master
  - [x] create draft release on github
    - [x] upload artifacts build by CI from GCS
    - [x] attach release notes
- [x] stream-client-go (v0.5.0)
  - [x] tag commit as `v0.5.0`, push
  - [x] wait for CI to go green
- [x] dev-utils (v0.5.0)
  - [x] create branch `v0.5.x`
  - [x] consume cli v0.5.0 in Dockerfile
  - [x] consume stream-client-go v0.5.0 in go.mod
  - [x] run `go mod tidy`
  - [x] update version in VERSION to `0.5.0`
  - [x] commit changes and push to v0.5.x
  - [x] wait for CI to go green
  - [x] tag commit as `v0.5.0`, push
  - [x] wait for CI to go green
  - [x] update version in VERSION to `0.5.1-snapshot`
  - [x] commit changes and push to v0.5.x
  - [x] switch to master branch
  - [x] update version in VERSION to `0.6.0-snapshot`
  - [x] commit changes and push to master
- [x] chocolatey
  - [x] wait for cli release to be published on github
  - [x] consume cli v0.5.0
  - [x] commit changes and push to master
  - [x] publish to chocolatey: https://chocolatey.org/packages/riff/0.5.0
- [x] homebrew
  - [x] send PR upstream: https://github.com/Homebrew/homebrew-core/pull/50023
- [x] projectriff.io
  - [x] merge https://github.com/projectriff/projectriff.io/pull/202
- [x] fats (phase 2)
  - [x] update cli tool install to consume 0.5.x snapshots
  - [x] update acceptance install version to latest v0.5.x release snapshot
  - [x] commit and push to v0.5.x branch
  - [x] push new commit sha out to consumers on their v0.5.x branch
    - [x] cli
    - [x] system
    - [x] release

- [x] 🍻🎉

**Comment by jldec** [comment]
@ericbottard can you clarify the status of the pulsar and kafka provisioners
- are they in a state that we can release them with v0.5?
- if not, should we remove them from the v0.5 cli and docs?

cc: @scothis

**Comment by ericbottard** [comment]
The provisioners (I assume you actually mean providers) are fine themselves. There has been minimal manual testing with pulsar, but the (out-of-scope) installation of pulsar is not documented. Also there is no pulsar equivalent to https://projectriff.io/docs/v0.5/runtimes/streaming#kafkaprovider in docs (which includes a sample kafka install, so we could have a pulsar one there as well)

**Comment by scothis** [comment]
@jldec for the record, the in-memory, kafka and pulsar gateways are all included in this release, with passing tests.

**Comment by scothis** [comment]
@fbiville can you update chocolatey and homebrew?

**Comment by jldec** [comment]
FYI
CI failed for the version bump commit on projectriff/release
https://github.com/projectriff/release/commit/9dfe1e66af0c62b7fca964f299fdf10155189130

This resulted in https://github.com/projectriff/projectriff.io/issues/209

**Comment by fbiville** [comment]
> @fbiville can you update chocolatey and homebrew?

Done.

**Comment by jldec** [comment]
Thanks all!
