### ISSUE TITLE
Need to solve keda install for k8s v1.16+

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#1377]
We can't use `kapp` for installing `keda` on Kubernetes v1.16 or later since `keda` still use `k8s.io` in the API group.

- message: protected groups must have approval annotation "api-approved.kubernetes.io",
   see https://github.com/kubernetes/enhancements/pull/1111

**Comment by jldec** [comment]
E.g issue for users with latest minikube.

- file issue against keda
- talk to Dmitry about kapp workaround

**Comment by trisberg** [comment]
In the meantime we can skip the wait

```
kapp deploy -n apps -a keda -f https://storage.googleapis.com/projectriff/release/0.5.0-snapshot/keda.yaml --wait=false
```

**Comment by trisberg** [comment]
Created KEDA issue https://github.com/kedacore/keda/issues/552

**Comment by trisberg** [comment]
I created https://github.com/projectriff/release/issues/130 so we don't forget
