### ISSUE TITLE
document expectations of the function container build

### ISSUE THREAD

**Issue by markfisher** [projectriff/riff#142]
includes: base image, added artifact(s), and FUNCTION_URI env var

for example, java:
```
FROM sk8s/java-function-invoker:0.0.1-SNAPSHOT
ADD target/greeter-1.0.0.jar /functions/function.jar
```

js:
```
FROM sk8s/node-function-invoker:0.0.1-SNAPSHOT
ENV FUNCTION_URI /functions/function.js
ADD square.js /functions/function.js
```

shell:
```
FROM sk8s/shell-function-invoker:0.0.1-SNAPSHOT
ADD echo.sh /functions/script.sh
```

related to #126

**Comment by jldec** [comment]
provide at least one page overview doc for 0.0.3

**Comment by jldec** [comment]
Templates for Dockerfiles and yaml are now embedded in the cli / riff script.

Future direction is to extract those templates into invokers, so that a custom invokers can work with the unmodified cli.
