### ISSUE TITLE
switch to the Go topic-controller

### ISSUE THREAD

**Issue by markfisher** [projectriff/riff#145]
this should include deletion of the Java `topic-controller` as well as updates to the README (and a `./build-topic-controller` script if we continue that model)

we need to update the deployment config with the appropriate liveness/readiness probes (if different from the current Java endpoints)

the Go `topic-controller` should then be fully enabled in the end-to-end CI process as well

**Comment by ericbottard** [comment]
Not sure what you mean with "non http probes". This is a *controller*, so we can create http probes easily

**Comment by markfisher** [comment]
I updated the comment (I had misunderstood a different comment to mean that this process would not be exposing web endpoints).

**Comment by ericbottard** [comment]
Done in 31a9b88c4cd33767bb7f042dd4ccd2b4b54649d1
