### ISSUE TITLE
function yaml should accept volume mounts

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#154]
This will make it possible to use ConfigMaps

**Comment by markfisher** [comment]
This should already be possible now that we're accepting the entire container yaml format as of: https://github.com/markfisher/sk8s/commit/3ad0d58bfe8983d352a165beddde1208eb81a76b

**Comment by trisberg** [comment]
The `volumes` definition is outside of the container while the `volume-mount` is part of the container definition.

**Comment by markfisher** [comment]
Right, actual `volume` definitions would need to be outside of the `container` spec, similar to https://github.com/markfisher/sk8s/issues/155

**Comment by markfisher** [comment]
If the goal is using `ConfigMap` values as environment variables, that can be defined within the `container` spec though (without volume mounts) either at the individual key/value level:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-a-pod-environment-variable-with-data-from-a-single-configmap

...or all of the key/value pairs from a `ConfigMap`:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-pod-environment-variables

**Comment by dturanski** [comment]
Closing this.  See https://github.com/projectriff/kubernetes-crds/issues/6
