### ISSUE TITLE
Support @Autowiring for Spring Java functions

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#157]
We need to load the app context and make sure the autowiring support works for Spring Boot apps following the spring-cloud-function model.

**Comment by markfisher** [comment]
I assigned Dave as I believe he already has this on a branch.

**Comment by ericbottard** [comment]
Closing this as
- it pertains to the java-function-invoker
- I assume it is working now (@dsyer please re-create if this is not the case)
