### ISSUE TITLE
Add asciibuild styles to README files

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [projectriff/riff#160]
[asciibuild](https://github.com/jbrisbin/asciibuild) is a pretty lightweight gem for basically just executing asciidoc files. Essentially all we would have to do is add `[asciibuild, bash]` to some relevant code samples in README files. Then, with the gem installed, running `asciibuild README.adoc` (for example) will execute all the appropriately styled code samples. Coarsely this makes the README into a kind of script for those that want to follow the instructions without actually reading them (something like a "quickstart", which could itself be mentioned in the README) and opens up some options for actually "running the README" on CI.

**Comment by jldec** [comment]
Interesting idea - i think i could have sold people on this at GitHub where everyone was a rubyist :)

My intuition here is that adding another layer of interpreter will not win us more friends in this case. I think I would still prefer, where appropriate, to reduce the steps in the README by automating via runnable bash scripts (which eventually we'll turn into a CLI)

**Comment by ericbottard** [comment]
Trial runs I did were not very concluent.
Also, CI now better tracks local experience by leveraging Makefile where applicable (this was the triggering story for this issue)
