### ISSUE TITLE
Update helm instructions in the Getting Started doc

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#161]
https://github.com/projectriff/riff/blob/master/Getting-Started.adoc is a little out of date. Suggested fixes:

- [x] correct helm repo info
- [x] more details about package contents, image tags etc.
- [x] how to override tags
- [x] how to use helm-installed images for building samples (see #96)
- [x] how to override with a custom build of one component

**Comment by trisberg** [comment]
We also need to move off the SNAPSHOT tags to a curated set of artifacts that work together and won't be overwritten by later builds

**Comment by markfisher** [comment]
A subset of the checkbox items in this issue are being addressed by this PR:
https://github.com/projectriff/riff/pull/182

**Comment by trisberg** [comment]
The rest by https://github.com/projectriff/riff/pull/214
