### ISSUE TITLE
remove spring naming from sidecar properties

### ISSUE THREAD

**Issue by markfisher** [projectriff/riff#164]
we should probably replace `SPRING_APPLICATION_JSON` itself, but also the following keys used within that:

- spring.cloud.stream.bindings.input.destination
- spring.cloud.stream.bindings.input.group
- spring.cloud.stream.bindings.output.destination
- spring.profiles.active
- spring.application.name
- spring.cloud.stream.kafka.binder.brokers
- spring.cloud.stream.kafka.binder.zkNodes
- server.port

We should visit this as part of the upcoming general project naming updates.

**Comment by ericbottard** [comment]
Done in https://github.com/projectriff/function-sidecar/commit/70a50c164449b65f6db9cd9a8792124dbf66a662
