### ISSUE TITLE
ensure compliance with k8s api conventions

### ISSUE THREAD

**Issue by markfisher** [projectriff/riff#17]
https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md

**Comment by ericbottard** [comment]
On the case of `Function.handler`, the very minimum would be to rename to `handlerName`, but I think the very correct thing to do is to use [object reference](https://kubernetes.io/docs/resources-reference/v1.5/#objectreference-v1) (Or maybe a subclass of it that hardcodes the kind to Handler)

**Comment by markfisher** [comment]
Thanks Eric. Had a discussion yesterday where we were also considering whether our current "Dispatcher" strategies should be extracted out to their own components and possibly registered as custom resources as well. At a minimum, we need to have a more robust way to refer to the dispatcher name and its "parameters" than we do currently within the handler resource YAML.

**Comment by ericbottard** [comment]
https://github.com/markfisher/sk8s/pull/20 uses `HandlerRef` instead of `Handler`. In addition to the name change, that Ref encapsulates not only a handler name, but also a namespace (defaulting to the ns of the function if null). Other bits will be easy to add, need to discuss (ie apiVersion).
