### ISSUE TITLE
add build-all and deploy-riff scripts

### ISSUE THREAD

**Issue by markfisher** [projectriff/riff#183]
The `build-all` will invoke each of the existing `build-*` scripts.

The `deploy-all` could simply invoke:

```
kubectl apply -f config/types
kubectl apply -f config/kafka
kubectl apply -f config
```

...as well as taking boolean flags to add configs for rbac, metrics, tracing, etc.

We could of course have a single `build-and-deploy` script, but even then it should delegate to these 2 separate scripts since a `build-all` that builds and registers docker images locally (e.g. when using the minikube docker daemon) could also be invoked before using `helm install` pointing to the "values-snapshot.yaml" file that we'll be creating explicitly for local helm installations.

**Comment by jldec** [comment]
Fixed with monorepo move and new Makefile
see https://github.com/projectriff/riff/commits/master/Makefile
