### ISSUE TITLE
Rebase kubernetes-model on tag v2.0.4 to avoid snapshot deps

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#193]
We could try rebasing the kubernetes-model fork on the `v2.0.4` tag. This would avoid depending on snapshot version of the fabric8io artifacts. This would help with our release.

**Comment by ericbottard** [comment]
Done and released, as https://github.com/projectriff/kubernetes-model/commit/da486786ebfa71725f51d217a202b88497482cf0
