### ISSUE TITLE
Set up a slack/gitter channel

### ISSUE THREAD

**Issue by fitzoh** [projectriff/riff#205]
After the keynote announcement at SpringOne, a whole bunch of people like me are going to come and try to use riff, and fail.

It would be nice if there was a slack or gitter channel which was available for support/discussion that was listed on the README.

I personally have a preference for slack, and think it would probably make the most sense for it to live in the kubernetes slack domain (https://kubernetes.slack.com)

**Comment by jchesterpivotal** [comment]
Thanks. I've asked my peers about where we'd like to put it -- I imagine one of either the Cloud Foundry slack instance or the Kubernetes slack instance.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.

**Comment by kingdonb** [comment]
There isn't a Riff channel on Knative slack, though... trying to blend in?
