### ISSUE TITLE
riff script suggestions

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#215]
1. add version number to `riff` command so that we can field support questions
  - could also show and kubectl, docker versions in the usage
2. make it possible to use riff shell script without cloning repo (download with curl, chmod +x) or brew install

**Comment by trisberg** [comment]
Resolved via https://github.com/projectriff/riff/pull/216

Left out the "could also show and kubectl, docker versions in the usage" suggestion, we could add that later at some point possibly
