### ISSUE TITLE
investigate moving builds into multi-stage Dockerfiles.

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#223]
## option 1
- figure out if we can use [multi-stage](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) Dockerfile 
- and then delegate builds to dockerhub
- also understand implications for local builds and debugging

## other options
- [Google Cloud Container Builder](https://cloud.google.com/container-builder/docs/)
- [Google Cloud Container Registry](https://cloud.google.com/container-registry/docs/)
- [OSS predefined Container Builders](https://github.com/GoogleCloudPlatform/cloud-builders)

### for riff components
- OSS riff build pipeline
- triggered by git commits
- produces tagged containers => input to CI

### for riff users 
- automate container builds when there is just a function
- suggest a workflow with versioning tags

**Comment by jldec** [comment]
### more thoughts on automating container builds
We would prefer to use something that runs on k8s but doing docker builds in-cluster on k8s comes with its own complexities.
  - kubernetes/kubernetes#1806
  - https://applatix.com/case-docker-docker-kubernetes-part/
  - https://applatix.com/case-docker-docker-kubernetes-part-2/

Also looking at [brigade](https://github.com/Azure/brigade/blob/master/docs/topics/design.md#history-of-brigade) which feels like an OSS version of google container builder.

**Comment by freynca** [comment]
Both Google container builder and Dockerhub automated builds can link to GitHub accounts. However, it appears they both need a user with administrative privileges to orgs/repos from which to source; our Git bot does not currently have such privileges.
