### ISSUE TITLE
investigate redis streams

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#225]
### references
- [original post on antirez.com](http://antirez.com/news/114)
- [twitter thread](https://twitter.com/antirez/status/943149491657629698)
- [design requirements for consumer groups](https://gist.github.com/antirez/68e67f3251d10f026861be2d0fe0d2f4#requirements)

(i thought this one was interesting)
> - Serve messages to the client based on what client is available to process messages, without any pre-defined sharding, so that clients able to process messages at different rates does not create any processing hole.

**Comment by jldec** [comment]
see http://antirez.com/news/116

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
