### ISSUE TITLE
Port riff CLI to a high level language

### ISSUE THREAD

**Issue by dturanski** [projectriff/riff#249]
The current shell script implementation is monolithic, currently 600+ LOC in a single file. We are maintaining parallel functionality  as a Windows bat file.  It would be better to implement this in e.g.,  golang, which can work in any environment.

**Comment by scothis** [comment]
Ongoing work at https://github.com/projectriff/riff-cli

**Comment by jldec** [comment]
see https://github.com/projectriff/riff-cli

**Comment by jldec** [comment]
nice work @dturanski and @trisberg !
