### ISSUE TITLE
RBAC error on GKE cluster 

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#262]
I'm seeing the following errors after deploying riff with RBAC enabled on a `1.8.6-gke.0` cluster:

```
E0129 14:33:42.875812       1 reflector.go:205] github.com/projectriff/function-controller/pkg/controller/controller.go:104: Failed to list *v1.Topic: topics.projectriff.io is forbidden: User "system:serviceaccount:default:demo-riff-sa" cannot list topics.projectriff.io at the cluster scope: Unknown user "system:serviceaccount:default:demo-riff-sa"
```

```
E0129 14:35:56.707865       1 reflector.go:205] github.com/projectriff/topic-controller/cmd/topic-controller.go:105: Failed to list *v1.Topic: topics.projectriff.io is forbidden: User "system:serviceaccount:default:demo-riff-sa" cannot list topics.projectriff.io at the cluster scope: Unknown user "system:serviceaccount:default:demo-riff-sa"
```

**Comment by jldec** [comment]
@rmorgan encountered this doing a helm upgrade to 0.0.3 on PKS.

**Comment by rmorgan** [comment]
In looking at my logs, they are slightly different:
```
E0126 23:30:58.210762       1 reflector.go:205] github.com/projectriff/function-controller/pkg/controller/controller.go:105: Failed to list *v1.Function: functions.projectriff.io is forbidden: User "system:serviceaccount:default:demo-riff-sa" cannot list functions.projectriff.io at the cluster scope
```
This from deploying the chart w/ `helm install riffrepo/riff --version 0.0.3 --name demo --set create.rbac=true --set httpGateway.service.type=NodePort`

**Comment by trisberg** [comment]
I got one of those for the Function resource too:

```
E0129 14:56:15.627211       1 reflector.go:205] github.com/projectriff/function-controller/pkg/controller/controller.go:105: Failed to list *v1.Function: User "system:serviceaccount:default:demo-riff-sa" cannot list functions.projectriff.io at the cluster scope.: "Unknown user \"system:serviceaccount:default:demo-riff-sa\"" (get functions.projectriff.io)
```

Plus same for Deployments. Definitely looks like the same issue and something we need to address in the function-controller. We might be able to patch up the RBAC definitions to get past it for now.

**Comment by trisberg** [comment]
Published a `0.0.3-rbac` chart version to the `riffrepo` based on the branch with the rbac fix commit https://github.com/projectriff/helm-charts/commit/f165dd56ffee4eba9e463af253fb29c785195a93

**Comment by trisberg** [comment]
Added instructions in Getting-Started - https://github.com/projectriff/riff/blob/master/Getting-Started.adoc#install-riff

**Comment by jldec** [comment]
Also fixed https://projectriff.io/docs/running-on-gke-with-rbac/
