### ISSUE TITLE
Acceptance test suite for function invokers

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#267]
There must be a clear contract between the `function-sidecar` and the `*-function-invoker`s. As the protocol is formalized between the sidecar and invoker (whether based on HTTP, gRPC or something else) we should have confidence that the invoker is correctly invoking functions. An acceptance test suite will make it easier for us to ensure each provided invoker is functioning correctly, as well as third party invokers can ensure their compatibility.

**Comment by dturanski** [comment]
Related to #128 duplicate?

**Comment by scothis** [comment]
Dups #128
