### ISSUE TITLE
move riff system components to monorepo

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#279]
Still struggling with building and testing across repos.

**Comment by ericbottard** [comment]
I think we want to use mono repo that encompasses
- all the main go components
- the helm charts
- the k8s definitions (the current `riff` repo basically)
- the gRPC defs

The invokers should continue to live in their repo

That way, when a change happens to any of those, including in a PR, we should be able to build the components and deploy them as a chart, and correlate a potential failure.

**Comment by jchesterpivotal** [comment]
We'd also want to keep samples centralised. 

Probably CI, but let me think about that a bit -- generally the presence of CI in the monorepo is only tractable if it's a truly mono monorepo. So if invokers are separate, CI ought to be too.

**Comment by ericbottard** [comment]
It's true that changes to components forced us to alter ci in the past. But
then I guess it would advocate for really putting EVERYTHING

Le 14 févr. 2018 4:37 PM, "Jacques Chester" <notifications@github.com> a
écrit :

**Comment by jldec** [comment]
examples
https://github.com/runconduit/conduit
https://github.com/vmware/dispatch
https://github.com/envoyproxy/envoy

**Comment by jchesterpivotal** [comment]
So my reckoning is that we would probably do it in roughly this order:

- Helm charts
- gRPC definitions
- Control / system components
- Invokers

My ordering is based on a gut-feel assessment of easiest to hardest.

**Comment by scothis** [comment]
We did it!
