### ISSUE TITLE
lightweight hello world python sample

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#292]
i like the sentiments python sample function, but we should add a lighter python sample as well for ci and quick idiomatic python demo and experiments.

**Comment by dturanski** [comment]
Depends on update/publish of new python function invokers

**Comment by jldec** [comment]
shipped in 0.0.5
see https://github.com/projectriff/riff/commit/aff04abf09b5a0d086212f1d1b63e974bf18343d#diff-cc76b24c6f3a76f3996ce0ffa30029ae
