### ISSUE TITLE
Headers names should be case insensitive

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#300]
From https://github.com/projectriff/message-transport/issues/8

The headers are currently implemented as a map keyed by a string header name. The map key should be case insensitive to not distinguish between header names like `Content-Type` and `content-type`.

...I'd also be happy to make all header names case sensitive and force the http-gateway to normalize the case of all inbound headers. Either way, we need to be consistent.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
