### ISSUE TITLE
Add a runtime/ python version flag 

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#309]
_From @dturanski on February 22, 2018 14:45_

e.g., `riff create python --python-version=3 ...`   would build with the `python3-function-invoker`. The default should be 3 once the python3-function-invoker is available

_Copied from original issue: projectriff/riff-cli#55_

**Comment by dturanski** [comment]
Also change default protocol to grpc

**Comment by dturanski** [comment]
Closing this because of #370
