### ISSUE TITLE
Normalize FUNCTION_URI directory

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#312]
_From @scothis on February 20, 2018 16:33_

Each function invoker places the function to execute in a different location.

Java: `/functions`

Node: `/functions`

Python: `/`

Shell: `/`

We should always place functions into an empty directory since it's possible the function name could collide with a legitimate file path.

_Copied from original issue: projectriff/riff-cli#50_

**Comment by ericbottard** [comment]
_From @markfisher on February 20, 2018 17:44_

maybe `/riff`?

**Comment by fbiville** [comment]
Not relevant anymore.
