### ISSUE TITLE
Improve error handling for logs

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#314]
_From @trisberg on February 14, 2018 16:8_

Running `riff logs` depends on the transient nature of the pod running the function - we should have better error messages when the pod isn't in a state where the logs are accessible, right now you get stuff like:
```
$ riff logs -n square
Displaying logs for container sidecar of function square in namespace default

exit status 1: error: error executing jsonpath "{.items[0].metadata.name}": array index out of bounds: index 0, length 0

Error exit status 1 - Function square may not be currently active
```

would be nice to eliminate the jsonpath error

_Copied from original issue: projectriff/riff-cli#33_

**Comment by dturanski** [comment]
I think this might be straight forward once #342 is merged.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
