### ISSUE TITLE
Set up public distribution of executables for Mac OS, Linux, Windows

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#315]
_From @dturanski on January 19, 2018 22:16_

Github, brew...

_Copied from original issue: projectriff/riff-cli#8_

**Comment by ericbottard** [comment]
_From @jchesterpivotal on February 14, 2018 15:34_

Github is probably the easiest, insofar as we can use the existing [github release resource](https://github.com/concourse/github-release-resource).

For brew I think we'd be able to do something similar, but with another step or two in the pipeline.

**Comment by fbiville** [comment]
Current PR to get an official Homebrew recipe: https://github.com/Homebrew/homebrew-core/pull/37101.

**Comment by fbiville** [comment]
I've got something working with [Chocolatey](https://chocolatey.org/) as well. It's in a private repository for now.
Let me know if I should create a repo in `projectriff` org (contrary to Homebrew _by default_, Chocolatey package sources live anywhere).

**Comment by fbiville** [comment]
Chocolatey sources are now in https://github.com/projectriff/chocolatey.

**Comment by jldec** [comment]
see also #1143
