### ISSUE TITLE
Support custom templates for function resources and Dockerfile

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#316]
_From @dturanski on January 19, 2018 22:13_

There are hooks OOTB, e.g. `--config string   config file (default is $HOME/.riff.yaml)`  We should probably store path to templates, and potentially other things here

_Copied from original issue: projectriff/riff-cli#4_

**Comment by ericbottard** [comment]
_From @dturanski on January 22, 2018 23:17_

Some initial stories:

* User wants to provide a custom Dockerfile for ,e.g., all <language> functions
* User wants to configure a function container spec for a all <language> functions
* User wants to provide custom Dockerfile for a specific function 
* User wants to configure a function container for a specific function

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
