### ISSUE TITLE
Crash loop until Kafka is available

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#317]
_From @glyn on February 19, 2018 15:55_

Following the riff README on a fresh minikube, I noticed that the http-gateway enters a crash loop until Kafka is available. After 5 restarts it successfully starts. The logs from the failed starts are:
```
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
main.main()
	/go/src/github.com/projectriff/http-gateway/cmd/http-gateway.go:37 +0x3fe

```

It would be better if this behaviour was not visible to users.

@trisberg suggested adding an init-container to poll for Kafka being available.
@ericbottard wondered if the timeout in sarama could be tuned.

_Copied from original issue: projectriff/http-gateway#35_

**Comment by ericbottard** [comment]
I'd start [here](https://github.com/Shopify/sarama/blob/master/config.go#L30-L32)

**Comment by ericbottard** [comment]
_From @glyn on February 19, 2018 16:33_

Another cheap and cheerful option would be to re-order the riff README to deploy kafka/zookeeper before building the riff core components. ;-)

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
