### ISSUE TITLE
Producer error handling improvements

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#318]
_From @glyn on January 30, 2018 13:47_

When a HTTP client drives the `/requests` endpoint and the producer responds with an error before the client has been sent a response:

1. no response is sent to the client, even if that error immediately follows the send, until a 60 second timeout occurs.

2. any diagnostic information associated with the error is not sent to the client. It is sent a 404 with no details of what happened.

It would be better to return an error as soon as the producer responds with an error and to send any diagnostic information associated with the error back to the client. In particular, a 404 means "not found" which may give the impression that the invoked function has been undeployed. A 5xx error may be more suitable.

_Copied from original issue: projectriff/http-gateway#31_

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
