### ISSUE TITLE
Watch for changes to a topic resource

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#319]
_From @trisberg on January 8, 2018 18:44_

If the topic resource is modified we should detect that and recreate the topic reflecting any changes. I tried with changing the partition count tag of a topic and that wasn't reflected in the Kafka topic after the change. In fact I even deleted the topic resource and re-created it with a different partition count. That didn't work either. Seems the Kafka topics aren't removed and we don't rebalance them if they already exists when a topic resource is created (see #3).
  

_Copied from original issue: projectriff/topic-controller#17_

**Comment by ericbottard** [comment]
_From @glyn on February 16, 2018 9:2_

This is the topic analogue of issue https://github.com/projectriff/function-controller/issues/9 and can probably be implemented in a similar way to PR https://github.com/projectriff/function-controller/pull/16.

**Comment by ericbottard** [comment]
The real issue here is not really on the controller/go side, where things are rather easy, but on the Kafka/kazoo side: kazoo doesn't support updating a topic partition count (while raw Kafka theoretically does). 
@trisberg Deletion of topics requires changing the typical server configuration, setting `delete.topic.enable=true` which is not the default AFAIU

**Comment by ericbottard** [comment]
Duplicates #3

**Comment by ericbottard** [comment]
Also, [please note](https://github.com/projectriff/topic-controller/blob/master/glide.yaml#L12-L13) that we were using a [custom version](https://github.com/ericbottard/kazoo-go/commits/topic-management) of kazoo I built (integrating an outstanding PR at the time), but it seems it has been merged since (with even [more commits](https://github.com/wvanbergen/kazoo-go/pull/25/commits))

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
