### ISSUE TITLE
Support topic update (increase nb of partitions)

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#320]
In case one updates a topic Custom Resource (for example, trying to increase the number of partitions), this should be supported by the topic-controller (Kafka does not support decreasing the number of partitions).

Currently blocked by lack of support in kazoo-go

_From @ericbottard on November 8, 2017 9:12_

_Copied from original issue: projectriff/topic-controller#3_

**Comment by markfisher** [comment]
this PR for kazoo looks like it might provide the support we need once merged: https://github.com/wvanbergen/kazoo-go/pull/21/files#diff-cea6e922f9d62318fa7597016a855f2aR420

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
