### ISSUE TITLE
Sidecar panics if function invoker not available

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#323]
_From @dsyer on February 19, 2018 15:43_

Not sure if this is an issue, but it's easy to reproduce: just launch a sidecar and a function invoker on localhost, and then kill the invoker. The sidecar panics and never recovers. Seems like there might be a similar failure mode even in a healthy pod in k8s.

_Copied from original issue: projectriff/function-sidecar#53_

**Comment by jldec** [comment]
invoker healthchecks?

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
