### ISSUE TITLE
Retry limit for function errors?

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#324]
_From @dsyer on February 19, 2018 15:41_

When the sidecar sends a gRPC stream it fails  with a continuous stream of logs (apparently infinite):

```
Error receiving message from function: rpc error: code = Unknown desc =
Error receiving message from function: rpc error: code = Unknown desc =
Error receiving message from function: rpc error: code = Unknown desc =
...
```

The function invoker is failing (but only logging it once, strangely), but the sidecar goes on spitting out empty failure logs forever, and really it has no hope of ever succeeding.

_Copied from original issue: projectriff/function-sidecar#52_

**Comment by dturanski** [comment]
Related to #469

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
