### ISSUE TITLE
terminating container continues to accept input events

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#327]
_From @markfisher on December 12, 2017 21:44_

when the pod enters the terminating state we should be shutting down the consumer then completing in-flight processing, but after a `kubectl delete function ...` command continuing to send events to the function's input topic keeps it active as a consumer even while the pod state shows "terminating".

_Copied from original issue: projectriff/function-sidecar#30_

**Comment by ericbottard** [comment]
_From @jldec on December 14, 2017 14:39_

suggest perhaps moving this to 0.0.3

**Comment by ericbottard** [comment]
_From @markfisher on January 25, 2018 19:29_

not sure if this is happening anymore, but I'm moving to 0.0.4 where we can verify and either fix or close this issue as no longer relevant

**Comment by ericbottard** [comment]
_From @jldec on February 14, 2018 14:19_

moved to 0.0.5 :)

**Comment by ericbottard** [comment]
_From @glyn on February 15, 2018 8:40_

Certainly the behaviour has changed quite a lot since this issue was raised, so I'd vote for closing the issue unless there is evidence it is still a problem.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
