### ISSUE TITLE
Allow health probes

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#328]
_From @ericbottard on October 27, 2017 13:41_

_Copied from original issue: projectriff/function-sidecar#2_

**Comment by ericbottard** [comment]
I'm not sure this is actually a good idea, given how short lived a function pod is. wdyt @markfisher ?

**Comment by ericbottard** [comment]
_From @markfisher on November 23, 2017 16:56_

well, with continuous event streams a function pod can be up for a long time

**Comment by ericbottard** [comment]
True. My point was (but I think we can make it work) that we don't want the probes to mark the sidecar as failing and prevent it from working (but I guess there is nothing that, contrary to _service_ traffic, there is nothing that would prevent the sidecar to do its thing with kafka, as we're fully in control, right?)

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
