### ISSUE TITLE
Make sure generated CLI docs are always up to date

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#352]

**Comment by trisberg** [comment]
should we include the  bash completion file in `etc/bash` as well? Another option is to just remove it since we can just generate it when needed - https://github.com/projectriff/riff/blob/master/Getting-Started.adoc#riff-cli-bash-completion

**Comment by ericbottard** [comment]
Holding off on the completion stuff (as I also want to deal with zsh, although it doesn't work).

BUT, my understanding is that you don't deal with it as a file anyway.
You 
```
source <(riff completion)
```
or tomorrow
```
source <(riff completion [bash|zsh])
```

**Comment by trisberg** [comment]
right, `riff completion` generates a file and I just saved it in `/etc/bash` - we should remove it

**Comment by trisberg** [comment]
the bash completion doesn't work that great either

**Comment by ericbottard** [comment]
Arf, you missed a last minute change I think.
Let's wait for travis to fail (`./riff` instead of `riff`), I'll push a commit afterwards

**Comment by trisberg** [comment]
Oops, I wish git would warn you that there are additional commits.

I added an additional commit using `./$(OUTPUT)` including the same doc changes so still looks good
