### ISSUE TITLE
Configurable propagation of headers

### ISSUE THREAD

**Issue by markfisher** [projectriff/riff#368]
For functions to handle webhooks with HTTP headers, those headers need to be propagated from the HTTP gateway, over the message transport, and to the invokers.

The idea is to make this configurable (on the topic resource?), so that headers can be propagated selectively.

E.g. for [GitHub webhooks](https://developer.github.com/webhooks/securing/) the ` X-Hub-Signature` header contains a hash of the webhook payload, encrypted using a shared secret.

Configuration could be spread across a number of participating components: Topic resource configuration, http-gateway, and function-sidecar. The way an invoker makes headers available to a Function could vary across languages (e.g. in Java we can use the Spring `Message` type).

**Comment by jldec** [comment]
Updated description.

**Comment by jldec** [comment]
Example of go code to validate github webhook:
https://github.com/kelseyhightower/github-webhook/blob/master/main.go#L77

uses
https://github.com/google/go-github/blob/master/github/messages.go#L125

**Comment by ericbottard** [comment]
> (on the topic resource?)

I think one question we should as ourselves is "do we want to keep the `/{topic}` mapping?". Corollary: "Should there always be always a 1-1 mapping from URL path to topic (and hence downstream functions)". Even further: "Can we really expect to control the URL path(s!) at which a caller (say webhook) is going to invoke"

I think the answer is generally "no", so IMHO, we need to introduce an indirection between URL path and topic and hence, the configuration is not to be done at the topic level, but at a new concept (related to the gateway)


Something like 
Gateway = list of Endpoint
Endpoint = 
* Method(s)
* Paths (including `/*`, `/**`, `/{capture}`, etc)
* headers to propagate (by default riff header = http header)
* more generally, how to populate riff headers from `{capture}`, query string, http header


It's clearly more complicated than what you propose, but I think eventually we'll need that

**Comment by jldec** [comment]
for this first implementation (0.0.5) i suggest:
- a configurable whitelist for requests only
- the whitelist is user definable via a configuration string in the topic yaml
- PLUS continue to pass through those headers which we allow today (Accept, Content-Type, others?) 

so for validated GitHub webhooks users would use say "pass-headers: X-Hub-*" on the topic.

**Comment by jldec** [comment]
Here are some more design thoughts

- we don't ever want to pass *all* headers through the http gateway to functions  
   this implies that filtering headers must happen in the gateway, not in sidecars
- for the gateway to get config (like header whitelist) from topics it needs to watch k8s for changes (new, update, delete) to topics
- topic yaml names for the whitelist should not be http-specific
- the whitelist doesn't need to support wildcards in this first release

bonus:
- since the gateway is watching k8s for topics, it can 404 when there are requests on topic names that don't exist or names that are not supposed to be exposed via http.

**Comment by glyn** [comment]
@jldec I don't understand the first bullet. Why will there never be a case where a function needs to receive _all_ the HTTP headers? For example, how about a function which returns the number of HTTP headers in the input request?

Quite separately from whether or not all headers might ever be passed to functions, it seems to me that filtering can occur in the gateway, in the sidecar, between the gateway and the sidecar, or even in the function invoker without any particular issue. What am I missing? :-)

**Comment by jldec** [comment]
@glyn: clarification - this was part of an exercise in looking for an initial solution with less new code.

As an alternative to doing filtering at the getway, we considered doing the filtering ONLY in the sidecars which already do topic-specific work, and therefore could be more easily extended.

In the end I thought it was worth noting that this approach is problematic.

**Comment by ericbottard** [comment]
The sidecar doesn't have access to the k8s API and I think it's best that it stays that way. What we *could* do though, in any case, is to set a header with the list of headers that should be propagated

**Comment by glyn** [comment]
Thanks for the clarification @jldec!

**Comment by jchesterpivotal** [comment]
`function-sidecar` isn't actually filtering headers. That happens at the `http-gateway` and in some of the invokers (eg Node).

The commit I just added allows a user to add a comma-separated `RIFF_HTTP_HEADERS_WHITELIST` environment variable to define which headers to pass through. I don't see this as a quick version that allows users to start tinkering.

**Comment by jldec** [comment]
fixed in #419
