### ISSUE TITLE
Replace $KAFKA_BROKER by $KAFKA_BROKERS

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#379]
Currently, running all the tests requires the Kafka broker(s) to be specified twice, thus:
```
KAFKA_BROKERS=localhost:9092 KAFKA_BROKER=localhost:9092 make test
```

riff should be changed so that it is only necessary to specify `$KAFKA_BROKERS`.

**Comment by scothis** [comment]
Thanks for picking this up @mcowger 

Looks like plural is canonical. The type for `brokers` is an `[]string` https://github.com/projectriff/riff/blob/aabc03d57c09ba49778bcd392b67bc97234e6705/function-controller/cmd/function-controller.go#L49

Where the singular is used, it's later wrapped into an array. https://github.com/projectriff/riff/blob/aabc03d57c09ba49778bcd392b67bc97234e6705/function-sidecar/pkg/carrier/carrier_integration_test.go#L73

**Comment by mcowger** [comment]
Fair enough...thanks.

**Comment by glyn** [comment]
@mcowger Please note that the concourse CI repo [uses](https://github.com/projectriff/ci/blob/a574f549bcdb50c006c4c0e4570e7b1c4490ac9e/tasks/sidecar/build/run#L28) `$KAFKA_BROKER`. One suggestion for how to implement this issue smoothly would be to extend the components of riff that use `$KAFKA_BROKER` to also accept `$KAFKFA_BROKERS` as an alternative spelling and get that PR merged. Then replace `$KAFKA_BROKER` with `$KAFKA_BROKERS` in other repositories (take a look in `github.com/projectriff` for the relevant repos) and get those PRs merged. Then delete the support for `$KAFKA_BROKER` in the riff repo and get that PR merged.

The brute force approach of making the changes in the riff repo and seeing what breaks might be more painful if a little quicker. ;-)

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
