### ISSUE TITLE
Metrics aggregation

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#400]
Rather than emitting a metric every time a message is produced or consumed on an input topic and incurring the overhead of transmitting these metrics to the function controller, it would be more efficient to accumulate them in (small) batches and send some kind of aggregated metrics less frequently.

If the number of metrics accumulated in a batch is allowed to vary, aggregated metrics can be sent in any of the following situations:

- The number of accumulated metrics reaches a defined batch size.
- A timeout is reached and there is at least one accumulated metric waiting to be sent.
- (For consumer metrics) When the consumer receives its first message since either the consumer initialised or a defined time period has passed since the last aggregated metric was sent.

Aggregating metrics avoid problems of clock skew if they deal in durations rather than absolute times.

- [ ] Emit aggregated metrics
- [ ] Update the autoscaler to use aggregated metrics
- [ ] Carry true function consumption rates across scaling operations

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
