### ISSUE TITLE
Update samples with instructions to install an invoker

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#429]
Now that riff ships invoker-less, each sample should include the invoker that needs to be installed as a prerequisite.

**Comment by trisberg** [comment]
Should we also move the samples to the respective invoker project?

**Comment by scothis** [comment]
I'd rather move them to https://github.com/projectriff-samples

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
