### ISSUE TITLE
Auto-install command invoker

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#436]
After installing riff users should have at least one working invoker.

This includes:

- adding invoker code 

- updating CLI descriptions to refer to a command rather than node example

- updating Helm chart to install the invoker - investigate using two charts, one for the CRDs and one for the rest, also investigate using a post-install hook to create the invoker after the CRD has been created

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
