### ISSUE TITLE
Logs in function pod obscured by DNS noise

### ISSUE THREAD

**Issue by dsyer** [projectriff/riff#440]
When I kail a function these days I get mostly noise like this:

```
default/http-7fbd558f95-sl8zk[main]: 2018-03-23T10:24:59+0000 [stdout#info] A query: b'play.google.com'
default/http-7fbd558f95-sl8zk[main]: 2018-03-23T10:24:59+0000 [stdout#info] Result for b'play.google.com' is ['64.233.191.102', '64.233.191.113', '64.233.191.100', '64.233.191.101', '64.233.191.138', '64.233.191.139']
default/http-7fbd558f95-sl8zk[main]: 2018-03-23T10:25:22+0000 [stdout#info] A query: b'beacons.gcp.gvt2.com'
default/http-7fbd558f95-sl8zk[main]: 2018-03-23T10:25:22+0000 [stdout#info] Result for b'beacons.gcp.gvt2.com' is ['108.177.112.94']
```

it's distracting and doesn't seem to add much of interest to a function operator / author.

**Comment by scothis** [comment]
@dsyer are those not the logs from your function? The `[main]` container should be your function's stdout. 

Looking for that pattern it appears to be related to telepresence. https://gist.github.com/sha1sum/0bb563dab8189153a454478d392962e8

**Comment by dsyer** [comment]
Yes. It's telepresence. I guess that's nothing to do with riff, however annoying it is.
