### ISSUE TITLE
Imperative option to cancel a function invocation

### ISSUE THREAD

**Issue by dsyer** [projectriff/riff#441]
A function invocation can run forever (if the idle timeout is long enough). The only option for the user right now is to delete the whole deployment. It would be nice to be able to pre-emptively scale to 0. Related, but maybe not quite the same: there no point scaling to 0 if the kafka topic is full of garbage. You also need to clear the topic or reset the pointer so the next invocation doesn't get flooded with errors.

**Comment by markfisher** [comment]
the notion of control-plane is starting to seem necessary... would be useful for this case as well

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
