### ISSUE TITLE
Router pattern: sidecar or function directs message to different topic

### ISSUE THREAD

**Issue by dsyer** [projectriff/riff#443]
Having a single downstream topic is kind of limiting for a lot of integration flows. The router pattern is well known, and would fit into riff maybe as a `Function<Message<?>,String>`. But how can the sidecar know that the function is in the right form? What if it starts getting multiple outputs for a single input? It might be better, or at least a useful option to have, to implement routing behaviour as a sidecar feature. E.g.look at the outgoing messages for a header with a well-known name ("routekey") and send the message to the corresponding topic.

Draft: https://github.com/dsyer/riff/tree/feature/routekey

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
