### ISSUE TITLE
spike: explore options for schema on a Topic resource

### ISSUE THREAD

**Issue by markfisher** [projectriff/riff#446]
as part of this effort, we should evaluate whether the Spring Cloud Stream schema (and registry) approach is also relevant for riff (would facilitate interop with Spring Cloud Data Flow):
https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#schema-evolution

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
