### ISSUE TITLE
CLI file matcher should respect explicit 'riff create <invoker>' 

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#448]
This is related to https://github.com/projectriff/command-function-invoker/issues/10 but applies to the riff CLI in general, not just the command invoker.

After installing the [command function invoker yaml](https://github.com/projectriff/command-function-invoker/blob/master/command-invoker.yaml), all matchers stop working when used with `riff create` or `riff init`.

**Suggestion:** Specifying an invoker explicitly with say `riff create node` or `riff init node` should force matching on just node-invoker file extensions, and is more consistent and easier than using `--artifact` which might still be ambiguous across invokers.

**Comment by scothis** [comment]
This was the intended behavior, will look into why it's not matching correctly.
