### ISSUE TITLE
Simplify workflow with image digests or auto-tagging build iterations

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#450]
Developers need a smooth workflow for iterating on function images when building and pushing updates to a container registry e.g. to deploy updates to a hosted cluster.

Today, each build image has to be tagged with a unique tag (e.g. using `riff build -v x.x.x --push`) and then the same x.x.x tag also has to be applied to the function spec.container.image (e.g. by hand-editing the function yaml and then running `riff apply`.)

How about `riff build --digest --push --apply` 

- `--digest` captures the [image digest](https://docs.docker.com/engine/reference/commandline/images/) from the docker build and updates the function yaml
- `--push` calls docker push
- `--apply` applies the updated function yaml

**Comment by jldec** [comment]
Discussing with @markfisher, an alternative to modifying image digests/tags on every build would be to decouple builds from functions using separate resources. The build CRD controller could then be configured to automate lookup of the most-recent build-sha (or lock to a specific build/tag)

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
