### ISSUE TITLE
extend stream semantics to all invokers 

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#462]
- [ ] command invoker
- [x] go invoker
- [x] java invoker
- [x] node invoker
- [x] python3 invoker

~~python2 invoker~~

**Comment by dturanski** [comment]
I'm not sure we should do this for python2. I'm working on python3

**Comment by jldec** [comment]
updated OP to remove python2

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
