### ISSUE TITLE
function-sidecar loops forever on "Internal" gRPC error

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#469]
@dsyer [found](https://pivotal.slack.com/archives/C78E98VNJ/p1522143697000143) that the gRPC dispatcher can get into a loop reporting  an `Internal` gRPC error code:
```
2018/03/27 10:36:44 Error receiving message from function: rpc error: code = Internal desc = 
2018/03/27 10:36:44 Error receiving message from function: rpc error: code = Internal desc = 
2018/03/27 10:36:44 Error receiving message from function: rpc error: code = Internal desc = 
2018/03/27 10:36:44 Error receiving message from function: rpc error: code = Internal desc = 
2018/03/27 10:36:44 Error receiving message from function: rpc error: code = Internal desc = 
2018/03/27 10:36:44 Error receiving message from function: rpc error: code = Internal desc = 
```
Such an `Internal` error should [terminate](https://github.com/projectriff/riff/blob/ca1bb9e24273b009684939c0d489003faacf0e13/function-sidecar/pkg/dispatcher/grpc/grpc.go#L77) the gRPC dispatcher's `handleIncoming` loop.

A suggested fix is to detect the Internal gRPC error in the `streamClosureDiagnosed` function ([here](https://github.com/projectriff/riff/blob/ca1bb9e24273b009684939c0d489003faacf0e13/function-sidecar/pkg/dispatcher/grpc/grpc.go#L88)) and return `true`.

Note that `Internal` corresponds to error code 13.

**Comment by dturanski** [comment]
I get the same for coding errors

```
Error receiving message from function: rpc error: code = Unknown desc = Exception iterating responses: name 'logging' is not defined
```

Perhaps it's better to detect if we get the same error repeatedly

**Comment by glyn** [comment]
@dturanski Tempting, but that would also terminate the gRPC dispatcher's `handleIncoming` loop if a transient error occurred multiple times in succession.

**Comment by dturanski** [comment]
@glyn I thought about that, but trying to think of a reasonable scenario.  Since a variety of errors identify as `Unknown` a simple filter is insufficient.  Maybe some configurable strategy, e.g., in the example above, the function performs a simple calculation and performs a single value.  I would be happy to shut it down if I detect any type of multiple errors.  In a a more complex (streaming) situation, I may expect this behavior, but may want an error rate threshold.

**Comment by glyn** [comment]
Ok.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
