### ISSUE TITLE
support bounding of streams at the sidecar

### ISSUE THREAD

**Issue by markfisher** [projectriff/riff#471]
this could be controlled by declarative configuration for generic windowing based on time, number-of-events, etc. as provided per-function resource

the sidecar would then invoke the gRPC streaming service once per window (as opposed to once-only at startup as it is for an unbounded stream)

we might want to consider whether request/reply should be treated as a window of 1, or otherwise we should revisit the idea of a separate request-reply service alongside the stream-stream service

**Comment by jldec** [comment]
See https://github.com/projectriff/riff/commit/8efed627f7c2b68e325f8ecb885585f5ba38bfd1
