### ISSUE TITLE
Java protobuf generated classes not being published for releases

### ISSUE THREAD

**Issue by dsyer** [projectriff/riff#473]
There is a `<distributionManagement/>` in the pom but it points to sonatype repos and I don't expect we have permission to deploy there (there are no riff protobuff releases in Maven Central). We should either switch that on or move it to repo.spring.io or something. I see up to 0.0.2 in repo.spring.io (https://repo.spring.io/libs-milestone-local/io/projectriff/function-proto/).

**Comment by trisberg** [comment]
There were no changes after the 0.0.4 release, so we didn't release the 0.0.5 bits. here are the currently available versions: https://repo.spring.io/libs-milestone-local/io/projectriff/riff-function-proto/

**Comment by trisberg** [comment]
We haven't used the `<distributionManagement/>`, think that's fairly new. I just uploaded the releases to the milestone repo manually as part of the release process. We probably should change to use `repo.spring.io` for the distribution going forward so we can automate the release.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
