### ISSUE TITLE
Make timeout for "riff publish" configurable

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#482]

**Comment by cpage-pivotal** [comment]
Use case is data scientists running (Python) workloads that they want to schedule in concurrent bursts. Need to let long-running routines run to completion and get the results.

**Comment by markfisher** [comment]
Just a thought, but if we were to add support for fire-and-forget POST with either a URL in the response header or accepting a webhook URL for a response notification, would one of those options be even better for the particular use-case?

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
