### ISSUE TITLE
Are topics cluster scoped?

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#485]
The Topic CRD is namespaces scoped, but topics in Kafka and function inputs/outputs are essentially cluster scoped. The k8s resource should either become cluster scoped, or the k8s namespace should be reflected in the topic name in the broker and function bindings.

**Comment by markfisher** [comment]
I think Topics should be cluster-scoped, at least for now. They should only remain namespaced if we intend to enforce scoped bindings.

**Comment by trisberg** [comment]
Then we would need to separate the management of the topics resources from functions more, was mentioned here in #459 as well

**Comment by ericbottard** [comment]
In effect they are, but I think this is yet another topic (ah ah) for which we'll need to sit at the virtual table and re-discuss:
- if topics are clusterscoped, given that several functions can be bound to a topic, and assuming namespacing eventually implies access rules, how can I inject an event for my function F_eric and make sure I won't mess with F_mark (which I don't even konw exists) that is bound on the same topic?
- if topics are namespaced, then we must at the minimum (if we want to keep a single Kafka and a single GW)
  1. change the GW paths to include something that maps to the namespace eg `http://server/{namespace}/{topic}`
  2. internally post to kafka topics named eg `{namespace}/{topic}`

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
