### ISSUE TITLE
init requires -f <dir> - inconsistent with create 

### ISSUE THREAD

**Issue by dturanski** [projectriff/riff#488]
Currently `init` requires `-f <dir>` and does not interpret the arg as a directory path as create does.  Need to add `utils.AliasFlagToSoleArg("filepath")` for init.  Also test that the path does not collide with an invoker name.

**Comment by scothis** [comment]
It's safer to always include the flag. While commands are greedy and will be matched before arguments, if your path happens to collide with an invoker that's installed you could get a surprise when the command starts to fail.

**Comment by ericbottard** [comment]
Then we need to remove that behavior from `create` IIUC

**Comment by ericbottard** [comment]
Note that if we do https://github.com/projectriff/riff/issues/502, then there won't be any ambiguity as `riff init` and `riff create` (w/o an invoker) will be gone

**Comment by scothis** [comment]
`riff create` is picking up this behavior from the `build` command argument. We can add the same first-arg-to-filepath mapping for the `init` command to make the behavior consistent between `init` and `create`.
