### ISSUE TITLE
Unable to install with projectriff/kafka instance.

### ISSUE THREAD

**Issue by mcowger** [projectriff/riff#496]
I have a cluster thats empty and healthy:

```
[ec2-user@ip-10-0-0-28 ~]$ kubectl get -n riff-system all
No resources found.
```

install the single node kafka (` helm install --name riff-kafka --namespace riff-system projectriff/kafka`)and confirm its running

```
NAME                                    READY     STATUS    RESTARTS   AGE
riff-kafka-kafka-5f96b558bc-d5zwq       1/1       Running   0          1m
riff-kafka-zookeeper-56dd5fd86d-h4nvs   1/1       Running   0          1m
```
Then install riff per the GettingStarted docs (`helm install projectriff/riff --name projectriff --namespace riff-system --set kafka.create=true --set rbac.create=false`)

The HTTP gateway and topic controllers never successfully start:
```
[ec2-user@ip-10-0-0-28 ~]$ kubectl get -n riff-system po
NAME                                                   READY     STATUS             RESTARTS   AGE
projectriff-riff-function-controller-b4849f776-dmsfq   1/1       Running            0          31s
projectriff-riff-http-gateway-7dbdc9cd48-29hs8         0/1       CrashLoopBackOff   2          31s
projectriff-riff-topic-controller-8567cc4d66-shz2d     0/1       CrashLoopBackOff   2          31s
riff-kafka-kafka-5f96b558bc-d5zwq                      1/1       Running            0          3m
riff-kafka-zookeeper-56dd5fd86d-h4nvs                  1/1       Running            0          3m
```

With logs that look like this:

```
[ec2-user@ip-10-0-0-28 ~]$ kubectl logs  -n riff-system projectriff-riff-http-gateway-7dbdc9cd48-29hs8
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
main.main()
        /go/src/github.com/projectriff/riff/http-gateway/cmd/http-gateway.go:37 +0x3fe
```

Is this a doc error for the getting started, or something more?

**Comment by mcowger** [comment]
Upon further review - it appears that the issue is the name of the kafka install *has* to be `transport`.

```
[ec2-user@ip-10-0-0-28 ~]$ kubectl get -n riff-system po
NAME                                                   READY     STATUS    RESTARTS   AGE
projectriff-riff-function-controller-b4849f776-4thxr   1/1       Running   0          45s
projectriff-riff-http-gateway-7dbdc9cd48-bzbq4         1/1       Running   0          45s
projectriff-riff-topic-controller-8567cc4d66-dqkrf     1/1       Running   0          45s
transport-kafka-5bcbd48cf-zskqj                        1/1       Running   0          1m
transport-zookeeper-659c7cf898-l9m5k                   1/1       Running   0          1m
```

I'll fix the doc and send a PR.

**Comment by scothis** [comment]
@mcowger We just made a change just now to this behavior so that Kafka is installed via the projectriff chart. You should no longer need to install Kafka separately. It looks like you may have caught the small window between the PR being merged to master and the updated helm chart being available via our repository.

Try again and let us know how it goes.

Sorry about that.

**Comment by trisberg** [comment]
We are in the middle of a change to the Helm chart and the docs for the next 0.0.6 release so the GettingStarted doesn't reflect the current 0.0.5 release. 

If you want to install version 0.0.5 then follow https://github.com/projectriff/riff/blob/v0.0.5/Getting-Started.adoc  

If you want to install the current 0.0.6-snapshot version then follow https://github.com/projectriff/riff/blob/master/Development-Helm-install.adoc

**Comment by mcowger** [comment]
Indeed it does look like I hit that window :).

Using the Development instructions I was able to deploy correctly.   Feel free to drop the PR associated with this.

**Comment by trisberg** [comment]
I noticed the `helm delete --purge` command used the wrong release name, fixed that to be `projectriff` in master now. Thanks for trying riff, just be aware that if you use the latest snapshot versions things could occasionally break.
