### ISSUE TITLE
The Getting-Started guide doesn't work with current release (0.0.5)

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#499]
If someone follows the instructions in master they will not get a working riff install since the docs depend on new features that will be in 0.0.6 while the `helm install` command will pull the 0.0.5 chart.

We can:

- [x] Revert the Getting-Started guide to a version that works with chart version 0.0.5 (current release)
- [x] Create a PR for updating the Getting-Started guide to the 0.0.6 instructions 
- [x] Add additional commits for the `Getting-Started.adoc` to the `trisberg-issue-499-doc-for-006` branch.
- [x] Merge that [PR](https://github.com/projectriff/riff/pull/501) just before the next release

**Comment by scothis** [comment]
The getting started guide in the repo should always be accurate for the content of the current commit (or as close as practical). For the last stable release we should refer people to the website.

**Comment by trisberg** [comment]
Since it relies on published Helm chart it shouldn't be updated until we are ready for the release and that chart is available, otherwise someone stumbling on our docs could have a sub-par first experience like we saw.

**Comment by scothis** [comment]
We also publish snapshot helm charts where the new docs are relevent. In general, we need to be more clear about whether the docs are targeting a stable release or the current content of the repo.

**Comment by trisberg** [comment]
The Gettting-Started guide only references released version and no snapshots (no --devel flag used). That part is in the Development-Helm-install doc which now works for 0.0.6-snapshots and is current.
