### ISSUE TITLE
Require invoker name for 'riff create' and 'riff init' and clarify usage in help

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#502]
The CLI UX would be simpler if an invoker parameter were required for all `riff create <invoker>` and `riff init <invoker>` commands. If no invoker is specified, display a usage error and the list of registered invokers.

this is a followup to #448 

1. Auto-detecting invokers from file extensions introduces non-determinism. E.g. adding new invokers could break old workflows by stealing the extension. This is true even when pointing to a source file with --artifact.

2. The current command-invoker already makes it necessary _always_ to disambiguate, because it matches *. 

3. It's often eaiser to specify an invoker than point to an "artifact" file (invoker names are short).

4. with this approach we could even auto-generate the source file when there are no files at all in the directory. E.g. `riff create node --stream`

**Comment by ericbottard** [comment]
If we go through with this, this is a matter of completely removing the `riff create` and `riff init` commands and have only the (currently) sub-commands.

This would simplify the codebase for sure.

I am in favor of it, as I agree users know they want to create a "java" function for example, when they have a `.jar` file at hand

**Comment by jldec** [comment]
see also #517

**Comment by scothis** [comment]
#518 only address the doc part of this issue
