### ISSUE TITLE
concat example stuck at 

### ISSUE THREAD

**Issue by FabioChiodini** [projectriff/riff#503]
Hi

the concat examples gets deployed effectively (https://github.com/projectriff/riff/tree/master/samples/python/concat) but when you use the riff publish line listed in the readme the function is not able to execute as the containers creation gets stuck at:

NAME                      READY     STATUS             RESTARTS   AGE
concat-77db889cd4-s8zhr   0/2       ImagePullBackOff   12         54m

Is there something that got moved?

thank you very much.

F.

**Comment by FabioChiodini** [comment]
I make this more clear (hopefully). It seems that in some examples the riff docker push fails while in other examples works, If I manually push the docker image just after issuing the riff create command then the image pull succeeds:

<img width="916" alt="riff hack" src="https://user-images.githubusercontent.com/8775225/38375539-c175ca30-38f6-11e8-8a3d-1c0b79a34e08.png">

**Comment by dturanski** [comment]
The sample has been moved to https://github.com/projectriff/python3-function-invoker/tree/master/samples/concat.  

I cannot reproduce this after cleaning out my local docker repository.  If you are running minikube, you need to `eval $(minikube docker-env)` .   Feel free to reopen if you think this is still an issue.
