### ISSUE TITLE
Function-controller error reading partitions when function has no input topic

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#504]
- Apply a function with no input topic name (delete or set `input:` to blank in the function yaml)
- The function will not be triggerable (as expected), and the function-controller emit the following error message to its log every 100ms.

> Error reading partitions for topic : kafka server: The request attempted to perform an operation on an invalid topic.

- Restarting the function controller will not fix the problem

**Comment by markfisher** [comment]
if possible to use 1.9 as a baseline, we could add validation: https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#validation

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
