### ISSUE TITLE
Move docs not specifically about developing riff to projectriff.io

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#525]
Docs in this repo are currently pulling double duty between how to develop riff and how to run a release of riff. This leads to confusion when changes happen. Docs in this repo should only be related to developing riff and running the latest snapshot builds. All docs related to ruining the latest release should move to projectriff.io.

**Comment by trisberg** [comment]
Yes, let's separate these. 

Although not sure we need docs on "ruining the latest release", we know how to do that already ;)
