### ISSUE TITLE
"riff delete --all" should not fail if topic is not found

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#530]
If I delete a function where the topic `test` was already deleted using the "--all" option, I don't get an error and the function is not deleted. All I see is:

```
$ riff delete -n uppercase --all
Deleting topics.projectriff.io test:

```

This scenario can easily happen when I chain foo and bar with a shared topic and then delete both using the "--all" option.

**Comment by ericbottard** [comment]
I think another question we should ask ourselves first is "should it be possible to end up in this scenario", ie "should we allow deletion of topics that are bound to functions"?
