### ISSUE TITLE
function-sidecar should not pass correlationId over HTTP

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#531]
HTTP is inherently request-reply. By passing the correlationId as part of the HTTP request and expecting it to come back in the response, we are pushing a concern to the function-invoker that can be handled within the function-sidecar.

Instead of propagating the correlationId in the HTTP request, the value should be captured, and set on the output message created from the HTTP response.

**Comment by scothis** [comment]
Digging a little deeper, the sidecar sends the `correctionId` on every HTTP request and sets the id on the response automatically. The invoker can safely ignore the correctionId.

**Comment by dturanski** [comment]
it's currently used in http-gateway to match kafka request and reply messages
