### ISSUE TITLE
http-gateway fails with 404 if function doesn't reply

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#533]
If a function is failing and never returns a reply the error coming back from the http-gateway is 404:

```
$ riff publish -i my-flux -d '1' -r
Posting to http://127.0.0.1:30930/requests/my-flux
HTTP Gateway responded with code 404:
```

This is confusing, we should use "502 Bad Gateway" or "504 Gateway Timeout"

**Comment by scothis** [comment]
504 👍
