### ISSUE TITLE
riff CLI should check its version and component versions

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#536]
The versions should be compatible, CLI version should be >= controller versions

**Comment by jldec** [comment]
I also suggest that if we can't get the version stamped into the build, we should discourage the use of `go get` to install the CLI. (see [main readme](https://github.com/projectriff/riff#get-the-main-riff-repo-and-install-the-cli) and [docs](https://projectriff.io/docs/getting-started-on-minikube/#install-the-current-riff-cli-tool)). 

Would it be possible to add a Makefile target for the cli which also copies the build to the go/bin ?

The [cli folder readme](https://github.com/projectriff/riff/tree/master/riff-cli) needs cleanup also - the instructions there build the old cli in projectriff-archive.

**Comment by ericbottard** [comment]
> Would it be possible to add a Makefile target for the cli which also copies the build to go/bin ?

Yes, that's what `go install <package>` does (instead of just `go build`)

**Comment by jldec** [comment]
How do we set the VERSION of the build like the [Makefile](https://github.com/projectriff/riff/blob/master/riff-cli/Makefile) does?

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
