### ISSUE TITLE
Documentation in Function-Invokers.adoc is out of date

### ISSUE THREAD

**Issue by dsyer** [projectriff/riff#545]
It says you can run the http-gateway locally by just setting `KAFKA_BROKERS`, but that appears to be false now:

```
$ go run cmd/http-gateway.go
panic: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

goroutine 1 [running]:
main.main()
	/home/dsyer/dev/go/src/github.com/projectriff/riff/http-gateway/cmd/http-gateway.go:60 +0x4f6
```

**Comment by dsyer** [comment]
See #546 for a change that restores the old behaviour without changing it in k8s

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
