### ISSUE TITLE
riff-cli should not assume localhost when http-gateway is NodePort type

### ISSUE THREAD

**Issue by markfisher** [projectriff/riff#547]

**Comment by trisberg** [comment]
I don't think it does, AFAIK it only assumes localhost if it can't get the minikube url when http-gateway uses NodePort

**Comment by markfisher** [comment]
This was actually observed on a remote cluster environment that was using NodePort, but this probably just reiterates the fact that we need to use ingress instead of exposing the http-gateway service directly.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
