### ISSUE TITLE
Support for accept header in publish command

### ISSUE THREAD

**Issue by vijaynalawade** [projectriff/riff#554]
I was playing with Go Invoker.
Like --content-type, there should be way to specify accept type (--accept) which is useful when JSON reply is expected.
Due to lack of it, message conversion failed at side car when main container returned JSON object. 
As a workaround, I had to convert JSON object into string before returning from the handler function.

**Comment by scothis** [comment]
Yes. I found myself wanting the same capability yesterday, and for the same reason.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
