### ISSUE TITLE
`riff install` command to install riff into a clean k8s cluster

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#559]
Even with a significant investment into the getting started guides, installing riff is still more complex than it should be. The riff-cli could offer an `install` command that checks prerequisites and installs riff into a cluster.

We can wait for the helm tiller to become available, pick a default message transport, detect if rbac is needed and offer to install invokers. Under the hood we continue to use helm and the published helm charts.

**Comment by trisberg** [comment]
you can't detect if rbac is needed, at least not in any reliable way that I have found

**Comment by scothis** [comment]
> you can't detect if rbac is needed, at least not in any reliable way that I have found

Worst case it installs, detects the error, backs out the install and installs again with the correct config.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
