### ISSUE TITLE
Extend simulator to account for warmth ladder

### ISSUE THREAD

**Issue by jchesterpivotal** [projectriff/riff#587]
Control loop behaviour is deeply affected by delays and lags. The principal lag in our system is startup time for functions.

We currently model this as a single delay for all startups. However, startup time is not constant. As systems become progressively "warmer", the time to startup changes. Worse, this warming curve is affected by the number of available worker nodes.

This issue introduces two new requirements for the autoscaler.

1. Distinguish between levels of the warmth ladder: cold start, disk-warm, memory-warm and CPU-warm.
2. Model how instances "move" from one warmth level to another over the lifetime of the simulation.

Out of scope but ideal for followup issues:

* Allowing the simulation to show behaviour on small and large worker clusters (more nodes means average temperature will be lower)
* Show behaviour of chained functions

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
