### ISSUE TITLE
Document HTTP Gateway usage

### ISSUE THREAD

**Issue by odedia** [projectriff/riff#588]
Sorry if this already exists, couldn't find it.

Using riff cli I can pass parameters such as --data and --reply, however I don't really know how to invoke the same call from the REST API. I would like to issue a call from the browser, for example something like this:

`http://127.0.0.1:32331/messages/numbers?data=10&reply=true
`

If something similar already exists (perhaps by providing the data in the body?), would appreciate some documentation on this. That would make testing through tools like POSTman+Newman a breeze. 

Thanks.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
