### ISSUE TITLE
riff publish fails with 504 Gateway Timeout in minikube

### ISSUE THREAD

**Issue by samaitra** [projectriff/riff#610]
Steps followed 

To start minikube
minikube start --memory=4096

To build images with docker in minikube use

eval $(minikube docker-env)

Get the main riff repo and install the CLI

go get github.com/projectriff/riff

Build the riff core components

cd $(go env GOPATH)/src/github.com/projectriff/riff
make dockerize

Setup for development
make dev-setup

Create and run sample 
cd fn
./gradlew build

Install java invokers
riff invokers apply -f https://github.com/projectriff/java-function-invoker/raw/master/java-invoker.yaml

create the function and its input topic
riff create java --artifact build/libs/fn-1.0-SNAPSHOT.jar --handler functions.Hello --input words

publish a message and wait for a reply
riff publish --input words --data mydata --reply

Observing error as below 

```
Posting to http://192.168.99.100:32068/requests/words
HTTP Gateway responded with code 504: Gateway Timeout
```
I also observed that docker images are published in local docker daemon not in minikube docker daemon.

**Comment by trisberg** [comment]
If you open a new shell you would have to run the `eval $(minikube docker-env)` in the new shell as well, been there done that ...

Could you try this again, making sure the images build in the minikube's docker env. If that doesn't work then there is something else wrong and we'd have to investigate further.

**Comment by samaitra** [comment]
@trisberg yes I have set eval $(minikube docker-env) in the new shell but yet the image was not published in minikube docker.

Also I can see the following docker env values are configured with `$(minikube docker-env)`

DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_CERT_PATH=/Users/<USER_NAME>/.minikube/certs
DOCKER_API_VERSION=1.23

**Comment by trisberg** [comment]
That should work.

What does `riff version` return?

**Comment by ipolyzos** [comment]
Hi @trisberg, 

 I have the very same issue as well with the latest release. 

 Running on a MacOS.  And the riff version output for me is : 

> $ riff version
> riff CLI version: Unknown
> kubeconfig current-context: minikube
> 
> COMPONENT             IMAGE
> function-controller   projectriff/function-controller:0.0.7
> http-gateway          projectriff/http-gateway:0.0.7
> topic-controller      projectriff/topic-controller:0.0.7
> 
> INVOKER   VERSION
> command   0.0.7-snapshot
> go        0.0.3
> java      0.0.7
> node      0.0.9-snapshot
> python3   0.0.6

**Comment by trisberg** [comment]
@ipolyzos could you try using the release version of the CLI - https://github.com/projectriff/riff/releases/tag/v0.0.7

**Comment by ipolyzos** [comment]
@trisberg this deployment was with the latest release, following the instructions on [getting-started-on-minikube/](https://projectriff.io/docs/getting-started-on-minikube/). I have also attempted the 0.0.6 but was failing with 404. The only working attempt so far was the 0.0.5 release.

**Comment by samaitra** [comment]
@trisberg the riff version I am using is as follows

$ riff version
riff CLI version: 0.0.7-snapshot
kubeconfig current-context: minikube

COMPONENT             IMAGE
function-controller   projectriff/function-controller:0.0.8-snapshot
http-gateway          projectriff/http-gateway:0.0.8-snapshot
topic-controller      projectriff/topic-controller:0.0.8-snapshot

INVOKER   VERSION
java      0.0.8-snapshot

**Comment by trisberg** [comment]
@samaitra looks like your CLI version is off. Since you built a recent snapshot version of the components you should use a CLI built with the same version. 

You can build the CLI with `make -C riff-cli/ build` and then copy the binary `riff-cli/riff` to whatever location `which riff` points to.

You also need to rebuild the function resources, just add a `--force` option to your `riff create` command.

Hopefully this resolves your issues.
