### ISSUE TITLE
make leaves untracked files in vendor directory

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#617]
It appears that dep version 0.4.1 (e.g. installed by homebrew) exhibits this behaviour whereas the current HEAD version of dep does not.

### Workaround
```
brew uninstall --force dep && go get -u github.com/golang/dep/cmd/dep
```

### Steps to reproduce
1. brew install dep
2. Ensure that homebrew version is picked up. `dep version` should report v0.4.1.
3. cd to the riff directory
4. issue `make`
5. issue `git status` and observe untracked files

**Comment by fbiville** [comment]
Not reproduced with latest `dep` version (a.k.a. `v0.5.0`).
