### ISSUE TITLE
Favor Route and Configuration to Service

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#619]
Services are a more user friendly concept that in turn creates Configurations and Routes. Unlike working with Configurations and Routes directly, using a Service significantly limits the functionality of the Route. A Service can configure either a Route running the latest Revision, or a single specific Revision. A Route on the other hand can use traffic rules to manage traffic to multiple revisions as a canary or a blue/green deployment.

**Comment by scothis** [comment]
This is done in projectriff/system. The Handler resource decomposes to Route and Configuration bypassing Service.
