### ISSUE TITLE
Expose Bus/ClusterBus key-value parameters for Channels and Subscriptions

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#620]
Buses can expose parameters that a Channel or Subscription may provide a value for, or the Channel may be required to provide a value. Before creating a Channel or Subscription, the bus resource should be resolved and and the params inspected. Params without a default must be provided, value that are not defined by the bus should be ignored.

**Comment by scothis** [comment]
We no longer use Knative Eventing.
