### ISSUE TITLE
consider alternatives to "system" for install command

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#622]
_From @markfisher on July 20, 2018 20:20_

possibly "platform"

other ideas?

**Comment by ericbottard** [comment]
_From @glyn on July 23, 2018 11:4_

How about "eventing"? We _might_ want to be able to install just "serving" in the future given that the riff CLI supports non-eventing services quite well.

**Comment by scothis** [comment]
Install is now managed by https://github.com/projectriff/cnab-riff
