### ISSUE TITLE
--verbose mode for`riff function create`

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#623]
_From @jldec on July 23, 2018 14:6_

Users should have observability during function builds, and error notification for `riff function create`. 

I have already bumped up against this for two different situations

1. misconfigured push secret (probably the most common gotcha making our quickstart not quick and not start)

2. when network is not great kaniko will take 5 minutes or longer to upack the node invoker image layers - it does not use cached images.

### proposed solution.
- if --verbose is set, block return from `riff function create...`
- lookup the init containers in the build pod
- while each is busy, stream the logs for that container on stdout
- bail out if one of the containers exits with error code
- or finish with with happy success message.

I have been doing the above manually mostly for the build-and-push container which is where both the above issues will bite. E.g.
```
kubectl logs -f square-00001-hl5k4 -c build-step-build-and-push
```

**Comment by trisberg** [comment]
unfortunately it takes for ever to pull the build creds-init and git-init images (they are ~2.4 GB) and therefore there could be no visual feedback for several minutes, should we add a loop adding dots to a `waiting for image pull ...` message while we are waiting for the actual build to start ...

**Comment by scothis** [comment]
The build image size is being tracked at https://github.com/knative/build/issues/179. The image pull delay is annoying in GKE, it's intolerable in minikube.

**Comment by glyn** [comment]
# Implementation notes

- See kubectl's [logging code](https://github.com/kubernetes/kubernetes/blob/94c2c6c8423d722f436305cd67ef515a8800d723/pkg/kubectl/polymorphichelpers/logsforobject.go)

**Comment by glyn** [comment]
Feedback from @jldec:
> i was expecting just build container logs - not sure if including autoscaler and other sidecars is quite right
