### ISSUE TITLE
Provide bus commands

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#624]
_From @glyn on July 23, 2018 11:37_

Currently there is no way in the cli to create or destroy a bus or to list buses.

Namespaced buses should be a developer's concern and hence appropriate for the CLI.

It is not clear that cluster buses -- which could be deemed to be an operator's concern -- should be created/destroyed using the CLI, although it would be useful for a developer to be able to list them to see what's available.

**Comment by scothis** [comment]
We no longer use Knative Eventing
