### ISSUE TITLE
posting function to riff with knative (using the minikube getting started guide) fails

### ISSUE THREAD

**Issue by odedia** [projectriff/riff#629]
Tried to deploy a function to a knative environment using the guide at https://projectriff.io/docs/getting-started-with-knative-riff-on-minikube/

It is failing on the last "riff function" command:

```
$ riff function create node square \
>   --git-repo https://github.com/trisberg/node-fun-square.git \
>   --artifact square.js \
>   --image $DOCKER_ID/node-fun-square
Error: Post https://localhost:6443/apis/serving.knative.dev/v1alpha1/namespaces/default/services: dial tcp [::1]:6443: connect: connection refused

```
I am watching the cluster using `watch kubectl get pod --all-namespaces` and all containers appear to be up and running.

The KNative documentation suggests to create an IP address to use for communicating using the following command:

`export IP_ADDRESS=$(kubectl get node  -o 'jsonpath={.items[0].status.addresses[0].address}'):$(kubectl get svc knative-ingressgateway -n istio-system   -o 'jsonpath={.spec.ports[?(@.port==80)].nodePort}')`

Tried to use that IP address to communicate but connection is refused as well.

Thanks

**Comment by trisberg** [comment]
That IP address is only use when accessing the running apps on GKE cluster so not really related. What does `minikube status` show?

**Comment by odedia** [comment]
I just followed the guide again on a different computer and it worked up to the function creation stage, where it failed on "Init:Error". At any case, this issue seems cannot be reproduced so I'll close it and open a new one if needed.

Thanks!
