### ISSUE TITLE
Bring Your Own Riff Invokers (?)

### ISSUE THREAD

**Issue by kingdonb** [projectriff/riff#634]
So a couple of days ago I wandered in and found #226 which helped me run Ruby on Riff 0.0.7

Then Knative happened, and I remember hearing in some of the promotional materials that were released that all of the same invokers were supported...

https://projectriff.io/blog/riff-in-60ish-seconds/

"Riff now provides support for building function containers via a build template that uses the same invokers as Riff used before knative"

This sounds great, but the CLI help no longer provides any way to install an invoker, or really any mention of invoker at all.  This also sounds paradoxical, because Knative says Ruby is supported, while Riff has not had official Ruby support before... also, the `riff function create` help only mentions two invokers:

```
Usage:
  riff function create INVOKER FUNCTION_NAME  [flags]

Examples:
  riff function create node square --git-repo https://github.com/acme/square --image acme/square --namespace joseph-ns
  riff function create java tweets-logger
```

Can we get some comment regarding the new state of invokers in Riff and how you go about bringing your own?  I totally get that this is a new project, and I'm excited about it, but my whole team does Ruby primarily, ... the first utility of Riff for me would be to use during early development of APIs that haven't been through a design stage... so this is obviously a lot less compelling for me if I can't use it to run Ruby functions.

Hope you can understand my frustration as I only really started diving into the project about 5 days ago, and all my workflows are broken 🗡

**Comment by trisberg** [comment]
I hear you, and great that you are working on a Ruby invoker!

We are still working on improving the new CLI after the move to base the runtime on Knative and the invokers are currently hard coded here: https://github.com/projectriff/riff/blob/master/cmd/commands/function.go#L47-L48

We need to make this configurable, maybe add an `--invoker-url` flag ...

**Comment by trisberg** [comment]
You should also be able to test your functions by building the Docker image separately using a Dockerfile like:
```
FROM <your-invoker-image>
ARG FUNCTION_URI="<function-uri>"
ENV FUNCTION_URI ${FUNCTION_URI}
ADD <your artifact> /
```
and then pushing that image to DockerHub

You could then create a service for the function using something like:
```
riff service create my-fun --image acme/my-fun:1.0
```

**Comment by kingdonb** [comment]
Alright, super! I can edit that file and give it a shot.  Also thanks for the tip about `riff service create`.

Glad to see this project has really got some serious legs again!

**Comment by kingdonb** [comment]
A little rough around the edges, but your guidance was enough to make it work!

```
$ curl http://192.168.99.100:32380 \
  -H "Host: gem.default.example.com" \
  -X POST -d 'your data'; echo
["your data"]
```

My example is simple, it just installs any gems and then wraps your posted string data in a JSON array... so anyway I was able to use the exact same invoker I was using on 0.0.7 five days ago.

I thought I had to delete and then recreate the service once, and it took me a while to realize that I was not having luck because I was supposed to be POSTing some data to the service, ... and then it deleted itself for some reason, from the logs it looked like maybe having detected an update?

Wait a sec... that was the promised autoscaling "down to zero" behavior of Knative, wasn't it.

It was.  Superb.  The cold start time was quite a bit longer than with the last version of Riff, and it takes quite a bit longer to decide to scale back down to zero than the last version of Riff, but honestly for something that probably hasn't had much optimization done to it yet, I'll say that ain't bad for a first release... especially after total gut and re-tooling and everything else.  Nice!

**Comment by yebyen** [comment]
It actually went almost exactly like the TGI Kubernetes demo that I was watching while I did this now that I think about it.  Except much easier because of the riff system installer that saved me from knative long and detailed install doc.  (I was finished trying my Ruby invoker before he got his helloworld-go container up...)

**Comment by yebyen** [comment]
If there's anything that you want to track from here, I'll leave the issue open but, clear that there's no issue here for me.  Byo invoker is still very much possible.

**Comment by scothis** [comment]
Reopening because we need to restore CLI support for bring your own invokers.

riff 0.1 included a build comparability layer with previous invokers, the riff buildtemplate. As we move forward, we’d like to switch to build packs, which the new v3 model makes much easier to create. Knative provides many more options for build, as riff we’ll need to figure out how opinionated we want to be and what those opinions are.

**Comment by jldec** [comment]
Its important to encourage invokers authors by allowing full riff CLI usage for 3rd party invokers.

**Comment by jldec** [comment]
I liked the installable invoker design we had for riff previously.
It solved many of the requirements associated with #734 
- install invoker from a local directory (downloaded archive)
  - for #734 perform image name mapping during invoker install to reference private registry
- eliminate need to refer to github repos from hardwired invoker urls in cli
 
cc: @scothis

**Comment by scothis** [comment]
There isn't really anything meaningful to capture within a CRD as all of the metadata in the current Invoker CRD we either no longer use or is captured within the buildpack.

What we need to figure out is the best way to define the set of buildpacks to detect, and how to override that detection. Generally, defining the set of buildpacks to use within the cluster should be defined by the operator. Local builds should be allowed to use any buildpack regardless of whether it installed into the cluster.

**Comment by kingdonb** [comment]
> Local builds should be allowed to use any buildpack regardless of whether it installed into the cluster.

Agree strongly!  My favorite buildpack (Heroku packs) is the multi-buildpack.

**Comment by scothis** [comment]
> My favorite buildpack (Heroku packs) is the multi-buildpack.

You should like [Buildpack v3](https://buildpacks.io) then

**Comment by jldec** [comment]
How about (as a first step), just externalize the [list](https://github.com/projectriff/riff/blob/fac81e51b0c7c5f9d0abaf62c42a0dcf68b8bf5a/cmd/commands/function.go#L52) of invoker urls into a configmap, applied to the k8s cluster during install.

This would enable on-prem cluster operators to override the public invoker uris with their own private invoker urls, by pointing to a customized configmap during the install.

This should also satisfy the invoker-extensibility need expressed in this issue.

**Comment by markfisher** [comment]
I think externalizing into a ConfigMap makes sense for the short-term way of addressing on-prem private URLs, but I don't think we should promote that as an extensibility mechanism since we should be moving toward the v3 buildpack approach ASAP.

**Comment by ericbottard** [comment]
Using a ConfigMap kinda re-introduces the awkward dependency of the CLI/Cobra on an available cluster. What about having a hardcoded `map[shortname]url` for invokers, but also allowing a url to be used as the "invoker"?

Granted, given that we used the invokername as an argument rather than a flag, it will be a little weird, but it allows full extension for the interim before buildpack

**Comment by scothis** [comment]
#848 added the ability to specify a custom invoker-url

**Comment by kingdonb** [comment]
It looks like that's gone, is there a doc for what we do now? (all we Ruby-riffers)

I have https://github.com/kingdonb/riff/commits/master pegged at the commit before `--invoker-url` was removed, although I'm having some trouble building it...

Is there new documentation coming soon for 0.2 that will explain how to convert my invoker into a buildtemplate?  I'm excited!

**Comment by scothis** [comment]
Closing in favor of #1093
