### ISSUE TITLE
Provide build commands to view status and logs

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#635]
We need CLI commands to access build info and to view any error logs from a build

`riff build list`
`riff build status square-00001`
`riff build logs square-00001 --container build-step-build-and-push` 
`riff build logs square-00001 --all`

**Comment by jldec** [comment]
see also #623 - piping logs from successive build steps to stdout and stopping on error simplifies UX by reducing the need to spelunk.

**Comment by scothis** [comment]
We now have:
- `riff application/function list`
- `riff application/function create <name> --tail`
- `riff application/function tail <name>`
