### ISSUE TITLE
riff service create fails if the input channel already exists

### ISSUE THREAD

**Issue by dsyer** [projectriff/riff#642]
If channels are pub sub, they can have more than one subscription. So I assume this is a bug:

```
$ riff service create listener --image gcr.io/$GCP_PROJECT/listener --input events --cluster-bus stub
Error: channels.channels.knative.dev "events" already exists
```

Probably related:

```
$ riff service delete listener
riff service delete completed successfully
$ riff channel delete events
riff channel delete completed successfully
$ riff service create listener --image gcr.io/$GCP_PROJECT/listener --input events --cluster-bus stub
Error: subscriptions.channels.knative.dev "listener" already exists
```

**Comment by markfisher** [comment]
yes, that is a bug (or possibly 2)

a potential workaround is to create the service without`--input` and then use `riff service subscribe` as a follow-up step

**Comment by markfisher** [comment]
2 questions we need to answer before addressing this:

1. should we validate that IF the channel does already exist that it is using the same bus if specified?
2. should we have identical logic for the output channel (see #679) as for input?

related to question 1, exactly one of 'bus' or 'cluster-bus' is currently required when a channel is provided, but should we only require that if the channel does not already exist?

**Comment by scothis** [comment]
stale
