### ISSUE TITLE
Provide option for providing buildpack URL to "function create"

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#645]
Users should be able to provide a buildpack URL when creating functions, the default (currently Kaniko) might not be the best all the time.

**Comment by scothis** [comment]
I'm generally 👍 on allowing for using other build templates. The "gotcha" is that build templates are parameterized, so the CLI will need to pull the template and require the user satisfy required parameters.

**Comment by markfisher** [comment]
I think the `riff function` command should be opinionated, but we can add a `--build-template` option for `riff service create` in which case we're not expecting the `--image` to point to a prebuilt image

**Comment by trisberg** [comment]
This issue is specifically about providing a buildpack URL, using the buildpack build-template that already lines up well with the riff-build template. I created another issue for adding build options to the `riff service create` command - #737

**Comment by jldec** [comment]
fixed in #848
