### ISSUE TITLE
Install manifest

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#648]
Currently the installable resources are hard coded into the riff cli binary. This makes it very difficult to test new releases. Rather than expose the URL for each resource as a cli switch, we could define a manifest file that can then reference individual yaml files. A structured manifest will make it easier to pause for validation after installing Istio, or any other component that takes time to start.

A straw man proposal:
```
version: 0.1
istio: https://path/to/istio.yaml
system:
- https://path/to/knative-build.yaml
- https://path/to/knative-serving.yaml
- https://path/to/knative-eventing.yaml
- https://path/to/stub-clusterbus.yaml
namespace:
- https://path/to/riff-buildtemplate.yaml
```

cc @trisberg

**Comment by trisberg** [comment]
I agree we need to externalize this and a manifest seems better than overriding individual UTLs for the YAML artifacts

**Comment by glyn** [comment]
- [ ] Switch to istio and knative arrays in the manifest
- [ ] Implement 5 second delay between installs of items in the istio array
- [ ] Implement more specific global changes for items in the istio and knative arrays (`s/type: LoadBalancer/type: NodePort/`)
- [ ] Provide a sample manifest which is equivalent to the hard-coded behaviour (in the future we can sync these up using code generation)
