### ISSUE TITLE
document interfaces and other requirements for new function invokers

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#652]
For developers trying to write a new riff invoker, it would be helpful to provide some brief guidelines for minimal invoker requirements. I suggest adding in /docs.

### install
  - invoker url - public repo consumed by in first step of build

### build
  - Dockerfile

### runtime
   - http path 
   - http port
   - http method (point to Knative container contract perhaps)
   - http headers?
   - heathchecks?

NOTE: bear in mind that we'll be moving to buildpacks soon, so don't go overboard with Kaniko or riff-buildtemplate specifics.

**Comment by scothis** [comment]
This is the purpose of the [invoker-specification](https://github.com/projectriff/invoker-specification) repo
