### ISSUE TITLE
Automate creation of secret for build push credentials 

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#653]
The [steps](https://projectriff.io/docs/getting-started-with-knative-riff-on-gke/#create-a-kubernetes-secret-for-pushing-images-to-gcr) to create a secret for pushing builds are complex.

Can we do better by incorporating the Knative [gcr_helper](https://github.com/knative/build-templates/tree/master/gcr_helper) into our CLI or telling users to run it?

What about the [docker](https://projectriff.io/docs/getting-started-with-knative-riff-on-minikube/#create-a-kubernetes-secret-for-pushing-images-to-dockerhub) credentials?

**Comment by ericbottard** [comment]
This has been implemented already
