### ISSUE TITLE
Uninstaller reports success, even if you tell it not to uninstall

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#660]
The uninstaller will report a successful uninstall even if you say `n` to the prompt.

```
$ riff system uninstall --istio
Are you sure you want to uninstall the riff system? [y/n]: n
riff system uninstall completed successfully
```

Related, if no input is passed to the prompt the uninstaller will also report success. The prompt is effectively `[y/N]`.

**Comment by trisberg** [comment]
to avoid the "completed successfully" we would have to throw an error which is even uglier or we would have to have a way for any command to pass back a status which is a more invasive change.

**Comment by trisberg** [comment]
actually, we could do this on a command by command basis, just need to pass back a status that nothing was done
