### ISSUE TITLE
include git sha with riff version 

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#669]
It would be helpful to be able to validate the exact build, not just the version for `riff version`.

**Comment by scothis** [comment]
Before the Knative switch, we had talked about creating a config map to capture installed version metadata. We should consider doing the same or some other way to capture more version metadata.

**Comment by jldec** [comment]
I was thinking about the code used to build the riff CLI binary - esp users who run a CLI from a build of the riff repo master branch head.

Knowing more about about the installed bits in k8s would be nice too.
