### ISSUE TITLE
riff system install option to include ElasticSearch and Kibana

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#680]
Knative includes ElasticSearch and Kibana as optional components for aggregating and accessing logs. For users with sufficient memory say on minikube, it would be useful to install these components.

See Knative docs for [accessing logs](https://github.com/knative/docs/blob/master/serving/accessing-logs.md).

**Comment by trisberg** [comment]
Can be handled by using full `release-yaml` in a manifest #648
