### ISSUE TITLE
fix invoker docs for currently working riff invokers

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#687]
Let's bring back the invoker docs on the projectriff.io website and also add some notes in the invoker readme docs clarifying what is working for riff on Knative today, and what parts are not usable a.t.m because streaming support is not there yet.

**Comment by glyn** [comment]
Invokers to be covered:
- [ ] Java
- [ ] Node
- [ ] Go
- [ ] Command
- [ ] Python2 (?)
- [ ] Python3 (?)

@jldec Please confirm which invokers I should include.

**Comment by kingdonb** [comment]
Can we put Ruby on the list?  I have had great success with the sample provided in #226 and want to join your mailing list

Would like to be sure it receives all of the same best-practice advice as gets applied to the other invokers that you are maintaining in-house (maybe get it merged even)

- [ ] Ruby

**Comment by glyn** [comment]
@kingdonb Sure. I'll add a separate list of "community" invokers.

@jldec Please could you advise how @kingdonb should best stay in touch with invoker best-practices? I'm not sure we have a riff mailing list...

**Comment by jldec** [comment]
@glyn @kingdonb 
I recommend keeping an eye on the invoker roadmap issue #675, and particularly issues #634 and #654 which will affect invoker authors.

**Comment by kingdonb** [comment]
Yeah I was using "mailing list" as a surrogate for however contributors interact most frequently

I'm on the Knative slack and asked to get a #riff channel created, but I understand if the intention is to keep discussion centralized and focused on the Github issues

so I'm "joining your mailing list" – thanks for the pointers to issues I can keep an eye on!

**Comment by glyn** [comment]
@kingdonb Actually, the documentation that this issue will add to the riff website is for _users_ rather than _invoker authors_, so it needs to cover just those invokes which the `riff` CLI currently supports. The Ruby invoker will need ["bring your own invoker" support](https://github.com/projectriff/riff/issues/634) before it can be made available to users of the `riff` CLI, so I'm afraid I won't be able to include it in this issue.

**Comment by scothis** [comment]
https://projectriff.io/docs/v0.4/invokers/java
