### ISSUE TITLE
function create --verbose stalls on GKE

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#693]
Using `riff function create --verbose` stalls on GKE between the build pod and the running revision. It works fine on minikube.

See https://travis-ci.org/projectriff/fats/jobs/421257815#L767

cc @glyn

**Comment by glyn** [comment]
Hmmm. I just ran it on GKE and there was a pause of a few seconds after `build-step-build-and-push` before the application itself started running, but there was no stall. Is there any reason to think that the function creation itself did not stall, as that's the obvious explanation?

**Comment by scothis** [comment]
Good question, it could be something upstream in Knative Serving not resolving as expected. I pointed the finger towards something being amiss in GKE because the FATS minikube builds passed and the GKE build a few times in a row when trying to add `--wait` to `riff function create` in FATS.

**Comment by scothis** [comment]
In FATS, the command function passes regularly, while the jar function fails regularly.

It looks like the function starts, but the `riff --verbose` never sees the function as running and times out.

```
default/fats-uppercase-jar-00001-deployment-8685df5f-kxdhr[user-container]: INFO: Started application in 3.532 seconds (JVM running for 4.408)
Error: function creation failed: RevisionMissing: Configuration "fats-uppercase-jar" does not have any ready Revision.; Revision "fats-uppercase-jar-00001" failed with message: "Unable to create pods for more than 120 seconds.".
```

https://travis-ci.org/projectriff/fats/jobs/437345291#L768

**Comment by scothis** [comment]
I haven't seen this in a long time
