### ISSUE TITLE
0.1.2 release - publish and point CLI to latest install yaml for Istio, Knative, eventing, bus

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#696]
The riff cli depends on published copies of the install yaml for Knative components and for Istio. Currently these are manually prepared and published prior to each release.

Let's please capture how this process is done for others on the team to learn or automate in future.

**Comment by trisberg** [comment]
We now point to the files published nightly by the Knative project. The only file we host ourselves is `previous/riff-build/riff-build-0.1.0.yaml` containing the build-template we use. It is stored in the GCS bucket `https://storage.googleapis.com/riff-releases` and it doesn't change that frequently.

**Comment by scothis** [comment]
I kinda hope riff-build is never updated :)

**Comment by trisberg** [comment]
A detailed list of all steps is now in #697
