### ISSUE TITLE
Introduce `riff image relocate` to map the image coordinates to a user's docker registry

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#702]
See https://github.com/projectriff/riff/issues/688#issuecomment-415800900 for background.

**Comment by glyn** [comment]
I propose to map all images of the form `registry/user/xxx` (where `registry` can be _any_ host, typically `docker.io` or `gcr.io` and user can be _any_ user, typically `istio` or `knative-releases`) to `somehost/someuser/xxx` where `somehost` is the private registry and `someuser` is a suitable user in the private registry. There are two restrictions implicit in this mapping:

1. image names (the `xxx` bit) are preserved
2. there will be no collisions between public docker registries (e.g. `docker.io/isto/thing.yaml` and `gcr.io/knative-releases/thing.yaml`) or between users in a single registry (e.g. `gcr.io/knative-serving/release.yaml` and `gcr.io/knative-eventing/release.yaml`).

Suggested syntax (with no single letter switch abbreviations):
```
$ riff system install --privateRegistry=somehost --privateUser=someuser
```

**Comment by ericbottard** [comment]
Given other discussions, I'm not sure the need for `--privateRegistry` and `--privateUser` would stay, but if it does, I'd drop the "private" part. The fact that it is _sometimes_ used for private registries is just one use case. I may as well want to use an alternate (public) registry.

**Comment by trisberg** [comment]
could we add `registry` and `user` to the manifest instead of using separate flags? I'm assuming we would be using the registry to specify the yaml files anyway.

**Comment by glyn** [comment]
@trisberg I don't think that would be usable. The idea is that the customer downloads a `.tgz` file from Pivnet which contains the manifest and the YAML files. So the customer won't really be in the game of editing the manifest.

**Comment by trisberg** [comment]
I guess I'm not quite following this then - wouldn't the manifest already have the registry and user settings in the image or are we talking about doing a replace of the registry/user part?

**Comment by glyn** [comment]
@trisberg The `.tgz` file will refer to certain public docker registries, but a customer who doesn't allow their runtime to access the internet will push all the images to a _different_ private registry (but won't be expected to edit the `.tgz` file). So, yes, we do need to replace the registry/user part of the image names because we don't know the registry names and users that customers will choose.

**Comment by glyn** [comment]
To identify which strings in YAML files represent image names that should be mapped, we add another switch to point at an "image manifest" which lists the image names in an array:
```
$ riff system install --registry=somehost --registryUser=someuser --images=/path/to/image/manifest
```
The image manifest is a YAML file of the form:
```
manifestVersion: 0.1
images:
  - gcr.io/knative-releases/github.com/knative/build/cmd/creds-init@sha256:b5dff24742c5c8ac4673dc991e3f960d11b58efdf751d26c54ec5144c48eef30
  - <etc.>
```

**Comment by glyn** [comment]
Implementation:

- [ ]  image mapper utility
- [ ]  image manifest
- [ ]  support images of the form `username/path`
- [ ]  decide what to about images of the form `localhost[:port]/user/path`

**Comment by glyn** [comment]
Split out mapping of hierarchical image names to [issue 724](https://github.com/projectriff/riff/issues/724).

**Comment by glyn** [comment]
# DockerHub Support
`user/path`, `docker.io/user/path`, and `index.docker.io/userpath` are treated as equivalent entries in the image manifest (so you only need to specify at most one of them and it doesn't matter which) and when they need mapping, are three all mapped to `somehost/someuser/path`.

**Comment by glyn** [comment]
Changing the design to introduce a new subcommand for image relocation:
```
riff image relocate
```
This would take either a manifest or a YAML file as input and output.

Editing the title to match.

**Comment by ericbottard** [comment]
What do you mean "take a YAML file as input"? Do you mean a file that could be `kubectl apply`ed?

Also, that command would grab the image bits, right?

**Comment by glyn** [comment]
> What do you mean "take a YAML file as input"? Do you mean a file that could be kubectl applyed?

Yes, for example a bus YAML.

> Also, that command would grab the image bits, right?

No. I'm scoping this issue to do relocation of image names only for now. So you can relocate a single YAML file or a whole manifest of YAML files.
