### ISSUE TITLE
riff system install optionally to install from local directory

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#703]
This is to support installing from a local archive containing manifest and all the YAML files referenced by the manifest.

See https://github.com/projectriff/riff/issues/688#issuecomment-415800900 for context.

**Comment by glyn** [comment]
Proposed syntax (with no single-letter switches):
```
$ riff system install --archive=riff.tgz
```

**Comment by glyn** [comment]
Given that the archive may contain GBs of images, it makes more sense for the user to explode it and pass a directory to the CLI. This would make is easier to ship platform specific archive types (such as tgz for linux and zip for windows and macOS).

Proposed syntax (with no single-letter switches):
```
$ riff system install --directory=/some/directory/path
```

**Comment by ericbottard** [comment]
This *forces* the user to unpack it. Why not have `--from=<url>` and if it is a directory, proceed as you describe (and also opens up support for http support, etc)?

**Comment by jldec** [comment]
if the steps to install are the following, it may make more sense to install from local directory instead of archive file.

1. download archive
2. explode archive into an archive-folder
3. load images from archive-folder/images/xxx to the container registry
4. run install using CLI and yaml files from the same archive-folder

**Comment by glyn** [comment]
@ericbottard Yes, that was an earlier idea, but these files are most likely to be used when they contain gigabytes of images, which will likely wreck temp space.

**Comment by glyn** [comment]
Given that directory should contain a manifest and may contain an [image manifest](https://github.com/projectriff/riff/issues/702#issuecomment-417295234), I propose to use a file naming convention to identify manifests:

- The manifest must be called `mainfest.yaml`
- The image manifest must be called `image-manifest.yaml`

and each manifest, if present, must appear in the root of the specified directory. The manifest can use relative paths to refer to YAML release files in the directory. It's likely, but not required, that the YAML release files will also appear in the root of the specified directory, in which case their unardorned filenames can be used as relative paths.

**Comment by glyn** [comment]
Let's adopt @ericbottard's syntax suggestion:
```
$ riff system install --from=/some/directory/path
``` 
This is pithier and gives us the _option_ of installing directly from an archive in future.

**Comment by glyn** [comment]
@jldec Closing this in favour of https://github.com/projectriff/riff/issues/740.
