### ISSUE TITLE
Building function image using GCR on minikube fails

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#723]
Trying to build square function using a gcr.io image fails on minikube

**Comment by trisberg** [comment]
With the latest riff builder we are getting this error:

```
[build-step-analyze]: 2019/03/06 18:43:54 Error: connect to repo store 'gcr.io/cf-sandbox-trisberg/square:minikube': Get https://gcr.io/v2/token?scope=repository%3Acf-sandbox-trisberg%2Fsquare%3Apull&service=gcr.io: invoking docker-credential-gcr: exit status 1; output: docker-credential-gcr/helper: could not retrieve GCR's access token: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

**Comment by trisberg** [comment]
I'm assuming this is related to https://github.com/buildpack/roadmap/issues/42

**Comment by trisberg** [comment]
We can track this in https://github.com/buildpack/roadmap/issues/53

**Comment by scothis** [comment]
Based off my understanding of the root issue, if you relocate the builder and run images to GCR, you'll be able to push builds to GCR, but not DockerHub. Is that correct?

**Comment by trisberg** [comment]
Still the same error. I even added an image pull secret for the build service account to be able to pull the pack images from gcr.io that now were private. The `build-step-analyze` container still shows the same "default credentials" error.

**Comment by scothis** [comment]
Upstream issues are closed, reopen if this is still an issue
