### ISSUE TITLE
improve test coverage to include eventing 

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#728]
The current [riff acceptance test suite 🐀](https://github.com/projectriff/fats) runs uppercase functions for each of the 3 invokers.

For users trying out basic eventing features like channels and subscriptions, it would be good to validate that these features are also covered.

For inspiration, refer to [function chaining](https://projectriff.io/blog/announcing-riff-0-1-2-on-knative/#function-chaining-over-channels) in the v0.1.2. announcment.

**Comment by fbiville** [comment]
Merging https://github.com/projectriff/riff/pull/739 would help for the subscription cleanup :)
