### ISSUE TITLE
Add a --build-template option for "riff service create"

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#737]
It would be nice to have the option of providing source-repo/build-template options for a build step when creating a new service

**Comment by ericbottard** [comment]
The current distinction between `riff service create` and `riff function create` is that only the latter deals with build. So seems we're kind of going backwards.

I think we need to decide what it means to be "a function" (ie use `riff function create`):

1. is it something that needs to use Knative build (as is today)
2. or is it something that uses **the** opinionated riff buildTemplate (ie kaniko today, buildpack tomorrow)

If we stick to 1) then your proposition applies more to `riff function create`.
If 2), then the difference between the two commands is really thin (only a matter of having a default value for `--build-template`, in a way)

**Comment by trisberg** [comment]
What I'm suggesting does not include adding the the riff invoker layer, so it is applicable to any app, I just want the build to happen in the cluster using the standard Knative build-crd. That's why I think it fits better under `service`.

**Comment by trisberg** [comment]
No longer relevant
