### ISSUE TITLE
Mocks are re-generated before every `make test` run

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#748]
Since the generated code is committed into the repo, the mocks should only need to be updated when the interfaces they are mocking are updated.

Consider this another vote for an explicit code-gen script instead of a Makefile.

**Comment by ericbottard** [comment]
The problem is not with Makefile (quite the contrary) but with the clever use we (read: I) tried to make of it.
I was about to create an issue for this very problem myself. I'll come up with a quick fix
