### ISSUE TITLE
`riff system uninstall ...` ends before uninstall is complete

### ISSUE THREAD

**Issue by fbiville** [projectriff/riff#750]
The current behavior is currently counter-intuitive as the command displays the following message:
```
riff system uninstall completed successfully
```
However, when I try to run `riff system install` right after that, I get the following message:
```
Error: The knative-serving namespace is currently 'Terminating'. Please try again later.
```

As suggested by @glyn, we could add a `--wait` flag to allow users to wait for the actual uninstall completion. When the flag is not set, we should output a command allowing the user to follow the status of the uninstall.

**Comment by Turbots** [comment]
I have had the same issue, minor annoyance but if you have some patience, it works itself out of course.

**Comment by trisberg** [comment]
I've seen this behavior before, by with `kubectl` 1.11.x installed I've not seen it or it happens less frequently.

**Comment by fbiville** [comment]
Closing this as the more generic issue should tackle this command as well: https://github.com/projectriff/riff/issues/1079.
