### ISSUE TITLE
Improve error message when riff invokes a service for which the image is invalid

### ISSUE THREAD

**Issue by fbiville** [projectriff/riff#761]
Currently, the `--image` argument is not checked at all and an invalid image 
triggers an issue only when the service is invoked, which happens quite late in the process.
To make things worse, the error message displayed at invocation time is not explicit.

**Comment by scothis** [comment]
To do this the riff CLI would need to fetch the registry credentials out of the cluster. It would also need to distinguish between push and pull rights and whether the image is expected to exist at that moment.

This is all possible, but I would put emphasis on improving the error messages first.

**Comment by fbiville** [comment]
Sure thing, rephrasing the issue now.

**Comment by scothis** [comment]
We no longer have an invoke command, but the Handler resource reports a ready condition that can be consulted. If the image is bad, the handler will not become ready.
