### ISSUE TITLE
Move channel support from `riff service|function create` to `riff subscription create` subcommand 

### ISSUE THREAD

**Issue by fbiville** [projectriff/riff#771]
Following @ericbottard suggestion, the subcommand would have the following shape:
```
riff subscription create [optional-name] \
      --from <channel> \
      --processor <svc> \
      [--to <channel>] \
      [--namespace <namespace>]
```

`--input`/`--output` arguments will be removed from `riff service create` and `riff function create` .

**Comment by markfisher** [comment]
property names have changed in the Knative Subscription CRD: https://github.com/knative/eventing/pull/421

**Comment by jldec** [comment]
@scothis would you mind correcting/summarizing the new option names for this issue.

**Comment by glyn** [comment]
@jldec I implemented the agreed flag names. Please see the [docs](https://github.com/projectriff/riff/blob/master/docs/riff_subscription_create.md).

**Comment by jldec** [comment]
Updated original post with final design/help text.
