### ISSUE TITLE
smaller build image size

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#791]
The Knative Build image is currently very large, slowing down first-time builds significantly.
It would be helpful for demos and developer experience to fix this in the next release.
Tracking https://github.com/knative/build/pull/318 and https://github.com/knative/build/pull/363

**Comment by trisberg** [comment]
Now we just need this merged https://github.com/knative/serving/pull/2050

**Comment by trisberg** [comment]
The PR https://github.com/knative/serving/pull/2062 is merged, now we just need the nightly build for the release YAML

**Comment by scothis** [comment]
now in the stable manifest
