### ISSUE TITLE
temporary release of correlator app to help send events into channels 

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#792]
This is needed for demos and discussions because it's difficult to hit channel endpoints from outside the cluster. 

Suggested repo: projectriff/correlator

**Comment by markfisher** [comment]
repo now available: https://github.com/projectriff/correlator

will make a few updates and then push to the `projectriff` docker hub org

**Comment by markfisher** [comment]
first image pushed:

https://hub.docker.com/r/projectriff/correlator/tags/

looking forward to contributions
