### ISSUE TITLE
All shell-outs to kubectl need to pass `kubeconfig` and `server` switches if set on riff

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#803]
The riff cli accepts `--kubeconfig` and `--master` to configure the kubernetes server the command should connect to. However, when we shell out to kubectl, we don't set the values and thus can only communicate with the default cluster, even if the user explicitly asked to connect to another cluster. This is potentially dangerous for an operator depending on the default cluster they have selected.

Note: the `--master` switch in riff is named `--server` in kubectl

**Comment by trisberg** [comment]
We do guard against that here: https://github.com/projectriff/riff/blob/master/cmd/commands/system.go#L59-L66

Not that I'm against supporting them
