### ISSUE TITLE
riff image relocate should provide more feedback to user

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#808]
When copying the images as the last step, there may be a pregnant pause depending on the quantity of image data to be copied and the type of file system. When there is a large amount of data and the file system is relatively slow (e.g. on macO with a fusion drive), image copying can take many seconds.

The command should print when it is about to start copying.

**Comment by ericbottard** [comment]
Might be as simple as using `cp -v`

**Comment by glyn** [comment]
Yeah, logically at least. Remember we plan to replace shelling out to `cp` with some Go code. ;-)
