### ISSUE TITLE
make gen-mock doesn't run when needed

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#812]
I made a change to a struct that is causing the tests to panic without updated mocks. Running `make gen-mock` says there is nothing to do. It is wrong.

I shouldn't need to understand the inner working of Make in order to get it to work.

**Comment by ericbottard** [comment]
Which struct?

**Comment by scothis** [comment]
CreateFunctionOptions

**Comment by scothis** [comment]
Presumably any change to an arg used by the mocked client would need the mocks to be regenerated
