### ISSUE TITLE
Allow for multiple push credentials

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#817]
It should be possible to have active credentials for multiple image registries. So that Build CRD can push images to difference locations depending on the function.

Currently `riff namespace init` requires one of a manual secret, Docker Hub or GCR credentials. If a preexisting secret exists, it is replaced with the new value. New credentials should augment the service account to allow for migrating to a new image registry.

**Comment by fbiville** [comment]
Apologies in advance if I misunderstand the current state of riff and Knative:
> If a preexisting secret exists, it is replaced with the new value
It seems to me that the current impl preserves the pre-existing secret, if they share the same name (https://github.com/projectriff/riff/blob/master/pkg/core/namespace.go#L142).
TheIsn't it sufficient to bind a new secret with a different name to the existing service account to have subsequent builds

**Comment by scothis** [comment]
> It seems to me that the current impl preserves the pre-existing secret, if they share the same name 

Good question, registering the secret is a two step process:
1. create the Secret resource
2. reference the Secret in the ServiceAccount

The line you linked to is when the secret is registered with the ServiceAccount. We [delete a preexisting secret](https://github.com/projectriff/riff/blob/master/pkg/core/namespace.go#L109) as a part of step 1.

> is it sufficient to bind a new secret with a different name to the existing service account

I think so, but we'll need to try it to verify.

**Comment by fbiville** [comment]
Thanks for clearing that up.

Without changing code, my assumption is that running `namespace init` against the same namespace with different secret names each time would do the job (although I'm not saying this is a good solution). 

Back to the initial suggestion, do we want to get rid of the secret overwrite in 100% of cases? Shouldn't we remove the preexisting secrets if the metadata annotations of the existing and new secrets are equivalent?

**Comment by trisberg** [comment]
I think we should add a command to add credentials to an already existing `riff-build` service account.

We would require the secret name to be something other than `push-credentials` and the service account `riff-build` to already exist, the rest of the flags would match `namespace init`
```
riff namespace add-credentials --secret extra-creds [--gcr <path>] [--docker-hub <docker-id>] [--registry <registry-url> --registry-user <user>]
```

**Comment by fbiville** [comment]
Note: these added credentials should be removed when running `riff namespace cleanup`.

**Comment by fbiville** [comment]
Here is the updated specification for this issue:

1. [ ] introduce `credentials set [--secret <secret> (default: push-credentials)] [--gcr <path>] [--docker-hub <docker-id>] [--registry <registry-url> --registry-user <user>] [--namespace <ns>]`
1. [ ] introduce `credentials list [--namespace <ns>]` 
1. [ ] introduce `credentials delete [--secret <secret>] [--namespace <ns>]`

By supporting the following features, the plan is to also deprecate/remove `namespace init`:

1. create the riff build service account if it does not exist when `credentials set` is called
1. handle the image prefix just like `namespace init` does when `credentials set` is called

**Comment by fbiville** [comment]
As suggested by @scothis, there are two options to implement `riff namespace cleanup`:

 1. delete the service account and remove the image prefix from the config map when the last secret of the namespace is removed with `riff credentials delete`.
 2. let `riff-system` match the resources by the initialization labels used

**Comment by scothis** [comment]
done in #1266
