### ISSUE TITLE
Is there a better way to prevent docker from attempting to download from dev.local?

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#849]
When installing riff on a local kubernetes cluster with images residing only in a docker daemon, the following command is used:
```
$ riff image relocate --manifest ... --registry dev.local \
--registry-user <arbitrary user> --images ... \
--output ... --flatten
```
Registry `dev.local` is specified to indicate "local only" in which case the riff CLI tags any untagged images with something other than `:latest` (it currently uses `:local`) to prevent docker later failing to download from `dev.local` (which doesn't really exist) when checking for the latest version of an image.

It would be better if spurious download attempts could be avoided without the use of an arbitrary tag.

**Comment by glyn** [comment]
One option is to support a `--tag` switch with default value `local` so that the tag is no longer arbitrary. Another is to tag with a SHA which at least ensures (a certain kind of) uniqueness.

**Comment by scothis** [comment]
The `dev.local` image prefix is only special to knative serving when it resolves a Knative Revision's image name to a pin the sha for the Deployment.

**Comment by glyn** [comment]
> ...  to a pin the sha ...

I don't understand this phrase.

**Comment by glyn** [comment]
https://github.com/projectriff/riff/issues/977 renders this issue obsolete.
