### ISSUE TITLE
Cannot override "scale-to-zero-threshold" property on riff deployments

### ISSUE THREAD

**Issue by sabbyanandan** [projectriff/riff#855]
As a riff user, I wanted to override the default `scale-to-zero-threshold` behavior in `config-autoscaler` from 5m to 10s, but the change appears to not apply at runtime.

To reproduce, 
- go to "Config and storage -> Config Maps -> config-autoscaler" (from the Dashboard) and edit the `scale-to-zero-threshold` from 5m to 10s
- create and invoke a node function (I used the stock `square` function)
- verify the results
- wait for 10s .. 1m .. 5m ... the pod will terminate eventually

```
"data": {
    "concurrency-quantum-of-time": "100ms",
    "container-concurrency-target-default": "100",
    "container-concurrency-target-percentage": "1.0",
    "enable-scale-to-zero": "true",
    "enable-vertical-pod-autoscaling": "false",
    "max-scale-up-rate": "10",
    "panic-window": "6s",
    "scale-to-zero-grace-period": "2m",
    "scale-to-zero-threshold": "10s",
    "stable-window": "60s",
    "tick-interval": "2s"
  }
```

It might be a problem in Knative itself - possibly knative/serving#1958.

**Comment by glyn** [comment]
Yes, looks like a dup of https://github.com/knative/serving/issues/1958, which is itself a user error because of the unfortunate way that the autoscaler enforces some limits on configuration values and essentially ignores invalid values. See my [comment](https://github.com/knative/serving/issues/1958).

**Comment by glyn** [comment]
I agree the threshold should probably remain the same, but the way that values below the threshold are processed could be improved as per my suggestion.
