### ISSUE TITLE
Implement `riff-distro version`

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#861]
Make this analogous to `riff version`.

**Comment by fbiville** [comment]
Do `riff` and `riff-distro` share the same version?

**Comment by jldec** [comment]
yes - i expect that we would release them together.

**Comment by glyn** [comment]
We might want to allow the versions to diverge in the future, but we can certainly defer that for now to keep things simple.

**Comment by fbiville** [comment]
What about symlinking the `VERSION` file for now? Once we want to have diverging versions, it'll just be a matter of replacing the symlink with a regular file.

**Comment by ericbottard** [comment]
Use dot dot

**Comment by fbiville** [comment]
Oops, forgot to mention the issue in the commit: https://github.com/projectriff/riff/commit/77dba56d27d5a32c6038fb1de131ae8c617dc98c.
It's done now.
