### ISSUE TITLE
Clean up branches on this repo

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#863]
I as a user sometimes look at a projects branches to understand versioning policies. We as a team use personal forks to add features.
If some branches have been created on this repo, they were meant to be transient and to help when no other solution was deemed usable.
They should not clutter the branches drop-down anymore.

**Comment by fbiville** [comment]
We could remove all of these: https://github.com/projectriff/riff/branches/stale, right?

**Comment by ericbottard** [comment]
Hmmm, not really.
IMHO, we should (aim for and) be able to remove everything but `master` and `v0.0.x`

**Comment by ericbottard** [comment]
`v0.0.x` is considered stale, but should NOT be deleted

**Comment by scothis** [comment]
I deleted the branches I created

**Comment by trisberg** [comment]
I deleted mine as well

**Comment by scothis** [comment]
the only branches left are master and release branches from when this repo hosted code
