### ISSUE TITLE
Clarify projectriff/buildpack OSS

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#874]
From [function.go:L49](https://github.com/projectriff/riff/blob/master/cmd/commands/function.go#L49) the build image used for `riff function create java` is called `projectriff/buildpack`.

There does not appear to be any OSS repo to help riff users figure out where this image comes from, what it does, or what the constituent v3 buildpacks inside it are. https://github.com/projectriff/riff-buildpack appears to play a role but it is not the whole story.

cc @nebhale

**Comment by nebhale** [comment]
Yep, this needs the help of a `riff-buildpack-group` repository (which can be started without `pack` CLI HTTP support).

**Comment by ericbottard** [comment]
Created https://github.com/projectriff/riff-buildpack-group with initial content
