### ISSUE TITLE
Custom CA cert in build process?

### ISSUE THREAD

**Issue by andrewdriver123** [projectriff/riff#880]
Is there a way to mount a secret (in this case a TLS CA cert) into the `build-step-git-source` init container so that we can pull code from a Git repo that is inside a corporate network?

We gather that mounting a secret into the appropriate place in the container filesystem is the right way to do this, but given that Riff creates the pod rather than us, we're not sure how best to do this.

Additionally, is there a Slack or Discord for discussing Riff?

**Comment by ericbottard** [comment]
Hi @andrewdriver123 

I believe you're looking for https://github.com/knative/docs/blob/master/build/auth.md.

`riff` (via the `riff namespace init` command) takes care of credentials for the *docker registry*, but you should be able to install your git credentials the way described in the docs linked above once you've run `riff namespace init`. The service account is `riff-build`

**Comment by andrewdriver123** [comment]
Thanks for linking to those docs, @ericbottard.

We're trying to make a CA cert available, as our Git repository is using a self-signed TLS certificate. The documentation talks about Git credentials for user-level authentication, rather than CA certs for validating the authenticity of the server. Are we misunderstanding the linked docs? It's entirely possible, as it's the end of our day...

**Comment by ericbottard** [comment]
Ah, no it's rather my mistake (but it's end of day here for me as well :) ).
I'm not sure how you would configure a CA cert in the first place (not even in the context of Knative/riff). Could you detail that? Then maybe we can find a solution, but my gut feeling is that it's something we'll need to resolve at the Knative level

**Comment by andrewdriver123** [comment]
Thanks for getting back to us, @ericbottard.

We needed to get the CA certificate that was used to sign various internal certificates (in this case, for an internal GitHub equivalent) into the `build-step-git-source` init container, so the `git clone` would work. Previously it was failing with invalid cert errors.

In a manual test of the approach we added the CA cert as a base64-encoded secret, and mounted it into a container based on an Ubuntu image. If we mount the secret as a file in `usr/local/share/ca-certificates` and then imperatively run `update-ca-certificates`, then we were able to `curl` said GitHub-equivalent without TLS errors. The `update-ca-certificates` command seemed to be copying the certificate into `/etc/ssl/certs` and doing some sort of reload. Mounting the cert directly into `/etc/ssl/certs/` did not work: it seems the `update-ca-certificates` command was required.

We think the indirection is what's tricky here - we need to tell Riff about the CA cert secret, so then it can tell Knative that when it's generating the pod manifest it should mount the secret into the right place (and maybe run the command?). We're not sure how much this differs between various Linux distributions, so catering for all of them could be an overhead?

**Comment by DanielJonesEB** [comment]
I'm helping (in the loosest sense of the term) @andrewdriver123 with this. We switched to using SSH to clone instead of HTTP, which got us around the issue for now.

We've now run into this: https://github.com/projectriff/riff/issues/882

**Comment by ericbottard** [comment]
@andrewdriver123 Seems like what you would need to support this in riff is to customize the BuildTemplate in some way.
* Either customize the images so that your CA is already installed
* Or add some extra step(s) that install the CA with the process you described [above](https://github.com/projectriff/riff/issues/880#issuecomment-430192580)

I'm not sure there is some "standard" procedure for dealing with CAs that could be extracted from this, but if there was, this could become supported in Knative itself, the same way Knative already supports docker and git credentials.
