### ISSUE TITLE
Speed up `riff-distro image list` checking

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#887]
Currently, unless `--no-check` is specified, `riff-distro image list` validates each image it finds by making sure that `docker pull <image>` and `docker inspect --type=image <image>` both succeed.

This is rather inefficient as it involves downloading the images to the local docker daemon. It also requires a docker daemon to be running.

If there was a speedy way to check image validity, e.g. via the relevant docker registry, that would be preferable.

**Comment by jldec** [comment]
No longer required since #949.
