### ISSUE TITLE
Relocated images pushed to non-public registry can't be used for "riff system install"

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#896]
If we relocate images for a distro and push them to GCR as private images then they can't be used for a "riff system install" while referring to the manifest YAML file for the relocated images. The install fails due to k8s not being able to pull the images. 

We would need to patch all service accounts with "imagePullSecrets" before doing the install. This would require the namespaces to be created first, then a secret has to be created with the service account credentials for pulling images. Once this is done we can create the service accounts with the "imagePullSecrets" referring to the secret we created. With this in place we should be able to install the knative system.

**Comment by trisberg** [comment]
Managed to get it all running using a manual install with the following adjustments:

1. after the namespace is created I created  a secret with image pull credentials - for GCR I used:
```
kubectl create secret docker-registry "gcr" \
  --docker-server=gcr.io \
  --docker-username=_json_key \
  --docker-password="$(cat ~/.config/configstore/cf-sandbox-trisberg-pull-image.json)" \
  --docker-email=trisberg@pivotal.io \
  --namespace "istio-system"
```
where the JSON key file is created from a service account that has `roles/storage.objectViewer`

2. for each ServiceAccount set the `imagePullSecrets` like the following:
```
apiVersion: v1
kind: ServiceAccount
**imagePullSecrets:
- name: gcr**
metadata:
  name: istio-ingressgateway-service-account
  namespace: istio-system
...
```

Repeat the above for all namespaces - istio-system, knative-build, knative-serving and knative-eventing

Also patch the default service account in the namespace used to run apps/functions using:
```
kubectl patch serviceaccount "default" \
    -p '{"imagePullSecrets": [{"name": "gcr"}]}' \
    -n "default"
```

**Comment by trisberg** [comment]
Forgot to mention that I added the secret for the `riff-build` service account as well:

```
kubectl patch serviceaccount "riff-build" \
    -p '{"imagePullSecrets": [{"name": "gcr"}]}' \
    -n "default"
```

**Comment by jldec** [comment]
@trisberg do you have any suggestions for helping users automate some of this
(how would they know which namespaces to pre-initialize etc.)

**Comment by trisberg** [comment]
They can't use the yaml files we provide, they would need to be modified. Ideally we add this to the `riff image relocate` command where we could insert the necessary config options and the secret for pulling images.

**Comment by trisberg** [comment]
Looks like I can grant GCR pull access to the service account used for the PKS nodes. I ran the following:

```
gsutil iam ch serviceAccount:morganhill-pks-worker-node@cf-sandbox-trisberg.iam.gserviceaccount.com:objectViewer gs://artifacts.cf-sandbox-trisberg.appspot.com
```

This seems a lot easier than messing with the YAML files. Not sure how this would work for a VSphere cluster though.

**Comment by jldec** [comment]
Document workaround for alpha.

**Comment by markfisher** [comment]
I added the "documentation" label and removed "bug" since this is more about the way private registry access needs to be configured. We might take a K8s ServiceAccount approach later (modifying resource YAML etc), but if for now we'll be taking the lower level approach (configuring access for the worker node), then we would need to add a section to the documentation for each different deployment environment/registry we support.

**Comment by glyn** [comment]
`riff` no longer supports image relocation, so we can probably close this issue.
