### ISSUE TITLE
Support relocation of images which are hard-coded in the riff CLI

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#898]
Currently the use can use `riff image relocate` to relocate images referred to in the kubernetes configuration files referenced by a riff installation manifest, but the hard-coded images in the riff CLI are not affected.

Sub-tasks:
- [ ] include the hard-coded images in those listed by `riff-distro image list`
- [ ] extend the CLI operations which use the hard-coded images to allow those images to be relocated before being used

**Comment by glyn** [comment]
Focussing first on invoker base images, the riff CLI doesn't literally hard code the image names. Rather `riff function create` passes an invoker URL (either hard-coded or user-supplied) to a build (see projectriff/riff-build) which uses the contents referred to by the URL to generate a Dockerfile which is used to construct the function’s image. The generated Dockerfile refers to a base image for the invoker. It’s these base images that need relocating to a private registry.

**Comment by trisberg** [comment]
so the build-templates have image references in them:

riff:
```$ k get buildtemplate riff -oyaml | grep image:
    image: index.docker.io/projectriff/riff-init-a53b8b34598fd723044b9fc6d0471a62@sha256:33130595cba42999c2a25dccb2d25b9accd5e2f6745dad75702e9e061a762d72
    image: gcr.io/kaniko-project/executor
```

riff-cnb:
```
$ k get buildtemplate riff-cnb -oyaml | grep image:
    image: packs/base
    image: projectriff/buildpack
    image: packs/util
    image: projectriff/buildpack
    image: packs/util
```

The above is from a relocated distro but using `riff namespace init default --dockerhub trisberg` without a manifest, so it looks like I should use the `--maninfest` option to get the build-templates with the relocated references.

Running `riff namespace init default --dockerhub trisberg --manifest /Users/trisberg/Test/my-riff-release/manifest.yaml` I get the following:

```
$ k get buildtemplate riff -oyaml | grep image:
    image: gcr.io/cf-sandbox-trisberg/riff-init-a53b8b34598fd723044b9fc6d0471a62-33130595cba42999c2a25dccb2d25b9accd5e2f6745dad75702e9e061a762d72
    image: gcr.io/cf-sandbox-trisberg/executor
```

and 

```
$ k get buildtemplate riff-cnb -oyaml | grep image:
    image: gcr.io/cf-sandbox-trisberg/base
    image: gcr.io/cf-sandbox-trisberg/buildpack
    image: gcr.io/cf-sandbox-trisberg/util
    image: gcr.io/cf-sandbox-trisberg/buildpack
    image: gcr.io/cf-sandbox-trisberg/util
```

**Comment by trisberg** [comment]
Do we somehow guard against image name collisions when we relocate?

**Comment by jldec** [comment]
@trisberg i believe the relocated images use a hash in the name to avoid collisions e.g.

before
```yaml
     containers:
     - name: mixer
        image: "docker.io/istio/mixer:1.0.2"
        imagePullPolicy: IfNotPresent
```

after 
```yaml
      containers:
      - name: mixer
        image: "registry/repo/mixer-14ad3f9595723b4713853a3d5a1984c0"
        imagePullPolicy: IfNotPresent
```

**Comment by trisberg** [comment]
this one doesn't seem to follow that pattern:
`packs/util` -> `gcr.io/cf-sandbox-trisberg/util`

**Comment by jldec** [comment]
I think you're looking at a non-flattened relocation (my example was using `--flatten`)
i'll defer to @glyn to confirm that non-flattened relocation does not guard against collisions a.t.m.
if that's true we should file an issue.

**Comment by jldec** [comment]
My inclination would be to make --flatten the default (and only) relocation mode if the other mode is problematic.

[It also seems wrong that we allow non-flattened names and use the docker daemon as the vehicle for loading images, when those unflattened names won't work if you try to run locally using the images already loaded into docker.]

**Comment by glyn** [comment]
@trisberg wrote:
> I guess it's not possible to add a hash when not using a tag for the image.

Actually, we do add a hash. Is that a problem?

When flattening, we hash the full image name including any tag and/or digest, but we don't include a tag or a digest in the flattened name (unless the target registry is `dev.local` in which case we add the tag `:local` to prevent docker going off to the internet to find the latest image).

Specifically for an image name without a tag and when the target registry is _not_ `dev.local`, the flattened name does not have a tag. For example, `gcr.io/kaniko-project/executor` will be flattened to `reg.org/user/executor-a2dcf61ceb5f5bceb00771aea2a9a1dc`.

**Comment by glyn** [comment]
After discussion with @ericbottard, @scothis, and others, it turns out that buildpacks are covered already as part of the riff manifest relocation, but invokers would be very painful to relocate. The consensus is that we should only support buildpacks. We can safely drop JAR invoker support as we don’t think anyone is using it; @ericbottard has been working on a buildpack equivalent of the command invoker; there is now an npm buildpack which will allow the node invoker to be replaced.

Related issues:
*  node buildpack support https://github.com/projectriff/riff-buildpack/issues/12
* command buildpack support https://github.com/projectriff/riff-buildpack/issues/8
