### ISSUE TITLE
Creating subscription with reply-to channel not working properly

### ISSUE THREAD

**Issue by doddatpivotal** [projectriff/riff#899]
I'm using v0.1.3 of riff running on GKE.

I'm facing and issue with riff 0.1.3 when i create subscriptions with a reply-to channel:
```
riff subscription create -s powerof2 -c numbers -r squares
```
and then follow up with:
```
riff subscription list
```
I get:
```
NAME     CHANNEL SUBSCRIBER REPLY-TO        
powerof2 numbers powerof2   squares-channel
``` 

See that the reply to channel has a *-channel* appended to the end of it

**Comment by trisberg** [comment]
That surprised me initially as well. It is actually the name of the service that fronts the channel, so the channel name is "square" while the service name is "square-channel".  You can see the service by running `kubectl get services`. Maybe we should change the header to "REPLY-TO SERVICE".

**Comment by scothis** [comment]
We should hold off on any significant effort until we're ready to pickup the other changes with the switch to eventing.kantive.dev/v1alpha1 CRDs.

**Comment by trisberg** [comment]
Closing this for now, we can revisit if necessary when the new eventing features/CRDs are included.
