### ISSUE TITLE
`riff image relocate` option for not flattening image names

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#903]
The `--flatten` option was deleted by https://github.com/projectriff/riff/issues/901 and became the only option. Flattening should remain the default behaviour, but for registries which _do_ support hierarchical names, we should add a flag such as `--deep` to turn off flattening.

However, with flattening turned off, we should also try to reduce the likelihood of collisions for images with short paths, e.g.:
```
reg1.org/user1/x
reg2.org/user2/x
```

**Comment by jldec** [comment]
No longer required since #949.
