### ISSUE TITLE
validate riff install from relocated distro

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#917]
Now that riff-distro can create a distro, and riff can relocate the images in it, and then install from the relocated manifest, it would be helpful to validate with ci.

needs #922, #937

**Comment by glyn** [comment]
The aim is to do this in FATS for the first alpha. If we later move code to `pfs`, we can set up a separate CI with access to the private pfs repo.

**Comment by glyn** [comment]
`riff-distro` will be deleted along with the `riff image` commands, so this issue can be closed.
