### ISSUE TITLE
Get FATS green on Travis

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#922]
The build is currently broken and needs fixing.

**Comment by scothis** [comment]
Looks like an issue while watching for a running revision after `riff function create ... --wait`

See https://travis-ci.org/projectriff/fats/jobs/448497641#L646

> Error: function creation failed: RevisionMissing: Configuration "fats-uppercase-command" does not have any ready Revision.

**Comment by trisberg** [comment]
It's probably a change in how the status is reported, we made one adjustment for the scaling to zero messages we suddenly saw, could be some additional variations. There is one additional change that will be in upcoming releases https://github.com/knative/serving/pull/2348, although it didn't make the v0.2.0 release for serving.

**Comment by trisberg** [comment]
Actually looks more like a timing issue, maybe we should retry the status before assuming that the build failed.

**Comment by scothis** [comment]
Got much further before failing with the same error. Perhaps we need more than a single extra check.

See https://travis-ci.org/projectriff/fats/jobs/449170112#L2309

**Comment by georgeharley** [comment]
Still not out of the woods with this one as the fats build is still failing even with the latest code change in place (see fats build 776 at https://travis-ci.org/projectriff/fats/builds/449469497).  
A couple of points to note about build 776:
* on both GKE and minikube the failure occurs with the java invoker. On minikube the jar invoker was run first and all was fine while in GKE the command and jar invokers both went first and were fine. 
* both failures in GKE and minikube look to have occurred after the current max timeout of 1 minute has expired (verbose output shows 30 writes of the "Waiting on function creation:..." status message each 2 seconds apart). In other words, the failures appear to be consistent with the current wait logic.  
  
First thing tomorrow will see how the java invoker test fares if the 1 minute timeout is raised.

**Comment by trisberg** [comment]
Maybe we should try with the `v20181101-v0.2.0-11-g877523d` releases from serving, there was a fix that removed that intermediate failed status in https://github.com/knative/serving/pull/2348

**Comment by scothis** [comment]
🍏 https://travis-ci.org/projectriff/fats/builds/449621979
