### ISSUE TITLE
Adjust --manifest help according to available named manifests

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#933]
Now that the set of named manifests is configurable, commands which take named manifests should not assume that `stable` and `latest` are necessarily going to be present.

For example, `riff system install -h` currently includes this flag help:
```
  -m, --manifest string   manifest of kubernetes configuration files to be applied; can be a named manifest (stable or latest) or a path of a manifest file (default "stable")
```

**Comment by jldec** [comment]
Stable and latest are the only hardwired options now - closing.
