### ISSUE TITLE
create function failed with "incorrect username or password" in minikube

### ISSUE THREAD

**Issue by Lellansin** [projectriff/riff#935]
```
> riff function create node square \
  --git-repo https://github.com/projectriff-samples/node-square  \
  --artifact package.json \
  --image $DOCKER_ID/square \
  --verbose

Waiting for LatestCreatedRevisionName:. square-00001
default/square-00001-7g49s[build-step-git-source]: {"level":"info","ts":1541395240.2342284,"logger":"fallback-logger","caller":"git-init/main.go:74","msg":"Successfully cloned \"https://github.com/projectriff-samples/node-square\" @ \"master\""}
default/square-00001-7g49s[build-step-riff-init]: Initializing with node invoker
default/square-00001-7g49s[build-step-riff-init]: Initializing /workspace/Dockerfile
default/square-00001-7g49s[build-step-riff-init]: Initializing /workspace/.dockerignore
default/square-00001-7g49s[build-step-build-and-push]: INFO[0000] Removing ignored files from build context: [node_modules]
default/square-00001-7g49s[build-step-build-and-push]: INFO[0000] Downloading base image projectriff/node-function-invoker:0.0.8
default/square-00001-7g49s[build-step-build-and-push]: error building image: getting stage builder for stage 0: no token in bearer response:
default/square-00001-7g49s[build-step-build-and-push]: {"details":"incorrect username or password"}
default/square-00001-7g49s[build-step-build-and-push]:

Error: function creation failed: RevisionMissing: Configuration "square" does not have any ready Revision.; Revision "square-00001" failed with message: "build step \"build-step-build-and-push\" exited with code 1 (image: \"docker-pullable://gcr.io/kaniko-project/executor@sha256:6eb764a69b26888855213f9f09f8ac82910151ddcade4bb270c39363b1cbaaf9\"); for logs run: kubectl -n default logs square-00001-7g49s -c build-step-build-and-push".
```
I did follow the step in Document, but got this error while create function by riff cli. Should I login in sth. like gcr locally? or should I config some file in somewhere?

**Comment by trisberg** [comment]
It seems that there currently are issues having the Knative build step push GCR from a cluster that isn't running on GKE withing the same GCP Project. See #879 and also https://github.com/knative/build/issues/450

**Comment by Lellansin** [comment]
> It seems that there currently are issues having the Knative build step push GCR from a cluster that isn't running on GKE withing the same GCP Project. See #879 and also [knative/build#450](https://github.com/knative/build/issues/450)
> 
> For now you are better off pushing the image to DockeHub.

Hi @trisberg , thanks for your reply. I'm green to k8s & knative, so I'm confused about `pushing the image`. I guess there is an image built by riff among the create process, then I should find it and push it to GCR manually?

**Comment by trisberg** [comment]
Yes, `function create node` starts a build in the cluster that at the end pushes the image to a registry based on the `$DOCKER_ID` used for the `--image` you specified.

I assumed you used GCR but if you are using DockerHub then you just need to provide the password for the id specified as `DOCKER_ID`.

Try running:

```
riff namespace init default --dockerhub $DOCKER_ID
```

and provide the password when prompted.

Then you can remove the function from the first attempt using:

```
riff service delete square
```

and try your `function create` again.

**Comment by Lellansin** [comment]
Wow, I'v solved the problem with this steps. Thanks for your time!
