### ISSUE TITLE
Samples should build and run when riff is deployed with helm

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#96]
Samples are using Dockerfiles pointing to invoker base images like `projectriff/node-function-invoker:0.0.1-SNAPSHOT`

After a full local build of all riff components, the matching base images are included in the docker registry cache. This is not the case when deploying riff using helm .

**Comment by trisberg** [comment]
Since the 0.0.1 release the samples use a base image from the latest release, currently 0.0.1. The only exception is the python/uppercase sample that uses a Python base image.
