### ISSUE TITLE
Document how to install a registry on localhost 

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#980]
To preserve the ability to run demos in poorly-networked environments we need an alternative to `function create --local-path` using images named `dev.local/...`.

For now, this could be a doc page (or readme file) describing how to install and configure a localhost docker image registry.

**Comment by jldec** [comment]
not required for v0.2.0 milestone.

**Comment by scothis** [comment]
FATS does this with the docker-daemon registry, but [it requires](https://github.com/projectriff/fats/blob/master/registries/docker-daemon/configure.sh#L8-L11) [a number](https://github.com/projectriff/fats/blob/master/registries/docker-daemon/start.sh#L7-L33) [of hoops](https://github.com/projectriff/fats/blob/27ada4fb08d0ed9bf22ad1c630dd8af181690452/clusters/kind/configure.sh#L18-L45) and I don't think it's appropriate to support. All riff really cares is that there is a registry it can talk to. It doesn't care where that registry is.
